/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "lib/clk_gen.v:8" *)
module clk_gen(clk_f, clk_2f, clk_4f, clk_32f, reset);
  (* src = "lib/clk_gen.v:9" *)
  output clk_2f;
  (* src = "lib/clk_gen.v:11" *)
  input clk_32f;
  (* src = "lib/clk_gen.v:10" *)
  output clk_4f;
  (* src = "lib/clk_gen.v:8" *)
  output clk_f;
  (* src = "lib/clk_gen.v:14" *)
  wire q2;
  (* src = "lib/clk_gen.v:12" *)
  input reset;
  assign clk_2f = 1'h0;
  assign clk_4f = 1'h0;
  assign clk_f = 1'h0;
  assign q2 = 1'h0;
endmodule
