/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "lib/byte_striping.v:7" *)
module BYTE_STRIPING(lane_0, lane_1, valid_0, valid_1, data_in, valid_in, clk_2f, clk_f);
  (* src = "lib/byte_striping.v:14" *)
  wire [31:0] _000_;
  (* src = "lib/byte_striping.v:14" *)
  wire [31:0] _001_;
  (* src = "lib/byte_striping.v:14" *)
  wire _002_;
  (* src = "lib/byte_striping.v:14" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  (* src = "lib/byte_striping.v:12" *)
  input clk_2f;
  (* src = "lib/byte_striping.v:12" *)
  input clk_f;
  (* src = "lib/byte_striping.v:10" *)
  input [31:0] data_in;
  (* src = "lib/byte_striping.v:8" *)
  output [31:0] lane_0;
  (* src = "lib/byte_striping.v:8" *)
  output [31:0] lane_1;
  (* src = "lib/byte_striping.v:9" *)
  output valid_0;
  (* src = "lib/byte_striping.v:9" *)
  output valid_1;
  (* src = "lib/byte_striping.v:11" *)
  input valid_in;
  NOT _233_ (
    .A(clk_f),
    .Y(_004_)
  );
  NOR _234_ (
    .A(lane_1[0]),
    .B(clk_f),
    .Y(_005_)
  );
  NAND _235_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_006_)
  );
  NAND _236_ (
    .A(clk_f),
    .B(_006_),
    .Y(_007_)
  );
  NOT _237_ (
    .A(_007_),
    .Y(_008_)
  );
  NOR _238_ (
    .A(_005_),
    .B(_008_),
    .Y(_001_[0])
  );
  NOR _239_ (
    .A(clk_f),
    .B(lane_1[1]),
    .Y(_009_)
  );
  NAND _240_ (
    .A(data_in[1]),
    .B(valid_in),
    .Y(_010_)
  );
  NAND _241_ (
    .A(clk_f),
    .B(_010_),
    .Y(_011_)
  );
  NOT _242_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR _243_ (
    .A(_009_),
    .B(_012_),
    .Y(_001_[1])
  );
  NOR _244_ (
    .A(clk_f),
    .B(lane_1[2]),
    .Y(_013_)
  );
  NAND _245_ (
    .A(valid_in),
    .B(data_in[2]),
    .Y(_014_)
  );
  NAND _246_ (
    .A(clk_f),
    .B(_014_),
    .Y(_015_)
  );
  NOT _247_ (
    .A(_015_),
    .Y(_016_)
  );
  NOR _248_ (
    .A(_013_),
    .B(_016_),
    .Y(_001_[2])
  );
  NOR _249_ (
    .A(clk_f),
    .B(lane_1[3]),
    .Y(_017_)
  );
  NAND _250_ (
    .A(valid_in),
    .B(data_in[3]),
    .Y(_018_)
  );
  NAND _251_ (
    .A(clk_f),
    .B(_018_),
    .Y(_019_)
  );
  NOT _252_ (
    .A(_019_),
    .Y(_020_)
  );
  NOR _253_ (
    .A(_017_),
    .B(_020_),
    .Y(_001_[3])
  );
  NOR _254_ (
    .A(clk_f),
    .B(lane_1[4]),
    .Y(_021_)
  );
  NAND _255_ (
    .A(valid_in),
    .B(data_in[4]),
    .Y(_022_)
  );
  NAND _256_ (
    .A(clk_f),
    .B(_022_),
    .Y(_023_)
  );
  NOT _257_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _258_ (
    .A(_021_),
    .B(_024_),
    .Y(_001_[4])
  );
  NOR _259_ (
    .A(clk_f),
    .B(lane_1[5]),
    .Y(_025_)
  );
  NAND _260_ (
    .A(valid_in),
    .B(data_in[5]),
    .Y(_026_)
  );
  NAND _261_ (
    .A(clk_f),
    .B(_026_),
    .Y(_027_)
  );
  NOT _262_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _263_ (
    .A(_025_),
    .B(_028_),
    .Y(_001_[5])
  );
  NOR _264_ (
    .A(clk_f),
    .B(lane_1[6]),
    .Y(_029_)
  );
  NAND _265_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_030_)
  );
  NAND _266_ (
    .A(clk_f),
    .B(_030_),
    .Y(_031_)
  );
  NOT _267_ (
    .A(_031_),
    .Y(_032_)
  );
  NOR _268_ (
    .A(_029_),
    .B(_032_),
    .Y(_001_[6])
  );
  NOR _269_ (
    .A(clk_f),
    .B(lane_1[7]),
    .Y(_033_)
  );
  NAND _270_ (
    .A(valid_in),
    .B(data_in[7]),
    .Y(_034_)
  );
  NAND _271_ (
    .A(clk_f),
    .B(_034_),
    .Y(_035_)
  );
  NOT _272_ (
    .A(_035_),
    .Y(_036_)
  );
  NOR _273_ (
    .A(_033_),
    .B(_036_),
    .Y(_001_[7])
  );
  NOR _274_ (
    .A(clk_f),
    .B(lane_1[8]),
    .Y(_037_)
  );
  NAND _275_ (
    .A(valid_in),
    .B(data_in[8]),
    .Y(_038_)
  );
  NAND _276_ (
    .A(clk_f),
    .B(_038_),
    .Y(_039_)
  );
  NOT _277_ (
    .A(_039_),
    .Y(_040_)
  );
  NOR _278_ (
    .A(_037_),
    .B(_040_),
    .Y(_001_[8])
  );
  NOR _279_ (
    .A(clk_f),
    .B(lane_1[9]),
    .Y(_041_)
  );
  NAND _280_ (
    .A(valid_in),
    .B(data_in[9]),
    .Y(_042_)
  );
  NAND _281_ (
    .A(clk_f),
    .B(_042_),
    .Y(_043_)
  );
  NOT _282_ (
    .A(_043_),
    .Y(_044_)
  );
  NOR _283_ (
    .A(_041_),
    .B(_044_),
    .Y(_001_[9])
  );
  NOR _284_ (
    .A(clk_f),
    .B(lane_1[10]),
    .Y(_045_)
  );
  NAND _285_ (
    .A(valid_in),
    .B(data_in[10]),
    .Y(_046_)
  );
  NAND _286_ (
    .A(clk_f),
    .B(_046_),
    .Y(_047_)
  );
  NOT _287_ (
    .A(_047_),
    .Y(_048_)
  );
  NOR _288_ (
    .A(_045_),
    .B(_048_),
    .Y(_001_[10])
  );
  NOR _289_ (
    .A(clk_f),
    .B(lane_1[11]),
    .Y(_049_)
  );
  NAND _290_ (
    .A(valid_in),
    .B(data_in[11]),
    .Y(_050_)
  );
  NAND _291_ (
    .A(clk_f),
    .B(_050_),
    .Y(_051_)
  );
  NOT _292_ (
    .A(_051_),
    .Y(_052_)
  );
  NOR _293_ (
    .A(_049_),
    .B(_052_),
    .Y(_001_[11])
  );
  NOR _294_ (
    .A(clk_f),
    .B(lane_1[12]),
    .Y(_053_)
  );
  NAND _295_ (
    .A(valid_in),
    .B(data_in[12]),
    .Y(_054_)
  );
  NAND _296_ (
    .A(clk_f),
    .B(_054_),
    .Y(_055_)
  );
  NOT _297_ (
    .A(_055_),
    .Y(_056_)
  );
  NOR _298_ (
    .A(_053_),
    .B(_056_),
    .Y(_001_[12])
  );
  NOR _299_ (
    .A(clk_f),
    .B(lane_1[13]),
    .Y(_057_)
  );
  NAND _300_ (
    .A(valid_in),
    .B(data_in[13]),
    .Y(_058_)
  );
  NAND _301_ (
    .A(clk_f),
    .B(_058_),
    .Y(_059_)
  );
  NOT _302_ (
    .A(_059_),
    .Y(_060_)
  );
  NOR _303_ (
    .A(_057_),
    .B(_060_),
    .Y(_001_[13])
  );
  NOR _304_ (
    .A(clk_f),
    .B(lane_1[14]),
    .Y(_061_)
  );
  NAND _305_ (
    .A(valid_in),
    .B(data_in[14]),
    .Y(_062_)
  );
  NAND _306_ (
    .A(clk_f),
    .B(_062_),
    .Y(_063_)
  );
  NOT _307_ (
    .A(_063_),
    .Y(_064_)
  );
  NOR _308_ (
    .A(_061_),
    .B(_064_),
    .Y(_001_[14])
  );
  NOR _309_ (
    .A(clk_f),
    .B(lane_1[15]),
    .Y(_065_)
  );
  NAND _310_ (
    .A(valid_in),
    .B(data_in[15]),
    .Y(_066_)
  );
  NAND _311_ (
    .A(clk_f),
    .B(_066_),
    .Y(_067_)
  );
  NOT _312_ (
    .A(_067_),
    .Y(_068_)
  );
  NOR _313_ (
    .A(_065_),
    .B(_068_),
    .Y(_001_[15])
  );
  NOR _314_ (
    .A(clk_f),
    .B(lane_1[16]),
    .Y(_069_)
  );
  NAND _315_ (
    .A(valid_in),
    .B(data_in[16]),
    .Y(_070_)
  );
  NAND _316_ (
    .A(clk_f),
    .B(_070_),
    .Y(_071_)
  );
  NOT _317_ (
    .A(_071_),
    .Y(_072_)
  );
  NOR _318_ (
    .A(_069_),
    .B(_072_),
    .Y(_001_[16])
  );
  NOR _319_ (
    .A(clk_f),
    .B(lane_1[17]),
    .Y(_073_)
  );
  NAND _320_ (
    .A(valid_in),
    .B(data_in[17]),
    .Y(_074_)
  );
  NAND _321_ (
    .A(clk_f),
    .B(_074_),
    .Y(_075_)
  );
  NOT _322_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _323_ (
    .A(_073_),
    .B(_076_),
    .Y(_001_[17])
  );
  NOR _324_ (
    .A(clk_f),
    .B(lane_1[18]),
    .Y(_077_)
  );
  NAND _325_ (
    .A(valid_in),
    .B(data_in[18]),
    .Y(_078_)
  );
  NAND _326_ (
    .A(clk_f),
    .B(_078_),
    .Y(_079_)
  );
  NOT _327_ (
    .A(_079_),
    .Y(_080_)
  );
  NOR _328_ (
    .A(_077_),
    .B(_080_),
    .Y(_001_[18])
  );
  NOR _329_ (
    .A(clk_f),
    .B(lane_1[19]),
    .Y(_081_)
  );
  NAND _330_ (
    .A(valid_in),
    .B(data_in[19]),
    .Y(_082_)
  );
  NAND _331_ (
    .A(clk_f),
    .B(_082_),
    .Y(_083_)
  );
  NOT _332_ (
    .A(_083_),
    .Y(_084_)
  );
  NOR _333_ (
    .A(_081_),
    .B(_084_),
    .Y(_001_[19])
  );
  NOR _334_ (
    .A(clk_f),
    .B(lane_1[20]),
    .Y(_085_)
  );
  NAND _335_ (
    .A(valid_in),
    .B(data_in[20]),
    .Y(_086_)
  );
  NAND _336_ (
    .A(clk_f),
    .B(_086_),
    .Y(_087_)
  );
  NOT _337_ (
    .A(_087_),
    .Y(_088_)
  );
  NOR _338_ (
    .A(_085_),
    .B(_088_),
    .Y(_001_[20])
  );
  NOR _339_ (
    .A(clk_f),
    .B(lane_1[21]),
    .Y(_089_)
  );
  NAND _340_ (
    .A(valid_in),
    .B(data_in[21]),
    .Y(_090_)
  );
  NAND _341_ (
    .A(clk_f),
    .B(_090_),
    .Y(_091_)
  );
  NOT _342_ (
    .A(_091_),
    .Y(_092_)
  );
  NOR _343_ (
    .A(_089_),
    .B(_092_),
    .Y(_001_[21])
  );
  NOR _344_ (
    .A(clk_f),
    .B(lane_1[22]),
    .Y(_093_)
  );
  NAND _345_ (
    .A(valid_in),
    .B(data_in[22]),
    .Y(_094_)
  );
  NAND _346_ (
    .A(clk_f),
    .B(_094_),
    .Y(_095_)
  );
  NOT _347_ (
    .A(_095_),
    .Y(_096_)
  );
  NOR _348_ (
    .A(_093_),
    .B(_096_),
    .Y(_001_[22])
  );
  NOR _349_ (
    .A(clk_f),
    .B(lane_1[23]),
    .Y(_097_)
  );
  NAND _350_ (
    .A(valid_in),
    .B(data_in[23]),
    .Y(_098_)
  );
  NAND _351_ (
    .A(clk_f),
    .B(_098_),
    .Y(_099_)
  );
  NOT _352_ (
    .A(_099_),
    .Y(_100_)
  );
  NOR _353_ (
    .A(_097_),
    .B(_100_),
    .Y(_001_[23])
  );
  NOR _354_ (
    .A(clk_f),
    .B(lane_1[24]),
    .Y(_101_)
  );
  NAND _355_ (
    .A(valid_in),
    .B(data_in[24]),
    .Y(_102_)
  );
  NAND _356_ (
    .A(clk_f),
    .B(_102_),
    .Y(_103_)
  );
  NOT _357_ (
    .A(_103_),
    .Y(_104_)
  );
  NOR _358_ (
    .A(_101_),
    .B(_104_),
    .Y(_001_[24])
  );
  NOR _359_ (
    .A(clk_f),
    .B(lane_1[25]),
    .Y(_105_)
  );
  NAND _360_ (
    .A(valid_in),
    .B(data_in[25]),
    .Y(_106_)
  );
  NAND _361_ (
    .A(clk_f),
    .B(_106_),
    .Y(_107_)
  );
  NOT _362_ (
    .A(_107_),
    .Y(_108_)
  );
  NOR _363_ (
    .A(_105_),
    .B(_108_),
    .Y(_001_[25])
  );
  NOR _364_ (
    .A(clk_f),
    .B(lane_1[26]),
    .Y(_109_)
  );
  NAND _365_ (
    .A(valid_in),
    .B(data_in[26]),
    .Y(_110_)
  );
  NAND _366_ (
    .A(clk_f),
    .B(_110_),
    .Y(_111_)
  );
  NOT _367_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _368_ (
    .A(_109_),
    .B(_112_),
    .Y(_001_[26])
  );
  NOR _369_ (
    .A(clk_f),
    .B(lane_1[27]),
    .Y(_113_)
  );
  NAND _370_ (
    .A(valid_in),
    .B(data_in[27]),
    .Y(_114_)
  );
  NAND _371_ (
    .A(clk_f),
    .B(_114_),
    .Y(_115_)
  );
  NOT _372_ (
    .A(_115_),
    .Y(_116_)
  );
  NOR _373_ (
    .A(_113_),
    .B(_116_),
    .Y(_001_[27])
  );
  NOR _374_ (
    .A(clk_f),
    .B(lane_1[28]),
    .Y(_117_)
  );
  NAND _375_ (
    .A(valid_in),
    .B(data_in[28]),
    .Y(_118_)
  );
  NAND _376_ (
    .A(clk_f),
    .B(_118_),
    .Y(_119_)
  );
  NOT _377_ (
    .A(_119_),
    .Y(_120_)
  );
  NOR _378_ (
    .A(_117_),
    .B(_120_),
    .Y(_001_[28])
  );
  NOR _379_ (
    .A(clk_f),
    .B(lane_1[29]),
    .Y(_121_)
  );
  NAND _380_ (
    .A(valid_in),
    .B(data_in[29]),
    .Y(_122_)
  );
  NAND _381_ (
    .A(clk_f),
    .B(_122_),
    .Y(_123_)
  );
  NOT _382_ (
    .A(_123_),
    .Y(_124_)
  );
  NOR _383_ (
    .A(_121_),
    .B(_124_),
    .Y(_001_[29])
  );
  NOR _384_ (
    .A(clk_f),
    .B(lane_1[30]),
    .Y(_125_)
  );
  NAND _385_ (
    .A(valid_in),
    .B(data_in[30]),
    .Y(_126_)
  );
  NAND _386_ (
    .A(clk_f),
    .B(_126_),
    .Y(_127_)
  );
  NOT _387_ (
    .A(_127_),
    .Y(_128_)
  );
  NOR _388_ (
    .A(_125_),
    .B(_128_),
    .Y(_001_[30])
  );
  NOR _389_ (
    .A(clk_f),
    .B(lane_1[31]),
    .Y(_129_)
  );
  NAND _390_ (
    .A(valid_in),
    .B(data_in[31]),
    .Y(_130_)
  );
  NAND _391_ (
    .A(clk_f),
    .B(_130_),
    .Y(_131_)
  );
  NOT _392_ (
    .A(_131_),
    .Y(_132_)
  );
  NOR _393_ (
    .A(_129_),
    .B(_132_),
    .Y(_001_[31])
  );
  NAND _394_ (
    .A(valid_in),
    .B(clk_f),
    .Y(_133_)
  );
  NAND _395_ (
    .A(_004_),
    .B(valid_1),
    .Y(_134_)
  );
  NAND _396_ (
    .A(_133_),
    .B(_134_),
    .Y(_003_)
  );
  NAND _397_ (
    .A(clk_f),
    .B(valid_0),
    .Y(_135_)
  );
  NAND _398_ (
    .A(valid_in),
    .B(_004_),
    .Y(_136_)
  );
  NAND _399_ (
    .A(_135_),
    .B(_136_),
    .Y(_002_)
  );
  NAND _400_ (
    .A(clk_f),
    .B(lane_0[0]),
    .Y(_137_)
  );
  NOR _401_ (
    .A(clk_f),
    .B(_006_),
    .Y(_138_)
  );
  NOT _402_ (
    .A(_138_),
    .Y(_139_)
  );
  NAND _403_ (
    .A(_137_),
    .B(_139_),
    .Y(_000_[0])
  );
  NAND _404_ (
    .A(clk_f),
    .B(lane_0[1]),
    .Y(_140_)
  );
  NOR _405_ (
    .A(clk_f),
    .B(_010_),
    .Y(_141_)
  );
  NOT _406_ (
    .A(_141_),
    .Y(_142_)
  );
  NAND _407_ (
    .A(_140_),
    .B(_142_),
    .Y(_000_[1])
  );
  NAND _408_ (
    .A(clk_f),
    .B(lane_0[2]),
    .Y(_143_)
  );
  NOR _409_ (
    .A(clk_f),
    .B(_014_),
    .Y(_144_)
  );
  NOT _410_ (
    .A(_144_),
    .Y(_145_)
  );
  NAND _411_ (
    .A(_143_),
    .B(_145_),
    .Y(_000_[2])
  );
  NAND _412_ (
    .A(clk_f),
    .B(lane_0[3]),
    .Y(_146_)
  );
  NOR _413_ (
    .A(clk_f),
    .B(_018_),
    .Y(_147_)
  );
  NOT _414_ (
    .A(_147_),
    .Y(_148_)
  );
  NAND _415_ (
    .A(_146_),
    .B(_148_),
    .Y(_000_[3])
  );
  NAND _416_ (
    .A(clk_f),
    .B(lane_0[4]),
    .Y(_149_)
  );
  NOR _417_ (
    .A(clk_f),
    .B(_022_),
    .Y(_150_)
  );
  NOT _418_ (
    .A(_150_),
    .Y(_151_)
  );
  NAND _419_ (
    .A(_149_),
    .B(_151_),
    .Y(_000_[4])
  );
  NAND _420_ (
    .A(clk_f),
    .B(lane_0[5]),
    .Y(_152_)
  );
  NOR _421_ (
    .A(clk_f),
    .B(_026_),
    .Y(_153_)
  );
  NOT _422_ (
    .A(_153_),
    .Y(_154_)
  );
  NAND _423_ (
    .A(_152_),
    .B(_154_),
    .Y(_000_[5])
  );
  NAND _424_ (
    .A(clk_f),
    .B(lane_0[6]),
    .Y(_155_)
  );
  NOR _425_ (
    .A(clk_f),
    .B(_030_),
    .Y(_156_)
  );
  NOT _426_ (
    .A(_156_),
    .Y(_157_)
  );
  NAND _427_ (
    .A(_155_),
    .B(_157_),
    .Y(_000_[6])
  );
  NAND _428_ (
    .A(clk_f),
    .B(lane_0[7]),
    .Y(_158_)
  );
  NOR _429_ (
    .A(clk_f),
    .B(_034_),
    .Y(_159_)
  );
  NOT _430_ (
    .A(_159_),
    .Y(_160_)
  );
  NAND _431_ (
    .A(_158_),
    .B(_160_),
    .Y(_000_[7])
  );
  NAND _432_ (
    .A(clk_f),
    .B(lane_0[8]),
    .Y(_161_)
  );
  NOR _433_ (
    .A(clk_f),
    .B(_038_),
    .Y(_162_)
  );
  NOT _434_ (
    .A(_162_),
    .Y(_163_)
  );
  NAND _435_ (
    .A(_161_),
    .B(_163_),
    .Y(_000_[8])
  );
  NAND _436_ (
    .A(clk_f),
    .B(lane_0[9]),
    .Y(_164_)
  );
  NOR _437_ (
    .A(clk_f),
    .B(_042_),
    .Y(_165_)
  );
  NOT _438_ (
    .A(_165_),
    .Y(_166_)
  );
  NAND _439_ (
    .A(_164_),
    .B(_166_),
    .Y(_000_[9])
  );
  NAND _440_ (
    .A(clk_f),
    .B(lane_0[10]),
    .Y(_167_)
  );
  NOR _441_ (
    .A(clk_f),
    .B(_046_),
    .Y(_168_)
  );
  NOT _442_ (
    .A(_168_),
    .Y(_169_)
  );
  NAND _443_ (
    .A(_167_),
    .B(_169_),
    .Y(_000_[10])
  );
  NAND _444_ (
    .A(clk_f),
    .B(lane_0[11]),
    .Y(_170_)
  );
  NOR _445_ (
    .A(clk_f),
    .B(_050_),
    .Y(_171_)
  );
  NOT _446_ (
    .A(_171_),
    .Y(_172_)
  );
  NAND _447_ (
    .A(_170_),
    .B(_172_),
    .Y(_000_[11])
  );
  NAND _448_ (
    .A(clk_f),
    .B(lane_0[12]),
    .Y(_173_)
  );
  NOR _449_ (
    .A(clk_f),
    .B(_054_),
    .Y(_174_)
  );
  NOT _450_ (
    .A(_174_),
    .Y(_175_)
  );
  NAND _451_ (
    .A(_173_),
    .B(_175_),
    .Y(_000_[12])
  );
  NAND _452_ (
    .A(clk_f),
    .B(lane_0[13]),
    .Y(_176_)
  );
  NOR _453_ (
    .A(clk_f),
    .B(_058_),
    .Y(_177_)
  );
  NOT _454_ (
    .A(_177_),
    .Y(_178_)
  );
  NAND _455_ (
    .A(_176_),
    .B(_178_),
    .Y(_000_[13])
  );
  NAND _456_ (
    .A(clk_f),
    .B(lane_0[14]),
    .Y(_179_)
  );
  NOR _457_ (
    .A(clk_f),
    .B(_062_),
    .Y(_180_)
  );
  NOT _458_ (
    .A(_180_),
    .Y(_181_)
  );
  NAND _459_ (
    .A(_179_),
    .B(_181_),
    .Y(_000_[14])
  );
  NAND _460_ (
    .A(clk_f),
    .B(lane_0[15]),
    .Y(_182_)
  );
  NOR _461_ (
    .A(clk_f),
    .B(_066_),
    .Y(_183_)
  );
  NOT _462_ (
    .A(_183_),
    .Y(_184_)
  );
  NAND _463_ (
    .A(_182_),
    .B(_184_),
    .Y(_000_[15])
  );
  NAND _464_ (
    .A(clk_f),
    .B(lane_0[16]),
    .Y(_185_)
  );
  NOR _465_ (
    .A(clk_f),
    .B(_070_),
    .Y(_186_)
  );
  NOT _466_ (
    .A(_186_),
    .Y(_187_)
  );
  NAND _467_ (
    .A(_185_),
    .B(_187_),
    .Y(_000_[16])
  );
  NAND _468_ (
    .A(clk_f),
    .B(lane_0[17]),
    .Y(_188_)
  );
  NOR _469_ (
    .A(clk_f),
    .B(_074_),
    .Y(_189_)
  );
  NOT _470_ (
    .A(_189_),
    .Y(_190_)
  );
  NAND _471_ (
    .A(_188_),
    .B(_190_),
    .Y(_000_[17])
  );
  NAND _472_ (
    .A(clk_f),
    .B(lane_0[18]),
    .Y(_191_)
  );
  NOR _473_ (
    .A(clk_f),
    .B(_078_),
    .Y(_192_)
  );
  NOT _474_ (
    .A(_192_),
    .Y(_193_)
  );
  NAND _475_ (
    .A(_191_),
    .B(_193_),
    .Y(_000_[18])
  );
  NAND _476_ (
    .A(clk_f),
    .B(lane_0[19]),
    .Y(_194_)
  );
  NOR _477_ (
    .A(clk_f),
    .B(_082_),
    .Y(_195_)
  );
  NOT _478_ (
    .A(_195_),
    .Y(_196_)
  );
  NAND _479_ (
    .A(_194_),
    .B(_196_),
    .Y(_000_[19])
  );
  NAND _480_ (
    .A(clk_f),
    .B(lane_0[20]),
    .Y(_197_)
  );
  NOR _481_ (
    .A(clk_f),
    .B(_086_),
    .Y(_198_)
  );
  NOT _482_ (
    .A(_198_),
    .Y(_199_)
  );
  NAND _483_ (
    .A(_197_),
    .B(_199_),
    .Y(_000_[20])
  );
  NAND _484_ (
    .A(clk_f),
    .B(lane_0[21]),
    .Y(_200_)
  );
  NOR _485_ (
    .A(clk_f),
    .B(_090_),
    .Y(_201_)
  );
  NOT _486_ (
    .A(_201_),
    .Y(_202_)
  );
  NAND _487_ (
    .A(_200_),
    .B(_202_),
    .Y(_000_[21])
  );
  NAND _488_ (
    .A(clk_f),
    .B(lane_0[22]),
    .Y(_203_)
  );
  NOR _489_ (
    .A(clk_f),
    .B(_094_),
    .Y(_204_)
  );
  NOT _490_ (
    .A(_204_),
    .Y(_205_)
  );
  NAND _491_ (
    .A(_203_),
    .B(_205_),
    .Y(_000_[22])
  );
  NAND _492_ (
    .A(clk_f),
    .B(lane_0[23]),
    .Y(_206_)
  );
  NOR _493_ (
    .A(clk_f),
    .B(_098_),
    .Y(_207_)
  );
  NOT _494_ (
    .A(_207_),
    .Y(_208_)
  );
  NAND _495_ (
    .A(_206_),
    .B(_208_),
    .Y(_000_[23])
  );
  NAND _496_ (
    .A(clk_f),
    .B(lane_0[24]),
    .Y(_209_)
  );
  NOR _497_ (
    .A(clk_f),
    .B(_102_),
    .Y(_210_)
  );
  NOT _498_ (
    .A(_210_),
    .Y(_211_)
  );
  NAND _499_ (
    .A(_209_),
    .B(_211_),
    .Y(_000_[24])
  );
  NAND _500_ (
    .A(clk_f),
    .B(lane_0[25]),
    .Y(_212_)
  );
  NOR _501_ (
    .A(clk_f),
    .B(_106_),
    .Y(_213_)
  );
  NOT _502_ (
    .A(_213_),
    .Y(_214_)
  );
  NAND _503_ (
    .A(_212_),
    .B(_214_),
    .Y(_000_[25])
  );
  NAND _504_ (
    .A(clk_f),
    .B(lane_0[26]),
    .Y(_215_)
  );
  NOR _505_ (
    .A(clk_f),
    .B(_110_),
    .Y(_216_)
  );
  NOT _506_ (
    .A(_216_),
    .Y(_217_)
  );
  NAND _507_ (
    .A(_215_),
    .B(_217_),
    .Y(_000_[26])
  );
  NAND _508_ (
    .A(clk_f),
    .B(lane_0[27]),
    .Y(_218_)
  );
  NOR _509_ (
    .A(clk_f),
    .B(_114_),
    .Y(_219_)
  );
  NOT _510_ (
    .A(_219_),
    .Y(_220_)
  );
  NAND _511_ (
    .A(_218_),
    .B(_220_),
    .Y(_000_[27])
  );
  NAND _512_ (
    .A(clk_f),
    .B(lane_0[28]),
    .Y(_221_)
  );
  NOR _513_ (
    .A(clk_f),
    .B(_118_),
    .Y(_222_)
  );
  NOT _514_ (
    .A(_222_),
    .Y(_223_)
  );
  NAND _515_ (
    .A(_221_),
    .B(_223_),
    .Y(_000_[28])
  );
  NAND _516_ (
    .A(clk_f),
    .B(lane_0[29]),
    .Y(_224_)
  );
  NOR _517_ (
    .A(clk_f),
    .B(_122_),
    .Y(_225_)
  );
  NOT _518_ (
    .A(_225_),
    .Y(_226_)
  );
  NAND _519_ (
    .A(_224_),
    .B(_226_),
    .Y(_000_[29])
  );
  NAND _520_ (
    .A(clk_f),
    .B(lane_0[30]),
    .Y(_227_)
  );
  NOR _521_ (
    .A(clk_f),
    .B(_126_),
    .Y(_228_)
  );
  NOT _522_ (
    .A(_228_),
    .Y(_229_)
  );
  NAND _523_ (
    .A(_227_),
    .B(_229_),
    .Y(_000_[30])
  );
  NAND _524_ (
    .A(clk_f),
    .B(lane_0[31]),
    .Y(_230_)
  );
  NOR _525_ (
    .A(clk_f),
    .B(_130_),
    .Y(_231_)
  );
  NOT _526_ (
    .A(_231_),
    .Y(_232_)
  );
  NAND _527_ (
    .A(_230_),
    .B(_232_),
    .Y(_000_[31])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _528_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(lane_0[0])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _529_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(lane_0[1])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _530_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(lane_0[2])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _531_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(lane_0[3])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _532_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(lane_0[4])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _533_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(lane_0[5])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _534_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(lane_0[6])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _535_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(lane_0[7])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _536_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(lane_0[8])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _537_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(lane_0[9])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _538_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(lane_0[10])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _539_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(lane_0[11])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _540_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(lane_0[12])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _541_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(lane_0[13])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _542_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(lane_0[14])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _543_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(lane_0[15])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _544_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(lane_0[16])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _545_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(lane_0[17])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _546_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(lane_0[18])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _547_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(lane_0[19])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _548_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(lane_0[20])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _549_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(lane_0[21])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _550_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(lane_0[22])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _551_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(lane_0[23])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _552_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(lane_0[24])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _553_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(lane_0[25])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _554_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(lane_0[26])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _555_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(lane_0[27])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _556_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(lane_0[28])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _557_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(lane_0[29])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _558_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(lane_0[30])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _559_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(lane_0[31])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _560_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(lane_1[0])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _561_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(lane_1[1])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _562_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(lane_1[2])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _563_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(lane_1[3])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _564_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(lane_1[4])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _565_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(lane_1[5])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _566_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(lane_1[6])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _567_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(lane_1[7])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _568_ (
    .C(clk_2f),
    .D(_001_[8]),
    .Q(lane_1[8])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _569_ (
    .C(clk_2f),
    .D(_001_[9]),
    .Q(lane_1[9])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _570_ (
    .C(clk_2f),
    .D(_001_[10]),
    .Q(lane_1[10])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _571_ (
    .C(clk_2f),
    .D(_001_[11]),
    .Q(lane_1[11])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _572_ (
    .C(clk_2f),
    .D(_001_[12]),
    .Q(lane_1[12])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _573_ (
    .C(clk_2f),
    .D(_001_[13]),
    .Q(lane_1[13])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _574_ (
    .C(clk_2f),
    .D(_001_[14]),
    .Q(lane_1[14])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _575_ (
    .C(clk_2f),
    .D(_001_[15]),
    .Q(lane_1[15])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _576_ (
    .C(clk_2f),
    .D(_001_[16]),
    .Q(lane_1[16])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _577_ (
    .C(clk_2f),
    .D(_001_[17]),
    .Q(lane_1[17])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _578_ (
    .C(clk_2f),
    .D(_001_[18]),
    .Q(lane_1[18])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _579_ (
    .C(clk_2f),
    .D(_001_[19]),
    .Q(lane_1[19])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _580_ (
    .C(clk_2f),
    .D(_001_[20]),
    .Q(lane_1[20])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _581_ (
    .C(clk_2f),
    .D(_001_[21]),
    .Q(lane_1[21])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _582_ (
    .C(clk_2f),
    .D(_001_[22]),
    .Q(lane_1[22])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _583_ (
    .C(clk_2f),
    .D(_001_[23]),
    .Q(lane_1[23])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _584_ (
    .C(clk_2f),
    .D(_001_[24]),
    .Q(lane_1[24])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _585_ (
    .C(clk_2f),
    .D(_001_[25]),
    .Q(lane_1[25])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _586_ (
    .C(clk_2f),
    .D(_001_[26]),
    .Q(lane_1[26])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _587_ (
    .C(clk_2f),
    .D(_001_[27]),
    .Q(lane_1[27])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _588_ (
    .C(clk_2f),
    .D(_001_[28]),
    .Q(lane_1[28])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _589_ (
    .C(clk_2f),
    .D(_001_[29]),
    .Q(lane_1[29])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _590_ (
    .C(clk_2f),
    .D(_001_[30]),
    .Q(lane_1[30])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _591_ (
    .C(clk_2f),
    .D(_001_[31]),
    .Q(lane_1[31])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _592_ (
    .C(clk_2f),
    .D(_002_),
    .Q(valid_0)
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _593_ (
    .C(clk_2f),
    .D(_003_),
    .Q(valid_1)
  );
endmodule

(* top =  1  *)
(* src = "src/phy_tx.v:9" *)
module PHY_TX(data_out_0, data_out_1, data_in, valid_in, reset, clk_32f);
  (* src = "src/phy_tx.v:15" *)
  wire clk_2f;
  (* src = "src/phy_tx.v:12" *)
  input clk_32f;
  (* src = "src/phy_tx.v:15" *)
  wire clk_4f;
  (* src = "src/phy_tx.v:15" *)
  wire clk_f;
  (* src = "src/phy_tx.v:17" *)
  wire [7:0] data_8b_0;
  (* src = "src/phy_tx.v:17" *)
  wire [7:0] data_8b_1;
  (* src = "src/phy_tx.v:11" *)
  input [31:0] data_in;
  (* src = "src/phy_tx.v:10" *)
  output data_out_0;
  (* src = "src/phy_tx.v:10" *)
  output data_out_1;
  (* src = "src/phy_tx.v:16" *)
  wire [31:0] lane_0;
  (* src = "src/phy_tx.v:16" *)
  wire [31:0] lane_1;
  (* src = "src/phy_tx.v:12" *)
  input reset;
  (* src = "src/phy_tx.v:19" *)
  wire valid_0;
  (* src = "src/phy_tx.v:19" *)
  wire valid_1;
  (* src = "src/phy_tx.v:12" *)
  input valid_in;
  (* src = "src/phy_tx.v:18" *)
  wire valid_out_0;
  (* src = "src/phy_tx.v:18" *)
  wire valid_out_1;
  (* module_not_derived = 32'd1 *)
  (* src = "src/phy_tx.v:24" *)
  BYTE_STRIPING bte_strp (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_in(data_in),
    .lane_0(lane_0),
    .lane_1(lane_1),
    .valid_0(valid_0),
    .valid_1(valid_1),
    .valid_in(valid_in)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/phy_tx.v:22" *)
  clk_gen clock_gen (
    .clk_2f(clk_2f),
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/phy_tx.v:26" *)
  m32_8 conv_0 (
    .clk_4f(clk_4f),
    .data_32_8(data_8b_0),
    .data_strp(lane_0),
    .reset(reset),
    .valid_32_8(valid_out_0),
    .valid_strp(valid_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/phy_tx.v:27" *)
  m32_8 conv_1 (
    .clk_4f(clk_4f),
    .data_32_8(data_8b_1),
    .data_strp(lane_1),
    .reset(reset),
    .valid_32_8(valid_out_1),
    .valid_strp(valid_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/phy_tx.v:30" *)
  paralelo_serial parial_0 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(data_8b_0),
    .data_out(data_out_0),
    .reset(reset),
    .valid_in(valid_out_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/phy_tx.v:31" *)
  paralelo_serial parial_1 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(data_8b_1),
    .data_out(data_out_1),
    .reset(reset),
    .valid_in(valid_out_1)
  );
endmodule

(* src = "lib/clk_gen.v:8" *)
module clk_gen(clk_f, clk_2f, clk_4f, clk_32f, reset);
  (* src = "lib/clk_gen.v:9" *)
  output clk_2f;
  (* src = "lib/clk_gen.v:11" *)
  input clk_32f;
  (* src = "lib/clk_gen.v:10" *)
  output clk_4f;
  (* src = "lib/clk_gen.v:8" *)
  output clk_f;
  (* src = "lib/clk_gen.v:14" *)
  wire q2;
  (* src = "lib/clk_gen.v:12" *)
  input reset;
  assign clk_2f = 1'h0;
  assign clk_4f = 1'h0;
  assign clk_f = 1'h0;
  assign q2 = 1'h0;
endmodule

(* src = "lib/m32_8.v:7" *)
module m32_8(data_32_8, valid_32_8, data_strp, valid_strp, reset, clk_4f);
  (* src = "lib/m32_8.v:16" *)
  wire [7:0] _000_;
  (* src = "lib/m32_8.v:16" *)
  wire [1:0] _001_;
  (* src = "lib/m32_8.v:16" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "lib/m32_8.v:12" *)
  input clk_4f;
  (* src = "lib/m32_8.v:7" *)
  output [7:0] data_32_8;
  (* src = "lib/m32_8.v:9" *)
  input [31:0] data_strp;
  (* src = "lib/m32_8.v:11" *)
  input reset;
  (* init = 2'h0 *)
  (* src = "lib/m32_8.v:14" *)
  wire [1:0] selector;
  (* src = "lib/m32_8.v:8" *)
  output valid_32_8;
  (* src = "lib/m32_8.v:10" *)
  input valid_strp;
  NOT _068_ (
    .A(selector[0]),
    .Y(_030_)
  );
  NOT _069_ (
    .A(selector[1]),
    .Y(_031_)
  );
  NAND _070_ (
    .A(valid_strp),
    .B(reset),
    .Y(_032_)
  );
  NOT _071_ (
    .A(_032_),
    .Y(_002_)
  );
  NOR _072_ (
    .A(selector[0]),
    .B(_031_),
    .Y(_033_)
  );
  NAND _073_ (
    .A(data_strp[8]),
    .B(_033_),
    .Y(_034_)
  );
  NOR _074_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_035_)
  );
  NAND _075_ (
    .A(data_strp[24]),
    .B(_035_),
    .Y(_036_)
  );
  NAND _076_ (
    .A(_034_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _077_ (
    .A(_030_),
    .B(selector[1]),
    .Y(_038_)
  );
  NAND _078_ (
    .A(data_strp[16]),
    .B(_038_),
    .Y(_039_)
  );
  NOR _079_ (
    .A(_030_),
    .B(_031_),
    .Y(_040_)
  );
  NAND _080_ (
    .A(data_strp[0]),
    .B(_040_),
    .Y(_041_)
  );
  NAND _081_ (
    .A(_039_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _082_ (
    .A(_037_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _083_ (
    .A(_032_),
    .B(_043_),
    .Y(_000_[0])
  );
  NAND _084_ (
    .A(data_strp[1]),
    .B(_040_),
    .Y(_044_)
  );
  NAND _085_ (
    .A(data_strp[25]),
    .B(_035_),
    .Y(_045_)
  );
  NAND _086_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _087_ (
    .A(data_strp[9]),
    .B(_033_),
    .Y(_047_)
  );
  NAND _088_ (
    .A(data_strp[17]),
    .B(_038_),
    .Y(_048_)
  );
  NAND _089_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _090_ (
    .A(_046_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _091_ (
    .A(_032_),
    .B(_050_),
    .Y(_000_[1])
  );
  NAND _092_ (
    .A(data_strp[2]),
    .B(_040_),
    .Y(_051_)
  );
  NAND _093_ (
    .A(data_strp[26]),
    .B(_035_),
    .Y(_052_)
  );
  NAND _094_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _095_ (
    .A(data_strp[10]),
    .B(_033_),
    .Y(_054_)
  );
  NAND _096_ (
    .A(data_strp[18]),
    .B(_038_),
    .Y(_055_)
  );
  NAND _097_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _098_ (
    .A(_053_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _099_ (
    .A(_032_),
    .B(_057_),
    .Y(_000_[2])
  );
  NAND _100_ (
    .A(data_strp[3]),
    .B(_040_),
    .Y(_058_)
  );
  NAND _101_ (
    .A(data_strp[27]),
    .B(_035_),
    .Y(_059_)
  );
  NAND _102_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _103_ (
    .A(data_strp[11]),
    .B(_033_),
    .Y(_061_)
  );
  NAND _104_ (
    .A(data_strp[19]),
    .B(_038_),
    .Y(_062_)
  );
  NAND _105_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _106_ (
    .A(_060_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _107_ (
    .A(_032_),
    .B(_064_),
    .Y(_000_[3])
  );
  NAND _108_ (
    .A(data_strp[4]),
    .B(_040_),
    .Y(_065_)
  );
  NAND _109_ (
    .A(data_strp[28]),
    .B(_035_),
    .Y(_066_)
  );
  NAND _110_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _111_ (
    .A(data_strp[12]),
    .B(_033_),
    .Y(_003_)
  );
  NAND _112_ (
    .A(data_strp[20]),
    .B(_038_),
    .Y(_004_)
  );
  NAND _113_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  NOR _114_ (
    .A(_067_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _115_ (
    .A(_032_),
    .B(_006_),
    .Y(_000_[4])
  );
  NAND _116_ (
    .A(data_strp[5]),
    .B(_040_),
    .Y(_007_)
  );
  NAND _117_ (
    .A(data_strp[29]),
    .B(_035_),
    .Y(_008_)
  );
  NAND _118_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _119_ (
    .A(data_strp[13]),
    .B(_033_),
    .Y(_010_)
  );
  NAND _120_ (
    .A(data_strp[21]),
    .B(_038_),
    .Y(_011_)
  );
  NAND _121_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _122_ (
    .A(_009_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _123_ (
    .A(_032_),
    .B(_013_),
    .Y(_000_[5])
  );
  NAND _124_ (
    .A(data_strp[6]),
    .B(_040_),
    .Y(_014_)
  );
  NAND _125_ (
    .A(data_strp[30]),
    .B(_035_),
    .Y(_015_)
  );
  NAND _126_ (
    .A(_014_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _127_ (
    .A(data_strp[14]),
    .B(_033_),
    .Y(_017_)
  );
  NAND _128_ (
    .A(data_strp[22]),
    .B(_038_),
    .Y(_018_)
  );
  NAND _129_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _130_ (
    .A(_016_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _131_ (
    .A(_032_),
    .B(_020_),
    .Y(_000_[6])
  );
  NAND _132_ (
    .A(data_strp[7]),
    .B(_040_),
    .Y(_021_)
  );
  NAND _133_ (
    .A(data_strp[31]),
    .B(_035_),
    .Y(_022_)
  );
  NAND _134_ (
    .A(_021_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _135_ (
    .A(data_strp[15]),
    .B(_033_),
    .Y(_024_)
  );
  NAND _136_ (
    .A(data_strp[23]),
    .B(_038_),
    .Y(_025_)
  );
  NAND _137_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _138_ (
    .A(_023_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _139_ (
    .A(_032_),
    .B(_027_),
    .Y(_000_[7])
  );
  NOR _140_ (
    .A(selector[0]),
    .B(_032_),
    .Y(_001_[0])
  );
  NOR _141_ (
    .A(_032_),
    .B(_040_),
    .Y(_028_)
  );
  NOT _142_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR _143_ (
    .A(_035_),
    .B(_029_),
    .Y(_001_[1])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _144_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(selector[0])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _145_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(selector[1])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _146_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_32_8[0])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _147_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_32_8[1])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _148_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_32_8[2])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _149_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_32_8[3])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _150_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_32_8[4])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _151_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_32_8[5])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _152_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_32_8[6])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _153_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_32_8[7])
  );
  (* src = "lib/m32_8.v:16" *)
  DFF _154_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_32_8)
  );
endmodule

(* src = "lib/paralelo_serial.v:1" *)
module paralelo_serial(clk_4f, clk_32f, data_in, valid_in, reset, data_out);
  (* src = "lib/paralelo_serial.v:11" *)
  wire [7:0] _000_;
  (* src = "lib/paralelo_serial.v:19" *)
  wire _001_;
  (* src = "lib/paralelo_serial.v:19" *)
  wire [2:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* src = "lib/paralelo_serial.v:2" *)
  input clk_32f;
  (* src = "lib/paralelo_serial.v:1" *)
  input clk_4f;
  (* src = "lib/paralelo_serial.v:9" *)
  wire [7:0] data2send;
  (* src = "lib/paralelo_serial.v:3" *)
  input [7:0] data_in;
  (* src = "lib/paralelo_serial.v:6" *)
  output data_out;
  (* src = "lib/paralelo_serial.v:5" *)
  input reset;
  (* src = "lib/paralelo_serial.v:8" *)
  wire [2:0] selector;
  (* src = "lib/paralelo_serial.v:4" *)
  input valid_in;
  NOT _046_ (
    .A(data_in[2]),
    .Y(_003_)
  );
  NOT _047_ (
    .A(data_in[3]),
    .Y(_004_)
  );
  NOT _048_ (
    .A(data_in[4]),
    .Y(_005_)
  );
  NOT _049_ (
    .A(data_in[5]),
    .Y(_006_)
  );
  NOT _050_ (
    .A(data_in[7]),
    .Y(_007_)
  );
  NOT _051_ (
    .A(reset),
    .Y(_008_)
  );
  NOT _052_ (
    .A(data2send[6]),
    .Y(_009_)
  );
  NOT _053_ (
    .A(data2send[7]),
    .Y(_010_)
  );
  NOT _054_ (
    .A(selector[0]),
    .Y(_011_)
  );
  NOT _055_ (
    .A(selector[1]),
    .Y(_012_)
  );
  NOT _056_ (
    .A(selector[2]),
    .Y(_013_)
  );
  NAND _057_ (
    .A(data_in[1]),
    .B(valid_in),
    .Y(_014_)
  );
  NOT _058_ (
    .A(_014_),
    .Y(_000_[1])
  );
  NAND _059_ (
    .A(valid_in),
    .B(_003_),
    .Y(_000_[2])
  );
  NAND _060_ (
    .A(valid_in),
    .B(_004_),
    .Y(_000_[3])
  );
  NAND _061_ (
    .A(valid_in),
    .B(_005_),
    .Y(_000_[4])
  );
  NAND _062_ (
    .A(valid_in),
    .B(_006_),
    .Y(_000_[5])
  );
  NAND _063_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_015_)
  );
  NOT _064_ (
    .A(_015_),
    .Y(_000_[6])
  );
  NAND _065_ (
    .A(valid_in),
    .B(_007_),
    .Y(_000_[7])
  );
  NOR _066_ (
    .A(_008_),
    .B(selector[0]),
    .Y(_002_[0])
  );
  NAND _067_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_016_)
  );
  NOT _068_ (
    .A(_016_),
    .Y(_017_)
  );
  NOR _069_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_018_)
  );
  NOT _070_ (
    .A(_018_),
    .Y(_019_)
  );
  NAND _071_ (
    .A(reset),
    .B(_019_),
    .Y(_020_)
  );
  NOR _072_ (
    .A(_017_),
    .B(_020_),
    .Y(_002_[1])
  );
  NOR _073_ (
    .A(_013_),
    .B(_016_),
    .Y(_021_)
  );
  NAND _074_ (
    .A(_013_),
    .B(_016_),
    .Y(_022_)
  );
  NAND _075_ (
    .A(reset),
    .B(_022_),
    .Y(_023_)
  );
  NOR _076_ (
    .A(_021_),
    .B(_023_),
    .Y(_002_[2])
  );
  NOR _077_ (
    .A(data2send[1]),
    .B(_013_),
    .Y(_024_)
  );
  NOR _078_ (
    .A(data2send[5]),
    .B(selector[2]),
    .Y(_025_)
  );
  NOR _079_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _080_ (
    .A(_011_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _081_ (
    .A(data2send[0]),
    .B(selector[2]),
    .Y(_028_)
  );
  NAND _082_ (
    .A(data2send[4]),
    .B(_013_),
    .Y(_029_)
  );
  NAND _083_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _084_ (
    .A(selector[0]),
    .B(_030_),
    .Y(_031_)
  );
  NAND _085_ (
    .A(_027_),
    .B(_031_),
    .Y(_032_)
  );
  NAND _086_ (
    .A(selector[1]),
    .B(_032_),
    .Y(_033_)
  );
  NAND _087_ (
    .A(_010_),
    .B(_013_),
    .Y(_034_)
  );
  NOR _088_ (
    .A(data2send[3]),
    .B(_013_),
    .Y(_035_)
  );
  NAND _089_ (
    .A(_018_),
    .B(_034_),
    .Y(_036_)
  );
  NOR _090_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _091_ (
    .A(data2send[2]),
    .B(selector[2]),
    .Y(_038_)
  );
  NOT _092_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _093_ (
    .A(_009_),
    .B(selector[2]),
    .Y(_040_)
  );
  NOR _094_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _095_ (
    .A(selector[0]),
    .B(_012_),
    .Y(_042_)
  );
  NOR _096_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _097_ (
    .A(_037_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _098_ (
    .A(_033_),
    .B(_044_),
    .Y(_001_)
  );
  NAND _099_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_045_)
  );
  NOT _100_ (
    .A(_045_),
    .Y(_000_[0])
  );
  (* src = "lib/paralelo_serial.v:19" *)
  DFF _101_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(selector[0])
  );
  (* src = "lib/paralelo_serial.v:19" *)
  DFF _102_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(selector[1])
  );
  (* src = "lib/paralelo_serial.v:19" *)
  DFF _103_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(selector[2])
  );
  (* src = "lib/paralelo_serial.v:19" *)
  DFF _104_ (
    .C(clk_32f),
    .D(_001_),
    .Q(data_out)
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _105_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data2send[0])
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _106_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data2send[1])
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _107_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data2send[2])
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _108_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data2send[3])
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _109_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data2send[4])
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _110_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data2send[5])
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _111_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data2send[6])
  );
  (* src = "lib/paralelo_serial.v:11" *)
  DFF _112_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data2send[7])
  );
endmodule
