/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "lib/serial_paralelo.v:1" *)
module serial_paralelo_synth(data_in, clk_4f, clk_32f, valid_out, data_out);
  (* src = "lib/serial_paralelo.v:6" *)
  wire BC_counter;
  (* src = "lib/serial_paralelo.v:7" *)
  wire active;
  (* src = "lib/serial_paralelo.v:3" *)
  input clk_32f;
  (* src = "lib/serial_paralelo.v:2" *)
  input clk_4f;
  (* src = "lib/serial_paralelo.v:1" *)
  input data_in;
  (* src = "lib/serial_paralelo.v:5" *)
  output [7:0] data_out;
  (* src = "lib/serial_paralelo.v:9" *)
  wire [2:0] i;
  (* src = "lib/serial_paralelo.v:4" *)
  output valid_out;
  assign BC_counter = 1'h0;
  assign active = 1'h0;
  assign i = 3'h0;
endmodule
