/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "lib/serial_paralelo.v:1" *)
module serial_paralelo_synth(data_in, clk_4f, clk_32f, reset, valid_out, data_out);
  (* src = "lib/serial_paralelo.v:11" *)
  wire _000_;
  (* src = "lib/serial_paralelo.v:11" *)
  wire [2:0] _001_;
  (* src = "lib/serial_paralelo.v:11" *)
  wire [4:0] _002_;
  (* src = "lib/serial_paralelo.v:11" *)
  wire [7:0] _003_;
  (* src = "lib/serial_paralelo.v:11" *)
  wire [7:0] _004_;
  (* src = "lib/serial_paralelo.v:11" *)
  wire _005_;
  (* src = "lib/serial_paralelo.v:11" *)
  (* unused_bits = "7" *)
  wire [7:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  (* src = "lib/serial_paralelo.v:10" *)
  wire active;
  (* src = "lib/serial_paralelo.v:7" *)
  wire [2:0] bc_counter;
  (* src = "lib/serial_paralelo.v:3" *)
  input clk_32f;
  (* src = "lib/serial_paralelo.v:2" *)
  input clk_4f;
  (* src = "lib/serial_paralelo.v:9" *)
  wire [4:0] counter;
  (* src = "lib/serial_paralelo.v:8" *)
  wire [7:0] data2send;
  (* src = "lib/serial_paralelo.v:1" *)
  input data_in;
  (* src = "lib/serial_paralelo.v:6" *)
  output [7:0] data_out;
  (* src = "lib/serial_paralelo.v:4" *)
  input reset;
  (* src = "lib/serial_paralelo.v:5" *)
  output valid_out;
  (* src = "lib/serial_paralelo.v:8" *)
  (* unused_bits = "7" *)
  wire [7:0] wait_buffer;
  NOT _115_ (
    .A(counter[2]),
    .Y(_088_)
  );
  NOT _116_ (
    .A(counter[4]),
    .Y(_089_)
  );
  NOT _117_ (
    .A(bc_counter[2]),
    .Y(_090_)
  );
  NOT _118_ (
    .A(reset),
    .Y(_091_)
  );
  NOT _119_ (
    .A(data2send[2]),
    .Y(_092_)
  );
  NOT _120_ (
    .A(bc_counter[0]),
    .Y(_093_)
  );
  NOT _121_ (
    .A(bc_counter[1]),
    .Y(_094_)
  );
  NOR _122_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_095_)
  );
  NAND _123_ (
    .A(_088_),
    .B(counter[3]),
    .Y(_096_)
  );
  NOR _124_ (
    .A(counter[4]),
    .B(_096_),
    .Y(_097_)
  );
  NAND _125_ (
    .A(_089_),
    .B(counter[3]),
    .Y(_098_)
  );
  NAND _126_ (
    .A(_088_),
    .B(_095_),
    .Y(_099_)
  );
  NOR _127_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _128_ (
    .A(_095_),
    .B(_097_),
    .Y(_101_)
  );
  NOR _129_ (
    .A(_091_),
    .B(_100_),
    .Y(_102_)
  );
  NOT _130_ (
    .A(_102_),
    .Y(_103_)
  );
  NAND _131_ (
    .A(data2send[0]),
    .B(_102_),
    .Y(_104_)
  );
  NOR _132_ (
    .A(_091_),
    .B(_101_),
    .Y(_105_)
  );
  NAND _133_ (
    .A(reset),
    .B(_100_),
    .Y(_106_)
  );
  NAND _134_ (
    .A(data_in),
    .B(_105_),
    .Y(_107_)
  );
  NAND _135_ (
    .A(_104_),
    .B(_107_),
    .Y(_003_[0])
  );
  NAND _136_ (
    .A(data2send[1]),
    .B(_102_),
    .Y(_108_)
  );
  NAND _137_ (
    .A(wait_buffer[0]),
    .B(_105_),
    .Y(_109_)
  );
  NAND _138_ (
    .A(_108_),
    .B(_109_),
    .Y(_003_[1])
  );
  NAND _139_ (
    .A(data2send[2]),
    .B(_102_),
    .Y(_110_)
  );
  NAND _140_ (
    .A(wait_buffer[1]),
    .B(_105_),
    .Y(_111_)
  );
  NAND _141_ (
    .A(_110_),
    .B(_111_),
    .Y(_003_[2])
  );
  NAND _142_ (
    .A(data2send[3]),
    .B(_102_),
    .Y(_112_)
  );
  NAND _143_ (
    .A(wait_buffer[2]),
    .B(_105_),
    .Y(_113_)
  );
  NAND _144_ (
    .A(_112_),
    .B(_113_),
    .Y(_003_[3])
  );
  NAND _145_ (
    .A(data2send[4]),
    .B(_102_),
    .Y(_114_)
  );
  NAND _146_ (
    .A(wait_buffer[3]),
    .B(_105_),
    .Y(_007_)
  );
  NAND _147_ (
    .A(_114_),
    .B(_007_),
    .Y(_003_[4])
  );
  NAND _148_ (
    .A(data2send[5]),
    .B(_102_),
    .Y(_008_)
  );
  NAND _149_ (
    .A(wait_buffer[4]),
    .B(_105_),
    .Y(_009_)
  );
  NAND _150_ (
    .A(_008_),
    .B(_009_),
    .Y(_003_[5])
  );
  NAND _151_ (
    .A(data2send[6]),
    .B(_102_),
    .Y(_010_)
  );
  NAND _152_ (
    .A(wait_buffer[5]),
    .B(_105_),
    .Y(_011_)
  );
  NAND _153_ (
    .A(_010_),
    .B(_011_),
    .Y(_003_[6])
  );
  NAND _154_ (
    .A(data2send[7]),
    .B(_102_),
    .Y(_012_)
  );
  NAND _155_ (
    .A(wait_buffer[6]),
    .B(_105_),
    .Y(_013_)
  );
  NAND _156_ (
    .A(_012_),
    .B(_013_),
    .Y(_003_[7])
  );
  NOR _157_ (
    .A(_093_),
    .B(_094_),
    .Y(_014_)
  );
  NAND _158_ (
    .A(bc_counter[0]),
    .B(bc_counter[1]),
    .Y(_015_)
  );
  NOR _159_ (
    .A(bc_counter[2]),
    .B(_014_),
    .Y(_016_)
  );
  NAND _160_ (
    .A(_090_),
    .B(_015_),
    .Y(_017_)
  );
  NAND _161_ (
    .A(active),
    .B(_017_),
    .Y(_018_)
  );
  NOT _162_ (
    .A(_018_),
    .Y(_019_)
  );
  NOR _163_ (
    .A(_106_),
    .B(_018_),
    .Y(_020_)
  );
  NAND _164_ (
    .A(_105_),
    .B(_019_),
    .Y(_021_)
  );
  NAND _165_ (
    .A(data_out[0]),
    .B(_021_),
    .Y(_022_)
  );
  NAND _166_ (
    .A(data2send[3]),
    .B(data2send[4]),
    .Y(_023_)
  );
  NAND _167_ (
    .A(data2send[5]),
    .B(data2send[7]),
    .Y(_024_)
  );
  NOR _168_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NOT _169_ (
    .A(_025_),
    .Y(_026_)
  );
  NOR _170_ (
    .A(data2send[0]),
    .B(data2send[1]),
    .Y(_027_)
  );
  NOR _171_ (
    .A(data2send[6]),
    .B(_092_),
    .Y(_028_)
  );
  NAND _172_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _173_ (
    .A(_026_),
    .B(_029_),
    .Y(_030_)
  );
  NOT _174_ (
    .A(_030_),
    .Y(_031_)
  );
  NAND _175_ (
    .A(_020_),
    .B(_031_),
    .Y(_032_)
  );
  NOT _176_ (
    .A(_032_),
    .Y(_033_)
  );
  NAND _177_ (
    .A(data2send[0]),
    .B(_033_),
    .Y(_034_)
  );
  NAND _178_ (
    .A(_022_),
    .B(_034_),
    .Y(_004_[0])
  );
  NOR _179_ (
    .A(data_out[1]),
    .B(_020_),
    .Y(_035_)
  );
  NOR _180_ (
    .A(data2send[1]),
    .B(_021_),
    .Y(_036_)
  );
  NOR _181_ (
    .A(_035_),
    .B(_036_),
    .Y(_004_[1])
  );
  NAND _182_ (
    .A(data2send[2]),
    .B(_020_),
    .Y(_037_)
  );
  NAND _183_ (
    .A(data_out[2]),
    .B(_021_),
    .Y(_038_)
  );
  NAND _184_ (
    .A(_037_),
    .B(_038_),
    .Y(_004_[2])
  );
  NOR _185_ (
    .A(data_out[3]),
    .B(_020_),
    .Y(_039_)
  );
  NOR _186_ (
    .A(data2send[3]),
    .B(_032_),
    .Y(_040_)
  );
  NOR _187_ (
    .A(_039_),
    .B(_040_),
    .Y(_004_[3])
  );
  NOR _188_ (
    .A(data_out[4]),
    .B(_020_),
    .Y(_041_)
  );
  NOR _189_ (
    .A(data2send[4]),
    .B(_032_),
    .Y(_042_)
  );
  NOR _190_ (
    .A(_041_),
    .B(_042_),
    .Y(_004_[4])
  );
  NOR _191_ (
    .A(data_out[5]),
    .B(_020_),
    .Y(_043_)
  );
  NOR _192_ (
    .A(data2send[5]),
    .B(_032_),
    .Y(_044_)
  );
  NOR _193_ (
    .A(_043_),
    .B(_044_),
    .Y(_004_[5])
  );
  NOR _194_ (
    .A(data_out[6]),
    .B(_020_),
    .Y(_045_)
  );
  NOR _195_ (
    .A(data2send[6]),
    .B(_021_),
    .Y(_046_)
  );
  NOR _196_ (
    .A(_045_),
    .B(_046_),
    .Y(_004_[6])
  );
  NAND _197_ (
    .A(data2send[7]),
    .B(_020_),
    .Y(_047_)
  );
  NAND _198_ (
    .A(data_out[7]),
    .B(_021_),
    .Y(_048_)
  );
  NAND _199_ (
    .A(_047_),
    .B(_048_),
    .Y(_004_[7])
  );
  NAND _200_ (
    .A(valid_out),
    .B(_021_),
    .Y(_049_)
  );
  NAND _201_ (
    .A(_032_),
    .B(_049_),
    .Y(_005_)
  );
  NOR _202_ (
    .A(_093_),
    .B(_101_),
    .Y(_050_)
  );
  NAND _203_ (
    .A(_016_),
    .B(_030_),
    .Y(_051_)
  );
  NOR _204_ (
    .A(active),
    .B(_015_),
    .Y(_052_)
  );
  NAND _205_ (
    .A(_090_),
    .B(_052_),
    .Y(_053_)
  );
  NOT _206_ (
    .A(_053_),
    .Y(_054_)
  );
  NAND _207_ (
    .A(_051_),
    .B(_053_),
    .Y(_055_)
  );
  NAND _208_ (
    .A(_050_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _209_ (
    .A(_101_),
    .B(_051_),
    .Y(_057_)
  );
  NOR _210_ (
    .A(bc_counter[0]),
    .B(_057_),
    .Y(_058_)
  );
  NAND _211_ (
    .A(reset),
    .B(_056_),
    .Y(_059_)
  );
  NOR _212_ (
    .A(_058_),
    .B(_059_),
    .Y(_001_[0])
  );
  NOR _213_ (
    .A(bc_counter[1]),
    .B(_050_),
    .Y(_060_)
  );
  NOR _214_ (
    .A(_051_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _215_ (
    .A(_101_),
    .B(_053_),
    .Y(_062_)
  );
  NAND _216_ (
    .A(_100_),
    .B(_054_),
    .Y(_063_)
  );
  NAND _217_ (
    .A(bc_counter[1]),
    .B(_063_),
    .Y(_064_)
  );
  NOR _218_ (
    .A(_057_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _219_ (
    .A(_061_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _220_ (
    .A(_091_),
    .B(_066_),
    .Y(_001_[1])
  );
  NOR _221_ (
    .A(bc_counter[2]),
    .B(_062_),
    .Y(_067_)
  );
  NOR _222_ (
    .A(_091_),
    .B(_067_),
    .Y(_001_[2])
  );
  NOR _223_ (
    .A(active),
    .B(_062_),
    .Y(_068_)
  );
  NOR _224_ (
    .A(_091_),
    .B(_068_),
    .Y(_000_)
  );
  NOR _225_ (
    .A(counter[0]),
    .B(_091_),
    .Y(_002_[0])
  );
  NAND _226_ (
    .A(counter[0]),
    .B(counter[1]),
    .Y(_069_)
  );
  NAND _227_ (
    .A(reset),
    .B(_069_),
    .Y(_070_)
  );
  NOR _228_ (
    .A(_095_),
    .B(_070_),
    .Y(_002_[1])
  );
  NOR _229_ (
    .A(_088_),
    .B(_069_),
    .Y(_071_)
  );
  NAND _230_ (
    .A(_088_),
    .B(_069_),
    .Y(_072_)
  );
  NAND _231_ (
    .A(reset),
    .B(_072_),
    .Y(_073_)
  );
  NOR _232_ (
    .A(_071_),
    .B(_073_),
    .Y(_002_[2])
  );
  NAND _233_ (
    .A(counter[3]),
    .B(_071_),
    .Y(_074_)
  );
  NOR _234_ (
    .A(counter[3]),
    .B(_071_),
    .Y(_075_)
  );
  NOT _235_ (
    .A(_075_),
    .Y(_076_)
  );
  NAND _236_ (
    .A(_074_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _237_ (
    .A(_103_),
    .B(_077_),
    .Y(_002_[3])
  );
  NOR _238_ (
    .A(_089_),
    .B(_074_),
    .Y(_078_)
  );
  NAND _239_ (
    .A(_089_),
    .B(_074_),
    .Y(_079_)
  );
  NAND _240_ (
    .A(reset),
    .B(_079_),
    .Y(_080_)
  );
  NOR _241_ (
    .A(_078_),
    .B(_080_),
    .Y(_002_[4])
  );
  NAND _242_ (
    .A(reset),
    .B(data_in),
    .Y(_081_)
  );
  NOT _243_ (
    .A(_081_),
    .Y(_006_[0])
  );
  NAND _244_ (
    .A(reset),
    .B(wait_buffer[0]),
    .Y(_082_)
  );
  NOT _245_ (
    .A(_082_),
    .Y(_006_[1])
  );
  NAND _246_ (
    .A(reset),
    .B(wait_buffer[1]),
    .Y(_083_)
  );
  NOT _247_ (
    .A(_083_),
    .Y(_006_[2])
  );
  NAND _248_ (
    .A(reset),
    .B(wait_buffer[2]),
    .Y(_084_)
  );
  NOT _249_ (
    .A(_084_),
    .Y(_006_[3])
  );
  NAND _250_ (
    .A(reset),
    .B(wait_buffer[3]),
    .Y(_085_)
  );
  NOT _251_ (
    .A(_085_),
    .Y(_006_[4])
  );
  NAND _252_ (
    .A(reset),
    .B(wait_buffer[4]),
    .Y(_086_)
  );
  NOT _253_ (
    .A(_086_),
    .Y(_006_[5])
  );
  NAND _254_ (
    .A(reset),
    .B(wait_buffer[5]),
    .Y(_087_)
  );
  NOT _255_ (
    .A(_087_),
    .Y(_006_[6])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _256_ (
    .C(clk_32f),
    .D(_005_),
    .Q(valid_out)
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _257_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(bc_counter[0])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _258_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(bc_counter[1])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _259_ (
    .C(clk_32f),
    .D(_001_[2]),
    .Q(bc_counter[2])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _260_ (
    .C(clk_32f),
    .D(_000_),
    .Q(active)
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _261_ (
    .C(clk_32f),
    .D(_006_[0]),
    .Q(wait_buffer[0])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _262_ (
    .C(clk_32f),
    .D(_006_[1]),
    .Q(wait_buffer[1])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _263_ (
    .C(clk_32f),
    .D(_006_[2]),
    .Q(wait_buffer[2])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _264_ (
    .C(clk_32f),
    .D(_006_[3]),
    .Q(wait_buffer[3])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _265_ (
    .C(clk_32f),
    .D(_006_[4]),
    .Q(wait_buffer[4])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _266_ (
    .C(clk_32f),
    .D(_006_[5]),
    .Q(wait_buffer[5])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _267_ (
    .C(clk_32f),
    .D(_006_[6]),
    .Q(wait_buffer[6])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _268_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(counter[0])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _269_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(counter[1])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _270_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(counter[2])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _271_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(counter[3])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _272_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(counter[4])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _273_ (
    .C(clk_32f),
    .D(_004_[0]),
    .Q(data_out[0])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _274_ (
    .C(clk_32f),
    .D(_004_[1]),
    .Q(data_out[1])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _275_ (
    .C(clk_32f),
    .D(_004_[2]),
    .Q(data_out[2])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _276_ (
    .C(clk_32f),
    .D(_004_[3]),
    .Q(data_out[3])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _277_ (
    .C(clk_32f),
    .D(_004_[4]),
    .Q(data_out[4])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _278_ (
    .C(clk_32f),
    .D(_004_[5]),
    .Q(data_out[5])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _279_ (
    .C(clk_32f),
    .D(_004_[6]),
    .Q(data_out[6])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _280_ (
    .C(clk_32f),
    .D(_004_[7]),
    .Q(data_out[7])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _281_ (
    .C(clk_32f),
    .D(_003_[0]),
    .Q(data2send[0])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _282_ (
    .C(clk_32f),
    .D(_003_[1]),
    .Q(data2send[1])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _283_ (
    .C(clk_32f),
    .D(_003_[2]),
    .Q(data2send[2])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _284_ (
    .C(clk_32f),
    .D(_003_[3]),
    .Q(data2send[3])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _285_ (
    .C(clk_32f),
    .D(_003_[4]),
    .Q(data2send[4])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _286_ (
    .C(clk_32f),
    .D(_003_[5]),
    .Q(data2send[5])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _287_ (
    .C(clk_32f),
    .D(_003_[6]),
    .Q(data2send[6])
  );
  (* src = "lib/serial_paralelo.v:11" *)
  DFF _288_ (
    .C(clk_32f),
    .D(_003_[7]),
    .Q(data2send[7])
  );
endmodule
