/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "lib/byte_striping.v:7" *)
module STRIPING_SYNTH(lane_0, lane_1, valid_0, valid_1, data_in, valid_in, clk_2f, clk_f);
  (* src = "lib/byte_striping.v:14" *)
  wire [31:0] _000_;
  (* src = "lib/byte_striping.v:14" *)
  wire [31:0] _001_;
  (* src = "lib/byte_striping.v:14" *)
  wire _002_;
  (* src = "lib/byte_striping.v:14" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  (* src = "lib/byte_striping.v:12" *)
  input clk_2f;
  (* src = "lib/byte_striping.v:12" *)
  input clk_f;
  (* src = "lib/byte_striping.v:10" *)
  input [31:0] data_in;
  (* src = "lib/byte_striping.v:8" *)
  output [31:0] lane_0;
  (* src = "lib/byte_striping.v:8" *)
  output [31:0] lane_1;
  (* src = "lib/byte_striping.v:9" *)
  output valid_0;
  (* src = "lib/byte_striping.v:9" *)
  output valid_1;
  (* src = "lib/byte_striping.v:11" *)
  input valid_in;
  NOT _233_ (
    .A(clk_f),
    .Y(_004_)
  );
  NOR _234_ (
    .A(lane_1[3]),
    .B(clk_f),
    .Y(_005_)
  );
  NAND _235_ (
    .A(valid_in),
    .B(data_in[3]),
    .Y(_006_)
  );
  NAND _236_ (
    .A(clk_f),
    .B(_006_),
    .Y(_007_)
  );
  NOT _237_ (
    .A(_007_),
    .Y(_008_)
  );
  NOR _238_ (
    .A(_005_),
    .B(_008_),
    .Y(_001_[3])
  );
  NOR _239_ (
    .A(clk_f),
    .B(lane_1[4]),
    .Y(_009_)
  );
  NAND _240_ (
    .A(valid_in),
    .B(data_in[4]),
    .Y(_010_)
  );
  NAND _241_ (
    .A(clk_f),
    .B(_010_),
    .Y(_011_)
  );
  NOT _242_ (
    .A(_011_),
    .Y(_012_)
  );
  NOR _243_ (
    .A(_009_),
    .B(_012_),
    .Y(_001_[4])
  );
  NOR _244_ (
    .A(clk_f),
    .B(lane_1[5]),
    .Y(_013_)
  );
  NAND _245_ (
    .A(valid_in),
    .B(data_in[5]),
    .Y(_014_)
  );
  NAND _246_ (
    .A(clk_f),
    .B(_014_),
    .Y(_015_)
  );
  NOT _247_ (
    .A(_015_),
    .Y(_016_)
  );
  NOR _248_ (
    .A(_013_),
    .B(_016_),
    .Y(_001_[5])
  );
  NOR _249_ (
    .A(clk_f),
    .B(lane_1[6]),
    .Y(_017_)
  );
  NAND _250_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_018_)
  );
  NAND _251_ (
    .A(clk_f),
    .B(_018_),
    .Y(_019_)
  );
  NOT _252_ (
    .A(_019_),
    .Y(_020_)
  );
  NOR _253_ (
    .A(_017_),
    .B(_020_),
    .Y(_001_[6])
  );
  NOR _254_ (
    .A(clk_f),
    .B(lane_1[7]),
    .Y(_021_)
  );
  NAND _255_ (
    .A(valid_in),
    .B(data_in[7]),
    .Y(_022_)
  );
  NAND _256_ (
    .A(clk_f),
    .B(_022_),
    .Y(_023_)
  );
  NOT _257_ (
    .A(_023_),
    .Y(_024_)
  );
  NOR _258_ (
    .A(_021_),
    .B(_024_),
    .Y(_001_[7])
  );
  NOR _259_ (
    .A(clk_f),
    .B(lane_1[8]),
    .Y(_025_)
  );
  NAND _260_ (
    .A(valid_in),
    .B(data_in[8]),
    .Y(_026_)
  );
  NAND _261_ (
    .A(clk_f),
    .B(_026_),
    .Y(_027_)
  );
  NOT _262_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _263_ (
    .A(_025_),
    .B(_028_),
    .Y(_001_[8])
  );
  NOR _264_ (
    .A(clk_f),
    .B(lane_1[9]),
    .Y(_029_)
  );
  NAND _265_ (
    .A(valid_in),
    .B(data_in[9]),
    .Y(_030_)
  );
  NAND _266_ (
    .A(clk_f),
    .B(_030_),
    .Y(_031_)
  );
  NOT _267_ (
    .A(_031_),
    .Y(_032_)
  );
  NOR _268_ (
    .A(_029_),
    .B(_032_),
    .Y(_001_[9])
  );
  NOR _269_ (
    .A(clk_f),
    .B(lane_1[10]),
    .Y(_033_)
  );
  NAND _270_ (
    .A(valid_in),
    .B(data_in[10]),
    .Y(_034_)
  );
  NAND _271_ (
    .A(clk_f),
    .B(_034_),
    .Y(_035_)
  );
  NOT _272_ (
    .A(_035_),
    .Y(_036_)
  );
  NOR _273_ (
    .A(_033_),
    .B(_036_),
    .Y(_001_[10])
  );
  NOR _274_ (
    .A(clk_f),
    .B(lane_1[11]),
    .Y(_037_)
  );
  NAND _275_ (
    .A(valid_in),
    .B(data_in[11]),
    .Y(_038_)
  );
  NAND _276_ (
    .A(clk_f),
    .B(_038_),
    .Y(_039_)
  );
  NOT _277_ (
    .A(_039_),
    .Y(_040_)
  );
  NOR _278_ (
    .A(_037_),
    .B(_040_),
    .Y(_001_[11])
  );
  NOR _279_ (
    .A(clk_f),
    .B(lane_1[12]),
    .Y(_041_)
  );
  NAND _280_ (
    .A(valid_in),
    .B(data_in[12]),
    .Y(_042_)
  );
  NAND _281_ (
    .A(clk_f),
    .B(_042_),
    .Y(_043_)
  );
  NOT _282_ (
    .A(_043_),
    .Y(_044_)
  );
  NOR _283_ (
    .A(_041_),
    .B(_044_),
    .Y(_001_[12])
  );
  NOR _284_ (
    .A(clk_f),
    .B(lane_1[13]),
    .Y(_045_)
  );
  NAND _285_ (
    .A(valid_in),
    .B(data_in[13]),
    .Y(_046_)
  );
  NAND _286_ (
    .A(clk_f),
    .B(_046_),
    .Y(_047_)
  );
  NOT _287_ (
    .A(_047_),
    .Y(_048_)
  );
  NOR _288_ (
    .A(_045_),
    .B(_048_),
    .Y(_001_[13])
  );
  NOR _289_ (
    .A(clk_f),
    .B(lane_1[14]),
    .Y(_049_)
  );
  NAND _290_ (
    .A(valid_in),
    .B(data_in[14]),
    .Y(_050_)
  );
  NAND _291_ (
    .A(clk_f),
    .B(_050_),
    .Y(_051_)
  );
  NOT _292_ (
    .A(_051_),
    .Y(_052_)
  );
  NOR _293_ (
    .A(_049_),
    .B(_052_),
    .Y(_001_[14])
  );
  NOR _294_ (
    .A(clk_f),
    .B(lane_1[15]),
    .Y(_053_)
  );
  NAND _295_ (
    .A(valid_in),
    .B(data_in[15]),
    .Y(_054_)
  );
  NAND _296_ (
    .A(clk_f),
    .B(_054_),
    .Y(_055_)
  );
  NOT _297_ (
    .A(_055_),
    .Y(_056_)
  );
  NOR _298_ (
    .A(_053_),
    .B(_056_),
    .Y(_001_[15])
  );
  NOR _299_ (
    .A(clk_f),
    .B(lane_1[16]),
    .Y(_057_)
  );
  NAND _300_ (
    .A(valid_in),
    .B(data_in[16]),
    .Y(_058_)
  );
  NAND _301_ (
    .A(clk_f),
    .B(_058_),
    .Y(_059_)
  );
  NOT _302_ (
    .A(_059_),
    .Y(_060_)
  );
  NOR _303_ (
    .A(_057_),
    .B(_060_),
    .Y(_001_[16])
  );
  NOR _304_ (
    .A(clk_f),
    .B(lane_1[17]),
    .Y(_061_)
  );
  NAND _305_ (
    .A(valid_in),
    .B(data_in[17]),
    .Y(_062_)
  );
  NAND _306_ (
    .A(clk_f),
    .B(_062_),
    .Y(_063_)
  );
  NOT _307_ (
    .A(_063_),
    .Y(_064_)
  );
  NOR _308_ (
    .A(_061_),
    .B(_064_),
    .Y(_001_[17])
  );
  NOR _309_ (
    .A(clk_f),
    .B(lane_1[18]),
    .Y(_065_)
  );
  NAND _310_ (
    .A(valid_in),
    .B(data_in[18]),
    .Y(_066_)
  );
  NAND _311_ (
    .A(clk_f),
    .B(_066_),
    .Y(_067_)
  );
  NOT _312_ (
    .A(_067_),
    .Y(_068_)
  );
  NOR _313_ (
    .A(_065_),
    .B(_068_),
    .Y(_001_[18])
  );
  NOR _314_ (
    .A(clk_f),
    .B(lane_1[19]),
    .Y(_069_)
  );
  NAND _315_ (
    .A(valid_in),
    .B(data_in[19]),
    .Y(_070_)
  );
  NAND _316_ (
    .A(clk_f),
    .B(_070_),
    .Y(_071_)
  );
  NOT _317_ (
    .A(_071_),
    .Y(_072_)
  );
  NOR _318_ (
    .A(_069_),
    .B(_072_),
    .Y(_001_[19])
  );
  NOR _319_ (
    .A(clk_f),
    .B(lane_1[20]),
    .Y(_073_)
  );
  NAND _320_ (
    .A(valid_in),
    .B(data_in[20]),
    .Y(_074_)
  );
  NAND _321_ (
    .A(clk_f),
    .B(_074_),
    .Y(_075_)
  );
  NOT _322_ (
    .A(_075_),
    .Y(_076_)
  );
  NOR _323_ (
    .A(_073_),
    .B(_076_),
    .Y(_001_[20])
  );
  NOR _324_ (
    .A(clk_f),
    .B(lane_1[21]),
    .Y(_077_)
  );
  NAND _325_ (
    .A(valid_in),
    .B(data_in[21]),
    .Y(_078_)
  );
  NAND _326_ (
    .A(clk_f),
    .B(_078_),
    .Y(_079_)
  );
  NOT _327_ (
    .A(_079_),
    .Y(_080_)
  );
  NOR _328_ (
    .A(_077_),
    .B(_080_),
    .Y(_001_[21])
  );
  NOR _329_ (
    .A(clk_f),
    .B(lane_1[22]),
    .Y(_081_)
  );
  NAND _330_ (
    .A(valid_in),
    .B(data_in[22]),
    .Y(_082_)
  );
  NAND _331_ (
    .A(clk_f),
    .B(_082_),
    .Y(_083_)
  );
  NOT _332_ (
    .A(_083_),
    .Y(_084_)
  );
  NOR _333_ (
    .A(_081_),
    .B(_084_),
    .Y(_001_[22])
  );
  NOR _334_ (
    .A(clk_f),
    .B(lane_1[23]),
    .Y(_085_)
  );
  NAND _335_ (
    .A(valid_in),
    .B(data_in[23]),
    .Y(_086_)
  );
  NAND _336_ (
    .A(clk_f),
    .B(_086_),
    .Y(_087_)
  );
  NOT _337_ (
    .A(_087_),
    .Y(_088_)
  );
  NOR _338_ (
    .A(_085_),
    .B(_088_),
    .Y(_001_[23])
  );
  NOR _339_ (
    .A(clk_f),
    .B(lane_1[24]),
    .Y(_089_)
  );
  NAND _340_ (
    .A(valid_in),
    .B(data_in[24]),
    .Y(_090_)
  );
  NAND _341_ (
    .A(clk_f),
    .B(_090_),
    .Y(_091_)
  );
  NOT _342_ (
    .A(_091_),
    .Y(_092_)
  );
  NOR _343_ (
    .A(_089_),
    .B(_092_),
    .Y(_001_[24])
  );
  NOR _344_ (
    .A(clk_f),
    .B(lane_1[25]),
    .Y(_093_)
  );
  NAND _345_ (
    .A(valid_in),
    .B(data_in[25]),
    .Y(_094_)
  );
  NAND _346_ (
    .A(clk_f),
    .B(_094_),
    .Y(_095_)
  );
  NOT _347_ (
    .A(_095_),
    .Y(_096_)
  );
  NOR _348_ (
    .A(_093_),
    .B(_096_),
    .Y(_001_[25])
  );
  NOR _349_ (
    .A(clk_f),
    .B(lane_1[26]),
    .Y(_097_)
  );
  NAND _350_ (
    .A(valid_in),
    .B(data_in[26]),
    .Y(_098_)
  );
  NAND _351_ (
    .A(clk_f),
    .B(_098_),
    .Y(_099_)
  );
  NOT _352_ (
    .A(_099_),
    .Y(_100_)
  );
  NOR _353_ (
    .A(_097_),
    .B(_100_),
    .Y(_001_[26])
  );
  NOR _354_ (
    .A(clk_f),
    .B(lane_1[27]),
    .Y(_101_)
  );
  NAND _355_ (
    .A(valid_in),
    .B(data_in[27]),
    .Y(_102_)
  );
  NAND _356_ (
    .A(clk_f),
    .B(_102_),
    .Y(_103_)
  );
  NOT _357_ (
    .A(_103_),
    .Y(_104_)
  );
  NOR _358_ (
    .A(_101_),
    .B(_104_),
    .Y(_001_[27])
  );
  NOR _359_ (
    .A(clk_f),
    .B(lane_1[28]),
    .Y(_105_)
  );
  NAND _360_ (
    .A(valid_in),
    .B(data_in[28]),
    .Y(_106_)
  );
  NAND _361_ (
    .A(clk_f),
    .B(_106_),
    .Y(_107_)
  );
  NOT _362_ (
    .A(_107_),
    .Y(_108_)
  );
  NOR _363_ (
    .A(_105_),
    .B(_108_),
    .Y(_001_[28])
  );
  NOR _364_ (
    .A(clk_f),
    .B(lane_1[29]),
    .Y(_109_)
  );
  NAND _365_ (
    .A(valid_in),
    .B(data_in[29]),
    .Y(_110_)
  );
  NAND _366_ (
    .A(clk_f),
    .B(_110_),
    .Y(_111_)
  );
  NOT _367_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _368_ (
    .A(_109_),
    .B(_112_),
    .Y(_001_[29])
  );
  NOR _369_ (
    .A(clk_f),
    .B(lane_1[30]),
    .Y(_113_)
  );
  NAND _370_ (
    .A(valid_in),
    .B(data_in[30]),
    .Y(_114_)
  );
  NAND _371_ (
    .A(clk_f),
    .B(_114_),
    .Y(_115_)
  );
  NOT _372_ (
    .A(_115_),
    .Y(_116_)
  );
  NOR _373_ (
    .A(_113_),
    .B(_116_),
    .Y(_001_[30])
  );
  NOR _374_ (
    .A(clk_f),
    .B(lane_1[31]),
    .Y(_117_)
  );
  NAND _375_ (
    .A(valid_in),
    .B(data_in[31]),
    .Y(_118_)
  );
  NAND _376_ (
    .A(clk_f),
    .B(_118_),
    .Y(_119_)
  );
  NOT _377_ (
    .A(_119_),
    .Y(_120_)
  );
  NOR _378_ (
    .A(_117_),
    .B(_120_),
    .Y(_001_[31])
  );
  NAND _379_ (
    .A(clk_f),
    .B(valid_0),
    .Y(_121_)
  );
  NAND _380_ (
    .A(_004_),
    .B(valid_in),
    .Y(_122_)
  );
  NAND _381_ (
    .A(_121_),
    .B(_122_),
    .Y(_002_)
  );
  NAND _382_ (
    .A(clk_f),
    .B(lane_0[0]),
    .Y(_123_)
  );
  NAND _383_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_124_)
  );
  NOR _384_ (
    .A(clk_f),
    .B(_124_),
    .Y(_125_)
  );
  NOT _385_ (
    .A(_125_),
    .Y(_126_)
  );
  NAND _386_ (
    .A(_123_),
    .B(_126_),
    .Y(_000_[0])
  );
  NAND _387_ (
    .A(clk_f),
    .B(lane_0[1]),
    .Y(_127_)
  );
  NAND _388_ (
    .A(valid_in),
    .B(data_in[1]),
    .Y(_128_)
  );
  NOR _389_ (
    .A(clk_f),
    .B(_128_),
    .Y(_129_)
  );
  NOT _390_ (
    .A(_129_),
    .Y(_130_)
  );
  NAND _391_ (
    .A(_127_),
    .B(_130_),
    .Y(_000_[1])
  );
  NAND _392_ (
    .A(clk_f),
    .B(lane_0[2]),
    .Y(_131_)
  );
  NAND _393_ (
    .A(valid_in),
    .B(data_in[2]),
    .Y(_132_)
  );
  NOR _394_ (
    .A(clk_f),
    .B(_132_),
    .Y(_133_)
  );
  NOT _395_ (
    .A(_133_),
    .Y(_134_)
  );
  NAND _396_ (
    .A(_131_),
    .B(_134_),
    .Y(_000_[2])
  );
  NAND _397_ (
    .A(clk_f),
    .B(lane_0[3]),
    .Y(_135_)
  );
  NOR _398_ (
    .A(clk_f),
    .B(_006_),
    .Y(_136_)
  );
  NOT _399_ (
    .A(_136_),
    .Y(_137_)
  );
  NAND _400_ (
    .A(_135_),
    .B(_137_),
    .Y(_000_[3])
  );
  NAND _401_ (
    .A(clk_f),
    .B(lane_0[4]),
    .Y(_138_)
  );
  NOR _402_ (
    .A(clk_f),
    .B(_010_),
    .Y(_139_)
  );
  NOT _403_ (
    .A(_139_),
    .Y(_140_)
  );
  NAND _404_ (
    .A(_138_),
    .B(_140_),
    .Y(_000_[4])
  );
  NAND _405_ (
    .A(clk_f),
    .B(lane_0[5]),
    .Y(_141_)
  );
  NOR _406_ (
    .A(clk_f),
    .B(_014_),
    .Y(_142_)
  );
  NOT _407_ (
    .A(_142_),
    .Y(_143_)
  );
  NAND _408_ (
    .A(_141_),
    .B(_143_),
    .Y(_000_[5])
  );
  NAND _409_ (
    .A(clk_f),
    .B(lane_0[6]),
    .Y(_144_)
  );
  NOR _410_ (
    .A(clk_f),
    .B(_018_),
    .Y(_145_)
  );
  NOT _411_ (
    .A(_145_),
    .Y(_146_)
  );
  NAND _412_ (
    .A(_144_),
    .B(_146_),
    .Y(_000_[6])
  );
  NAND _413_ (
    .A(clk_f),
    .B(lane_0[7]),
    .Y(_147_)
  );
  NOR _414_ (
    .A(clk_f),
    .B(_022_),
    .Y(_148_)
  );
  NOT _415_ (
    .A(_148_),
    .Y(_149_)
  );
  NAND _416_ (
    .A(_147_),
    .B(_149_),
    .Y(_000_[7])
  );
  NAND _417_ (
    .A(clk_f),
    .B(lane_0[8]),
    .Y(_150_)
  );
  NOR _418_ (
    .A(clk_f),
    .B(_026_),
    .Y(_151_)
  );
  NOT _419_ (
    .A(_151_),
    .Y(_152_)
  );
  NAND _420_ (
    .A(_150_),
    .B(_152_),
    .Y(_000_[8])
  );
  NAND _421_ (
    .A(clk_f),
    .B(lane_0[9]),
    .Y(_153_)
  );
  NOR _422_ (
    .A(clk_f),
    .B(_030_),
    .Y(_154_)
  );
  NOT _423_ (
    .A(_154_),
    .Y(_155_)
  );
  NAND _424_ (
    .A(_153_),
    .B(_155_),
    .Y(_000_[9])
  );
  NAND _425_ (
    .A(clk_f),
    .B(lane_0[10]),
    .Y(_156_)
  );
  NOR _426_ (
    .A(clk_f),
    .B(_034_),
    .Y(_157_)
  );
  NOT _427_ (
    .A(_157_),
    .Y(_158_)
  );
  NAND _428_ (
    .A(_156_),
    .B(_158_),
    .Y(_000_[10])
  );
  NAND _429_ (
    .A(clk_f),
    .B(lane_0[11]),
    .Y(_159_)
  );
  NOR _430_ (
    .A(clk_f),
    .B(_038_),
    .Y(_160_)
  );
  NOT _431_ (
    .A(_160_),
    .Y(_161_)
  );
  NAND _432_ (
    .A(_159_),
    .B(_161_),
    .Y(_000_[11])
  );
  NAND _433_ (
    .A(clk_f),
    .B(lane_0[12]),
    .Y(_162_)
  );
  NOR _434_ (
    .A(clk_f),
    .B(_042_),
    .Y(_163_)
  );
  NOT _435_ (
    .A(_163_),
    .Y(_164_)
  );
  NAND _436_ (
    .A(_162_),
    .B(_164_),
    .Y(_000_[12])
  );
  NAND _437_ (
    .A(clk_f),
    .B(lane_0[13]),
    .Y(_165_)
  );
  NOR _438_ (
    .A(clk_f),
    .B(_046_),
    .Y(_166_)
  );
  NOT _439_ (
    .A(_166_),
    .Y(_167_)
  );
  NAND _440_ (
    .A(_165_),
    .B(_167_),
    .Y(_000_[13])
  );
  NAND _441_ (
    .A(clk_f),
    .B(lane_0[14]),
    .Y(_168_)
  );
  NOR _442_ (
    .A(clk_f),
    .B(_050_),
    .Y(_169_)
  );
  NOT _443_ (
    .A(_169_),
    .Y(_170_)
  );
  NAND _444_ (
    .A(_168_),
    .B(_170_),
    .Y(_000_[14])
  );
  NAND _445_ (
    .A(clk_f),
    .B(lane_0[15]),
    .Y(_171_)
  );
  NOR _446_ (
    .A(clk_f),
    .B(_054_),
    .Y(_172_)
  );
  NOT _447_ (
    .A(_172_),
    .Y(_173_)
  );
  NAND _448_ (
    .A(_171_),
    .B(_173_),
    .Y(_000_[15])
  );
  NAND _449_ (
    .A(clk_f),
    .B(lane_0[16]),
    .Y(_174_)
  );
  NOR _450_ (
    .A(clk_f),
    .B(_058_),
    .Y(_175_)
  );
  NOT _451_ (
    .A(_175_),
    .Y(_176_)
  );
  NAND _452_ (
    .A(_174_),
    .B(_176_),
    .Y(_000_[16])
  );
  NAND _453_ (
    .A(clk_f),
    .B(lane_0[17]),
    .Y(_177_)
  );
  NOR _454_ (
    .A(clk_f),
    .B(_062_),
    .Y(_178_)
  );
  NOT _455_ (
    .A(_178_),
    .Y(_179_)
  );
  NAND _456_ (
    .A(_177_),
    .B(_179_),
    .Y(_000_[17])
  );
  NAND _457_ (
    .A(clk_f),
    .B(lane_0[18]),
    .Y(_180_)
  );
  NOR _458_ (
    .A(clk_f),
    .B(_066_),
    .Y(_181_)
  );
  NOT _459_ (
    .A(_181_),
    .Y(_182_)
  );
  NAND _460_ (
    .A(_180_),
    .B(_182_),
    .Y(_000_[18])
  );
  NAND _461_ (
    .A(clk_f),
    .B(lane_0[19]),
    .Y(_183_)
  );
  NOR _462_ (
    .A(clk_f),
    .B(_070_),
    .Y(_184_)
  );
  NOT _463_ (
    .A(_184_),
    .Y(_185_)
  );
  NAND _464_ (
    .A(_183_),
    .B(_185_),
    .Y(_000_[19])
  );
  NAND _465_ (
    .A(clk_f),
    .B(lane_0[20]),
    .Y(_186_)
  );
  NOR _466_ (
    .A(clk_f),
    .B(_074_),
    .Y(_187_)
  );
  NOT _467_ (
    .A(_187_),
    .Y(_188_)
  );
  NAND _468_ (
    .A(_186_),
    .B(_188_),
    .Y(_000_[20])
  );
  NAND _469_ (
    .A(clk_f),
    .B(lane_0[21]),
    .Y(_189_)
  );
  NOR _470_ (
    .A(clk_f),
    .B(_078_),
    .Y(_190_)
  );
  NOT _471_ (
    .A(_190_),
    .Y(_191_)
  );
  NAND _472_ (
    .A(_189_),
    .B(_191_),
    .Y(_000_[21])
  );
  NAND _473_ (
    .A(clk_f),
    .B(lane_0[22]),
    .Y(_192_)
  );
  NOR _474_ (
    .A(clk_f),
    .B(_082_),
    .Y(_193_)
  );
  NOT _475_ (
    .A(_193_),
    .Y(_194_)
  );
  NAND _476_ (
    .A(_192_),
    .B(_194_),
    .Y(_000_[22])
  );
  NAND _477_ (
    .A(clk_f),
    .B(lane_0[23]),
    .Y(_195_)
  );
  NOR _478_ (
    .A(clk_f),
    .B(_086_),
    .Y(_196_)
  );
  NOT _479_ (
    .A(_196_),
    .Y(_197_)
  );
  NAND _480_ (
    .A(_195_),
    .B(_197_),
    .Y(_000_[23])
  );
  NAND _481_ (
    .A(clk_f),
    .B(lane_0[24]),
    .Y(_198_)
  );
  NOR _482_ (
    .A(clk_f),
    .B(_090_),
    .Y(_199_)
  );
  NOT _483_ (
    .A(_199_),
    .Y(_200_)
  );
  NAND _484_ (
    .A(_198_),
    .B(_200_),
    .Y(_000_[24])
  );
  NAND _485_ (
    .A(clk_f),
    .B(lane_0[25]),
    .Y(_201_)
  );
  NOR _486_ (
    .A(clk_f),
    .B(_094_),
    .Y(_202_)
  );
  NOT _487_ (
    .A(_202_),
    .Y(_203_)
  );
  NAND _488_ (
    .A(_201_),
    .B(_203_),
    .Y(_000_[25])
  );
  NAND _489_ (
    .A(clk_f),
    .B(lane_0[26]),
    .Y(_204_)
  );
  NOR _490_ (
    .A(clk_f),
    .B(_098_),
    .Y(_205_)
  );
  NOT _491_ (
    .A(_205_),
    .Y(_206_)
  );
  NAND _492_ (
    .A(_204_),
    .B(_206_),
    .Y(_000_[26])
  );
  NAND _493_ (
    .A(clk_f),
    .B(lane_0[27]),
    .Y(_207_)
  );
  NOR _494_ (
    .A(clk_f),
    .B(_102_),
    .Y(_208_)
  );
  NOT _495_ (
    .A(_208_),
    .Y(_209_)
  );
  NAND _496_ (
    .A(_207_),
    .B(_209_),
    .Y(_000_[27])
  );
  NAND _497_ (
    .A(clk_f),
    .B(lane_0[28]),
    .Y(_210_)
  );
  NOR _498_ (
    .A(clk_f),
    .B(_106_),
    .Y(_211_)
  );
  NOT _499_ (
    .A(_211_),
    .Y(_212_)
  );
  NAND _500_ (
    .A(_210_),
    .B(_212_),
    .Y(_000_[28])
  );
  NAND _501_ (
    .A(clk_f),
    .B(lane_0[29]),
    .Y(_213_)
  );
  NOR _502_ (
    .A(clk_f),
    .B(_110_),
    .Y(_214_)
  );
  NOT _503_ (
    .A(_214_),
    .Y(_215_)
  );
  NAND _504_ (
    .A(_213_),
    .B(_215_),
    .Y(_000_[29])
  );
  NAND _505_ (
    .A(clk_f),
    .B(lane_0[30]),
    .Y(_216_)
  );
  NOR _506_ (
    .A(clk_f),
    .B(_114_),
    .Y(_217_)
  );
  NOT _507_ (
    .A(_217_),
    .Y(_218_)
  );
  NAND _508_ (
    .A(_216_),
    .B(_218_),
    .Y(_000_[30])
  );
  NAND _509_ (
    .A(clk_f),
    .B(lane_0[31]),
    .Y(_219_)
  );
  NOR _510_ (
    .A(clk_f),
    .B(_118_),
    .Y(_220_)
  );
  NOT _511_ (
    .A(_220_),
    .Y(_221_)
  );
  NAND _512_ (
    .A(_219_),
    .B(_221_),
    .Y(_000_[31])
  );
  NAND _513_ (
    .A(clk_f),
    .B(valid_in),
    .Y(_222_)
  );
  NAND _514_ (
    .A(_004_),
    .B(valid_1),
    .Y(_223_)
  );
  NAND _515_ (
    .A(_222_),
    .B(_223_),
    .Y(_003_)
  );
  NOR _516_ (
    .A(clk_f),
    .B(lane_1[0]),
    .Y(_224_)
  );
  NAND _517_ (
    .A(clk_f),
    .B(_124_),
    .Y(_225_)
  );
  NOT _518_ (
    .A(_225_),
    .Y(_226_)
  );
  NOR _519_ (
    .A(_224_),
    .B(_226_),
    .Y(_001_[0])
  );
  NOR _520_ (
    .A(clk_f),
    .B(lane_1[1]),
    .Y(_227_)
  );
  NAND _521_ (
    .A(clk_f),
    .B(_128_),
    .Y(_228_)
  );
  NOT _522_ (
    .A(_228_),
    .Y(_229_)
  );
  NOR _523_ (
    .A(_227_),
    .B(_229_),
    .Y(_001_[1])
  );
  NOR _524_ (
    .A(clk_f),
    .B(lane_1[2]),
    .Y(_230_)
  );
  NAND _525_ (
    .A(clk_f),
    .B(_132_),
    .Y(_231_)
  );
  NOT _526_ (
    .A(_231_),
    .Y(_232_)
  );
  NOR _527_ (
    .A(_230_),
    .B(_232_),
    .Y(_001_[2])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _528_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(lane_0[0])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _529_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(lane_0[1])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _530_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(lane_0[2])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _531_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(lane_0[3])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _532_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(lane_0[4])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _533_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(lane_0[5])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _534_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(lane_0[6])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _535_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(lane_0[7])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _536_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(lane_0[8])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _537_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(lane_0[9])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _538_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(lane_0[10])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _539_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(lane_0[11])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _540_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(lane_0[12])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _541_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(lane_0[13])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _542_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(lane_0[14])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _543_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(lane_0[15])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _544_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(lane_0[16])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _545_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(lane_0[17])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _546_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(lane_0[18])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _547_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(lane_0[19])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _548_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(lane_0[20])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _549_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(lane_0[21])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _550_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(lane_0[22])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _551_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(lane_0[23])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _552_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(lane_0[24])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _553_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(lane_0[25])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _554_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(lane_0[26])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _555_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(lane_0[27])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _556_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(lane_0[28])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _557_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(lane_0[29])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _558_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(lane_0[30])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _559_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(lane_0[31])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _560_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(lane_1[0])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _561_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(lane_1[1])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _562_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(lane_1[2])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _563_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(lane_1[3])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _564_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(lane_1[4])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _565_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(lane_1[5])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _566_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(lane_1[6])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _567_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(lane_1[7])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _568_ (
    .C(clk_2f),
    .D(_001_[8]),
    .Q(lane_1[8])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _569_ (
    .C(clk_2f),
    .D(_001_[9]),
    .Q(lane_1[9])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _570_ (
    .C(clk_2f),
    .D(_001_[10]),
    .Q(lane_1[10])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _571_ (
    .C(clk_2f),
    .D(_001_[11]),
    .Q(lane_1[11])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _572_ (
    .C(clk_2f),
    .D(_001_[12]),
    .Q(lane_1[12])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _573_ (
    .C(clk_2f),
    .D(_001_[13]),
    .Q(lane_1[13])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _574_ (
    .C(clk_2f),
    .D(_001_[14]),
    .Q(lane_1[14])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _575_ (
    .C(clk_2f),
    .D(_001_[15]),
    .Q(lane_1[15])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _576_ (
    .C(clk_2f),
    .D(_001_[16]),
    .Q(lane_1[16])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _577_ (
    .C(clk_2f),
    .D(_001_[17]),
    .Q(lane_1[17])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _578_ (
    .C(clk_2f),
    .D(_001_[18]),
    .Q(lane_1[18])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _579_ (
    .C(clk_2f),
    .D(_001_[19]),
    .Q(lane_1[19])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _580_ (
    .C(clk_2f),
    .D(_001_[20]),
    .Q(lane_1[20])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _581_ (
    .C(clk_2f),
    .D(_001_[21]),
    .Q(lane_1[21])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _582_ (
    .C(clk_2f),
    .D(_001_[22]),
    .Q(lane_1[22])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _583_ (
    .C(clk_2f),
    .D(_001_[23]),
    .Q(lane_1[23])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _584_ (
    .C(clk_2f),
    .D(_001_[24]),
    .Q(lane_1[24])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _585_ (
    .C(clk_2f),
    .D(_001_[25]),
    .Q(lane_1[25])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _586_ (
    .C(clk_2f),
    .D(_001_[26]),
    .Q(lane_1[26])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _587_ (
    .C(clk_2f),
    .D(_001_[27]),
    .Q(lane_1[27])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _588_ (
    .C(clk_2f),
    .D(_001_[28]),
    .Q(lane_1[28])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _589_ (
    .C(clk_2f),
    .D(_001_[29]),
    .Q(lane_1[29])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _590_ (
    .C(clk_2f),
    .D(_001_[30]),
    .Q(lane_1[30])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _591_ (
    .C(clk_2f),
    .D(_001_[31]),
    .Q(lane_1[31])
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _592_ (
    .C(clk_2f),
    .D(_002_),
    .Q(valid_0)
  );
  (* src = "lib/byte_striping.v:14" *)
  DFF _593_ (
    .C(clk_2f),
    .D(_003_),
    .Q(valid_1)
  );
endmodule
