/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "byte_striping.v:7" *)
module BYTE_STRIPING(lane_0, lane_1, valid_0, valid_1, data_in, valid_in, clk_2f, clk_f);
  (* src = "byte_striping.v:14" *)
  wire [31:0] _000_;
  (* src = "byte_striping.v:14" *)
  wire [31:0] _001_;
  (* src = "byte_striping.v:14" *)
  wire _002_;
  (* src = "byte_striping.v:14" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  (* src = "byte_striping.v:12" *)
  input clk_2f;
  (* src = "byte_striping.v:12" *)
  input clk_f;
  (* src = "byte_striping.v:10" *)
  input [31:0] data_in;
  (* src = "byte_striping.v:8" *)
  output [31:0] lane_0;
  (* src = "byte_striping.v:8" *)
  output [31:0] lane_1;
  (* src = "byte_striping.v:9" *)
  output valid_0;
  (* src = "byte_striping.v:9" *)
  output valid_1;
  (* src = "byte_striping.v:11" *)
  input valid_in;
  NOT _233_ (
    .A(clk_f),
    .Y(_004_)
  );
  NAND _234_ (
    .A(valid_in),
    .B(clk_f),
    .Y(_005_)
  );
  NAND _235_ (
    .A(valid_1),
    .B(_004_),
    .Y(_006_)
  );
  NAND _236_ (
    .A(_005_),
    .B(_006_),
    .Y(_003_)
  );
  NAND _237_ (
    .A(valid_in),
    .B(data_in[0]),
    .Y(_007_)
  );
  NOR _238_ (
    .A(clk_f),
    .B(lane_1[0]),
    .Y(_008_)
  );
  NAND _239_ (
    .A(clk_f),
    .B(_007_),
    .Y(_009_)
  );
  NOT _240_ (
    .A(_009_),
    .Y(_010_)
  );
  NOR _241_ (
    .A(_008_),
    .B(_010_),
    .Y(_001_[0])
  );
  NAND _242_ (
    .A(data_in[1]),
    .B(valid_in),
    .Y(_011_)
  );
  NOR _243_ (
    .A(clk_f),
    .B(lane_1[1]),
    .Y(_012_)
  );
  NAND _244_ (
    .A(clk_f),
    .B(_011_),
    .Y(_013_)
  );
  NOT _245_ (
    .A(_013_),
    .Y(_014_)
  );
  NOR _246_ (
    .A(_012_),
    .B(_014_),
    .Y(_001_[1])
  );
  NAND _247_ (
    .A(valid_in),
    .B(data_in[2]),
    .Y(_015_)
  );
  NOR _248_ (
    .A(clk_f),
    .B(lane_1[2]),
    .Y(_016_)
  );
  NAND _249_ (
    .A(clk_f),
    .B(_015_),
    .Y(_017_)
  );
  NOT _250_ (
    .A(_017_),
    .Y(_018_)
  );
  NOR _251_ (
    .A(_016_),
    .B(_018_),
    .Y(_001_[2])
  );
  NAND _252_ (
    .A(valid_in),
    .B(data_in[3]),
    .Y(_019_)
  );
  NOR _253_ (
    .A(clk_f),
    .B(lane_1[3]),
    .Y(_020_)
  );
  NAND _254_ (
    .A(clk_f),
    .B(_019_),
    .Y(_021_)
  );
  NOT _255_ (
    .A(_021_),
    .Y(_022_)
  );
  NOR _256_ (
    .A(_020_),
    .B(_022_),
    .Y(_001_[3])
  );
  NAND _257_ (
    .A(valid_in),
    .B(data_in[4]),
    .Y(_023_)
  );
  NOR _258_ (
    .A(clk_f),
    .B(lane_1[4]),
    .Y(_024_)
  );
  NAND _259_ (
    .A(clk_f),
    .B(_023_),
    .Y(_025_)
  );
  NOT _260_ (
    .A(_025_),
    .Y(_026_)
  );
  NOR _261_ (
    .A(_024_),
    .B(_026_),
    .Y(_001_[4])
  );
  NAND _262_ (
    .A(valid_in),
    .B(data_in[5]),
    .Y(_027_)
  );
  NOR _263_ (
    .A(clk_f),
    .B(lane_1[5]),
    .Y(_028_)
  );
  NAND _264_ (
    .A(clk_f),
    .B(_027_),
    .Y(_029_)
  );
  NOT _265_ (
    .A(_029_),
    .Y(_030_)
  );
  NOR _266_ (
    .A(_028_),
    .B(_030_),
    .Y(_001_[5])
  );
  NAND _267_ (
    .A(valid_in),
    .B(data_in[6]),
    .Y(_031_)
  );
  NOR _268_ (
    .A(clk_f),
    .B(lane_1[6]),
    .Y(_032_)
  );
  NAND _269_ (
    .A(clk_f),
    .B(_031_),
    .Y(_033_)
  );
  NOT _270_ (
    .A(_033_),
    .Y(_034_)
  );
  NOR _271_ (
    .A(_032_),
    .B(_034_),
    .Y(_001_[6])
  );
  NAND _272_ (
    .A(valid_in),
    .B(data_in[7]),
    .Y(_035_)
  );
  NOR _273_ (
    .A(clk_f),
    .B(lane_1[7]),
    .Y(_036_)
  );
  NAND _274_ (
    .A(clk_f),
    .B(_035_),
    .Y(_037_)
  );
  NOT _275_ (
    .A(_037_),
    .Y(_038_)
  );
  NOR _276_ (
    .A(_036_),
    .B(_038_),
    .Y(_001_[7])
  );
  NAND _277_ (
    .A(valid_in),
    .B(data_in[8]),
    .Y(_039_)
  );
  NOR _278_ (
    .A(clk_f),
    .B(lane_1[8]),
    .Y(_040_)
  );
  NAND _279_ (
    .A(clk_f),
    .B(_039_),
    .Y(_041_)
  );
  NOT _280_ (
    .A(_041_),
    .Y(_042_)
  );
  NOR _281_ (
    .A(_040_),
    .B(_042_),
    .Y(_001_[8])
  );
  NAND _282_ (
    .A(valid_in),
    .B(data_in[9]),
    .Y(_043_)
  );
  NOR _283_ (
    .A(clk_f),
    .B(lane_1[9]),
    .Y(_044_)
  );
  NAND _284_ (
    .A(clk_f),
    .B(_043_),
    .Y(_045_)
  );
  NOT _285_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _286_ (
    .A(_044_),
    .B(_046_),
    .Y(_001_[9])
  );
  NAND _287_ (
    .A(valid_in),
    .B(data_in[10]),
    .Y(_047_)
  );
  NOR _288_ (
    .A(clk_f),
    .B(lane_1[10]),
    .Y(_048_)
  );
  NAND _289_ (
    .A(clk_f),
    .B(_047_),
    .Y(_049_)
  );
  NOT _290_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR _291_ (
    .A(_048_),
    .B(_050_),
    .Y(_001_[10])
  );
  NAND _292_ (
    .A(valid_in),
    .B(data_in[11]),
    .Y(_051_)
  );
  NOR _293_ (
    .A(clk_f),
    .B(lane_1[11]),
    .Y(_052_)
  );
  NAND _294_ (
    .A(clk_f),
    .B(_051_),
    .Y(_053_)
  );
  NOT _295_ (
    .A(_053_),
    .Y(_054_)
  );
  NOR _296_ (
    .A(_052_),
    .B(_054_),
    .Y(_001_[11])
  );
  NAND _297_ (
    .A(valid_in),
    .B(data_in[12]),
    .Y(_055_)
  );
  NOR _298_ (
    .A(clk_f),
    .B(lane_1[12]),
    .Y(_056_)
  );
  NAND _299_ (
    .A(clk_f),
    .B(_055_),
    .Y(_057_)
  );
  NOT _300_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR _301_ (
    .A(_056_),
    .B(_058_),
    .Y(_001_[12])
  );
  NAND _302_ (
    .A(valid_in),
    .B(data_in[13]),
    .Y(_059_)
  );
  NOR _303_ (
    .A(clk_f),
    .B(lane_1[13]),
    .Y(_060_)
  );
  NAND _304_ (
    .A(clk_f),
    .B(_059_),
    .Y(_061_)
  );
  NOT _305_ (
    .A(_061_),
    .Y(_062_)
  );
  NOR _306_ (
    .A(_060_),
    .B(_062_),
    .Y(_001_[13])
  );
  NAND _307_ (
    .A(valid_in),
    .B(data_in[14]),
    .Y(_063_)
  );
  NOR _308_ (
    .A(clk_f),
    .B(lane_1[14]),
    .Y(_064_)
  );
  NAND _309_ (
    .A(clk_f),
    .B(_063_),
    .Y(_065_)
  );
  NOT _310_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _311_ (
    .A(_064_),
    .B(_066_),
    .Y(_001_[14])
  );
  NAND _312_ (
    .A(valid_in),
    .B(data_in[15]),
    .Y(_067_)
  );
  NOR _313_ (
    .A(clk_f),
    .B(lane_1[15]),
    .Y(_068_)
  );
  NAND _314_ (
    .A(clk_f),
    .B(_067_),
    .Y(_069_)
  );
  NOT _315_ (
    .A(_069_),
    .Y(_070_)
  );
  NOR _316_ (
    .A(_068_),
    .B(_070_),
    .Y(_001_[15])
  );
  NAND _317_ (
    .A(valid_in),
    .B(data_in[16]),
    .Y(_071_)
  );
  NOR _318_ (
    .A(clk_f),
    .B(lane_1[16]),
    .Y(_072_)
  );
  NAND _319_ (
    .A(clk_f),
    .B(_071_),
    .Y(_073_)
  );
  NOT _320_ (
    .A(_073_),
    .Y(_074_)
  );
  NOR _321_ (
    .A(_072_),
    .B(_074_),
    .Y(_001_[16])
  );
  NAND _322_ (
    .A(valid_in),
    .B(data_in[17]),
    .Y(_075_)
  );
  NOR _323_ (
    .A(clk_f),
    .B(lane_1[17]),
    .Y(_076_)
  );
  NAND _324_ (
    .A(clk_f),
    .B(_075_),
    .Y(_077_)
  );
  NOT _325_ (
    .A(_077_),
    .Y(_078_)
  );
  NOR _326_ (
    .A(_076_),
    .B(_078_),
    .Y(_001_[17])
  );
  NAND _327_ (
    .A(valid_in),
    .B(data_in[18]),
    .Y(_079_)
  );
  NOR _328_ (
    .A(clk_f),
    .B(lane_1[18]),
    .Y(_080_)
  );
  NAND _329_ (
    .A(clk_f),
    .B(_079_),
    .Y(_081_)
  );
  NOT _330_ (
    .A(_081_),
    .Y(_082_)
  );
  NOR _331_ (
    .A(_080_),
    .B(_082_),
    .Y(_001_[18])
  );
  NAND _332_ (
    .A(valid_in),
    .B(data_in[19]),
    .Y(_083_)
  );
  NOR _333_ (
    .A(clk_f),
    .B(lane_1[19]),
    .Y(_084_)
  );
  NAND _334_ (
    .A(clk_f),
    .B(_083_),
    .Y(_085_)
  );
  NOT _335_ (
    .A(_085_),
    .Y(_086_)
  );
  NOR _336_ (
    .A(_084_),
    .B(_086_),
    .Y(_001_[19])
  );
  NAND _337_ (
    .A(valid_in),
    .B(data_in[20]),
    .Y(_087_)
  );
  NOR _338_ (
    .A(clk_f),
    .B(lane_1[20]),
    .Y(_088_)
  );
  NAND _339_ (
    .A(clk_f),
    .B(_087_),
    .Y(_089_)
  );
  NOT _340_ (
    .A(_089_),
    .Y(_090_)
  );
  NOR _341_ (
    .A(_088_),
    .B(_090_),
    .Y(_001_[20])
  );
  NAND _342_ (
    .A(valid_in),
    .B(data_in[21]),
    .Y(_091_)
  );
  NOR _343_ (
    .A(clk_f),
    .B(lane_1[21]),
    .Y(_092_)
  );
  NAND _344_ (
    .A(clk_f),
    .B(_091_),
    .Y(_093_)
  );
  NOT _345_ (
    .A(_093_),
    .Y(_094_)
  );
  NOR _346_ (
    .A(_092_),
    .B(_094_),
    .Y(_001_[21])
  );
  NAND _347_ (
    .A(valid_in),
    .B(data_in[22]),
    .Y(_095_)
  );
  NOR _348_ (
    .A(clk_f),
    .B(lane_1[22]),
    .Y(_096_)
  );
  NAND _349_ (
    .A(clk_f),
    .B(_095_),
    .Y(_097_)
  );
  NOT _350_ (
    .A(_097_),
    .Y(_098_)
  );
  NOR _351_ (
    .A(_096_),
    .B(_098_),
    .Y(_001_[22])
  );
  NAND _352_ (
    .A(valid_in),
    .B(data_in[23]),
    .Y(_099_)
  );
  NOR _353_ (
    .A(clk_f),
    .B(lane_1[23]),
    .Y(_100_)
  );
  NAND _354_ (
    .A(clk_f),
    .B(_099_),
    .Y(_101_)
  );
  NOT _355_ (
    .A(_101_),
    .Y(_102_)
  );
  NOR _356_ (
    .A(_100_),
    .B(_102_),
    .Y(_001_[23])
  );
  NAND _357_ (
    .A(valid_in),
    .B(data_in[24]),
    .Y(_103_)
  );
  NOR _358_ (
    .A(clk_f),
    .B(lane_1[24]),
    .Y(_104_)
  );
  NAND _359_ (
    .A(clk_f),
    .B(_103_),
    .Y(_105_)
  );
  NOT _360_ (
    .A(_105_),
    .Y(_106_)
  );
  NOR _361_ (
    .A(_104_),
    .B(_106_),
    .Y(_001_[24])
  );
  NAND _362_ (
    .A(valid_in),
    .B(data_in[25]),
    .Y(_107_)
  );
  NOR _363_ (
    .A(clk_f),
    .B(lane_1[25]),
    .Y(_108_)
  );
  NAND _364_ (
    .A(clk_f),
    .B(_107_),
    .Y(_109_)
  );
  NOT _365_ (
    .A(_109_),
    .Y(_110_)
  );
  NOR _366_ (
    .A(_108_),
    .B(_110_),
    .Y(_001_[25])
  );
  NAND _367_ (
    .A(valid_in),
    .B(data_in[26]),
    .Y(_111_)
  );
  NOR _368_ (
    .A(clk_f),
    .B(lane_1[26]),
    .Y(_112_)
  );
  NAND _369_ (
    .A(clk_f),
    .B(_111_),
    .Y(_113_)
  );
  NOT _370_ (
    .A(_113_),
    .Y(_114_)
  );
  NOR _371_ (
    .A(_112_),
    .B(_114_),
    .Y(_001_[26])
  );
  NAND _372_ (
    .A(valid_in),
    .B(data_in[27]),
    .Y(_115_)
  );
  NOR _373_ (
    .A(clk_f),
    .B(lane_1[27]),
    .Y(_116_)
  );
  NAND _374_ (
    .A(clk_f),
    .B(_115_),
    .Y(_117_)
  );
  NOT _375_ (
    .A(_117_),
    .Y(_118_)
  );
  NOR _376_ (
    .A(_116_),
    .B(_118_),
    .Y(_001_[27])
  );
  NAND _377_ (
    .A(valid_in),
    .B(data_in[28]),
    .Y(_119_)
  );
  NOR _378_ (
    .A(clk_f),
    .B(lane_1[28]),
    .Y(_120_)
  );
  NAND _379_ (
    .A(clk_f),
    .B(_119_),
    .Y(_121_)
  );
  NOT _380_ (
    .A(_121_),
    .Y(_122_)
  );
  NOR _381_ (
    .A(_120_),
    .B(_122_),
    .Y(_001_[28])
  );
  NAND _382_ (
    .A(valid_in),
    .B(data_in[29]),
    .Y(_123_)
  );
  NOR _383_ (
    .A(clk_f),
    .B(lane_1[29]),
    .Y(_124_)
  );
  NAND _384_ (
    .A(clk_f),
    .B(_123_),
    .Y(_125_)
  );
  NOT _385_ (
    .A(_125_),
    .Y(_126_)
  );
  NOR _386_ (
    .A(_124_),
    .B(_126_),
    .Y(_001_[29])
  );
  NAND _387_ (
    .A(valid_in),
    .B(data_in[30]),
    .Y(_127_)
  );
  NOR _388_ (
    .A(clk_f),
    .B(lane_1[30]),
    .Y(_128_)
  );
  NAND _389_ (
    .A(clk_f),
    .B(_127_),
    .Y(_129_)
  );
  NOT _390_ (
    .A(_129_),
    .Y(_130_)
  );
  NOR _391_ (
    .A(_128_),
    .B(_130_),
    .Y(_001_[30])
  );
  NAND _392_ (
    .A(valid_in),
    .B(data_in[31]),
    .Y(_131_)
  );
  NOR _393_ (
    .A(clk_f),
    .B(lane_1[31]),
    .Y(_132_)
  );
  NAND _394_ (
    .A(clk_f),
    .B(_131_),
    .Y(_133_)
  );
  NOT _395_ (
    .A(_133_),
    .Y(_134_)
  );
  NOR _396_ (
    .A(_132_),
    .B(_134_),
    .Y(_001_[31])
  );
  NAND _397_ (
    .A(clk_f),
    .B(lane_0[0]),
    .Y(_135_)
  );
  NOR _398_ (
    .A(clk_f),
    .B(_007_),
    .Y(_136_)
  );
  NOT _399_ (
    .A(_136_),
    .Y(_137_)
  );
  NAND _400_ (
    .A(_135_),
    .B(_137_),
    .Y(_000_[0])
  );
  NAND _401_ (
    .A(clk_f),
    .B(lane_0[1]),
    .Y(_138_)
  );
  NOR _402_ (
    .A(clk_f),
    .B(_011_),
    .Y(_139_)
  );
  NOT _403_ (
    .A(_139_),
    .Y(_140_)
  );
  NAND _404_ (
    .A(_138_),
    .B(_140_),
    .Y(_000_[1])
  );
  NAND _405_ (
    .A(clk_f),
    .B(lane_0[2]),
    .Y(_141_)
  );
  NOR _406_ (
    .A(clk_f),
    .B(_015_),
    .Y(_142_)
  );
  NOT _407_ (
    .A(_142_),
    .Y(_143_)
  );
  NAND _408_ (
    .A(_141_),
    .B(_143_),
    .Y(_000_[2])
  );
  NAND _409_ (
    .A(clk_f),
    .B(lane_0[3]),
    .Y(_144_)
  );
  NOR _410_ (
    .A(clk_f),
    .B(_019_),
    .Y(_145_)
  );
  NOT _411_ (
    .A(_145_),
    .Y(_146_)
  );
  NAND _412_ (
    .A(_144_),
    .B(_146_),
    .Y(_000_[3])
  );
  NAND _413_ (
    .A(clk_f),
    .B(lane_0[4]),
    .Y(_147_)
  );
  NOR _414_ (
    .A(clk_f),
    .B(_023_),
    .Y(_148_)
  );
  NOT _415_ (
    .A(_148_),
    .Y(_149_)
  );
  NAND _416_ (
    .A(_147_),
    .B(_149_),
    .Y(_000_[4])
  );
  NAND _417_ (
    .A(clk_f),
    .B(lane_0[5]),
    .Y(_150_)
  );
  NOR _418_ (
    .A(clk_f),
    .B(_027_),
    .Y(_151_)
  );
  NOT _419_ (
    .A(_151_),
    .Y(_152_)
  );
  NAND _420_ (
    .A(_150_),
    .B(_152_),
    .Y(_000_[5])
  );
  NAND _421_ (
    .A(clk_f),
    .B(lane_0[6]),
    .Y(_153_)
  );
  NOR _422_ (
    .A(clk_f),
    .B(_031_),
    .Y(_154_)
  );
  NOT _423_ (
    .A(_154_),
    .Y(_155_)
  );
  NAND _424_ (
    .A(_153_),
    .B(_155_),
    .Y(_000_[6])
  );
  NAND _425_ (
    .A(clk_f),
    .B(lane_0[7]),
    .Y(_156_)
  );
  NOR _426_ (
    .A(clk_f),
    .B(_035_),
    .Y(_157_)
  );
  NOT _427_ (
    .A(_157_),
    .Y(_158_)
  );
  NAND _428_ (
    .A(_156_),
    .B(_158_),
    .Y(_000_[7])
  );
  NAND _429_ (
    .A(clk_f),
    .B(lane_0[8]),
    .Y(_159_)
  );
  NOR _430_ (
    .A(clk_f),
    .B(_039_),
    .Y(_160_)
  );
  NOT _431_ (
    .A(_160_),
    .Y(_161_)
  );
  NAND _432_ (
    .A(_159_),
    .B(_161_),
    .Y(_000_[8])
  );
  NAND _433_ (
    .A(clk_f),
    .B(lane_0[9]),
    .Y(_162_)
  );
  NOR _434_ (
    .A(clk_f),
    .B(_043_),
    .Y(_163_)
  );
  NOT _435_ (
    .A(_163_),
    .Y(_164_)
  );
  NAND _436_ (
    .A(_162_),
    .B(_164_),
    .Y(_000_[9])
  );
  NAND _437_ (
    .A(clk_f),
    .B(lane_0[10]),
    .Y(_165_)
  );
  NOR _438_ (
    .A(clk_f),
    .B(_047_),
    .Y(_166_)
  );
  NOT _439_ (
    .A(_166_),
    .Y(_167_)
  );
  NAND _440_ (
    .A(_165_),
    .B(_167_),
    .Y(_000_[10])
  );
  NAND _441_ (
    .A(clk_f),
    .B(lane_0[11]),
    .Y(_168_)
  );
  NOR _442_ (
    .A(clk_f),
    .B(_051_),
    .Y(_169_)
  );
  NOT _443_ (
    .A(_169_),
    .Y(_170_)
  );
  NAND _444_ (
    .A(_168_),
    .B(_170_),
    .Y(_000_[11])
  );
  NAND _445_ (
    .A(clk_f),
    .B(lane_0[12]),
    .Y(_171_)
  );
  NOR _446_ (
    .A(clk_f),
    .B(_055_),
    .Y(_172_)
  );
  NOT _447_ (
    .A(_172_),
    .Y(_173_)
  );
  NAND _448_ (
    .A(_171_),
    .B(_173_),
    .Y(_000_[12])
  );
  NAND _449_ (
    .A(clk_f),
    .B(lane_0[13]),
    .Y(_174_)
  );
  NOR _450_ (
    .A(clk_f),
    .B(_059_),
    .Y(_175_)
  );
  NOT _451_ (
    .A(_175_),
    .Y(_176_)
  );
  NAND _452_ (
    .A(_174_),
    .B(_176_),
    .Y(_000_[13])
  );
  NAND _453_ (
    .A(clk_f),
    .B(lane_0[14]),
    .Y(_177_)
  );
  NOR _454_ (
    .A(clk_f),
    .B(_063_),
    .Y(_178_)
  );
  NOT _455_ (
    .A(_178_),
    .Y(_179_)
  );
  NAND _456_ (
    .A(_177_),
    .B(_179_),
    .Y(_000_[14])
  );
  NAND _457_ (
    .A(clk_f),
    .B(lane_0[15]),
    .Y(_180_)
  );
  NOR _458_ (
    .A(clk_f),
    .B(_067_),
    .Y(_181_)
  );
  NOT _459_ (
    .A(_181_),
    .Y(_182_)
  );
  NAND _460_ (
    .A(_180_),
    .B(_182_),
    .Y(_000_[15])
  );
  NAND _461_ (
    .A(clk_f),
    .B(lane_0[16]),
    .Y(_183_)
  );
  NOR _462_ (
    .A(clk_f),
    .B(_071_),
    .Y(_184_)
  );
  NOT _463_ (
    .A(_184_),
    .Y(_185_)
  );
  NAND _464_ (
    .A(_183_),
    .B(_185_),
    .Y(_000_[16])
  );
  NAND _465_ (
    .A(clk_f),
    .B(lane_0[17]),
    .Y(_186_)
  );
  NOR _466_ (
    .A(clk_f),
    .B(_075_),
    .Y(_187_)
  );
  NOT _467_ (
    .A(_187_),
    .Y(_188_)
  );
  NAND _468_ (
    .A(_186_),
    .B(_188_),
    .Y(_000_[17])
  );
  NAND _469_ (
    .A(clk_f),
    .B(lane_0[18]),
    .Y(_189_)
  );
  NOR _470_ (
    .A(clk_f),
    .B(_079_),
    .Y(_190_)
  );
  NOT _471_ (
    .A(_190_),
    .Y(_191_)
  );
  NAND _472_ (
    .A(_189_),
    .B(_191_),
    .Y(_000_[18])
  );
  NAND _473_ (
    .A(clk_f),
    .B(lane_0[19]),
    .Y(_192_)
  );
  NOR _474_ (
    .A(clk_f),
    .B(_083_),
    .Y(_193_)
  );
  NOT _475_ (
    .A(_193_),
    .Y(_194_)
  );
  NAND _476_ (
    .A(_192_),
    .B(_194_),
    .Y(_000_[19])
  );
  NAND _477_ (
    .A(clk_f),
    .B(lane_0[20]),
    .Y(_195_)
  );
  NOR _478_ (
    .A(clk_f),
    .B(_087_),
    .Y(_196_)
  );
  NOT _479_ (
    .A(_196_),
    .Y(_197_)
  );
  NAND _480_ (
    .A(_195_),
    .B(_197_),
    .Y(_000_[20])
  );
  NAND _481_ (
    .A(clk_f),
    .B(lane_0[21]),
    .Y(_198_)
  );
  NOR _482_ (
    .A(clk_f),
    .B(_091_),
    .Y(_199_)
  );
  NOT _483_ (
    .A(_199_),
    .Y(_200_)
  );
  NAND _484_ (
    .A(_198_),
    .B(_200_),
    .Y(_000_[21])
  );
  NAND _485_ (
    .A(clk_f),
    .B(lane_0[22]),
    .Y(_201_)
  );
  NOR _486_ (
    .A(clk_f),
    .B(_095_),
    .Y(_202_)
  );
  NOT _487_ (
    .A(_202_),
    .Y(_203_)
  );
  NAND _488_ (
    .A(_201_),
    .B(_203_),
    .Y(_000_[22])
  );
  NAND _489_ (
    .A(clk_f),
    .B(lane_0[23]),
    .Y(_204_)
  );
  NOR _490_ (
    .A(clk_f),
    .B(_099_),
    .Y(_205_)
  );
  NOT _491_ (
    .A(_205_),
    .Y(_206_)
  );
  NAND _492_ (
    .A(_204_),
    .B(_206_),
    .Y(_000_[23])
  );
  NAND _493_ (
    .A(clk_f),
    .B(lane_0[24]),
    .Y(_207_)
  );
  NOR _494_ (
    .A(clk_f),
    .B(_103_),
    .Y(_208_)
  );
  NOT _495_ (
    .A(_208_),
    .Y(_209_)
  );
  NAND _496_ (
    .A(_207_),
    .B(_209_),
    .Y(_000_[24])
  );
  NAND _497_ (
    .A(clk_f),
    .B(lane_0[25]),
    .Y(_210_)
  );
  NOR _498_ (
    .A(clk_f),
    .B(_107_),
    .Y(_211_)
  );
  NOT _499_ (
    .A(_211_),
    .Y(_212_)
  );
  NAND _500_ (
    .A(_210_),
    .B(_212_),
    .Y(_000_[25])
  );
  NAND _501_ (
    .A(clk_f),
    .B(lane_0[26]),
    .Y(_213_)
  );
  NOR _502_ (
    .A(clk_f),
    .B(_111_),
    .Y(_214_)
  );
  NOT _503_ (
    .A(_214_),
    .Y(_215_)
  );
  NAND _504_ (
    .A(_213_),
    .B(_215_),
    .Y(_000_[26])
  );
  NAND _505_ (
    .A(clk_f),
    .B(lane_0[27]),
    .Y(_216_)
  );
  NOR _506_ (
    .A(clk_f),
    .B(_115_),
    .Y(_217_)
  );
  NOT _507_ (
    .A(_217_),
    .Y(_218_)
  );
  NAND _508_ (
    .A(_216_),
    .B(_218_),
    .Y(_000_[27])
  );
  NAND _509_ (
    .A(clk_f),
    .B(lane_0[28]),
    .Y(_219_)
  );
  NOR _510_ (
    .A(clk_f),
    .B(_119_),
    .Y(_220_)
  );
  NOT _511_ (
    .A(_220_),
    .Y(_221_)
  );
  NAND _512_ (
    .A(_219_),
    .B(_221_),
    .Y(_000_[28])
  );
  NAND _513_ (
    .A(clk_f),
    .B(lane_0[29]),
    .Y(_222_)
  );
  NOR _514_ (
    .A(clk_f),
    .B(_123_),
    .Y(_223_)
  );
  NOT _515_ (
    .A(_223_),
    .Y(_224_)
  );
  NAND _516_ (
    .A(_222_),
    .B(_224_),
    .Y(_000_[29])
  );
  NAND _517_ (
    .A(clk_f),
    .B(lane_0[30]),
    .Y(_225_)
  );
  NOR _518_ (
    .A(clk_f),
    .B(_127_),
    .Y(_226_)
  );
  NOT _519_ (
    .A(_226_),
    .Y(_227_)
  );
  NAND _520_ (
    .A(_225_),
    .B(_227_),
    .Y(_000_[30])
  );
  NAND _521_ (
    .A(clk_f),
    .B(lane_0[31]),
    .Y(_228_)
  );
  NOR _522_ (
    .A(clk_f),
    .B(_131_),
    .Y(_229_)
  );
  NOT _523_ (
    .A(_229_),
    .Y(_230_)
  );
  NAND _524_ (
    .A(_228_),
    .B(_230_),
    .Y(_000_[31])
  );
  NAND _525_ (
    .A(clk_f),
    .B(valid_0),
    .Y(_231_)
  );
  NAND _526_ (
    .A(valid_in),
    .B(_004_),
    .Y(_232_)
  );
  NAND _527_ (
    .A(_231_),
    .B(_232_),
    .Y(_002_)
  );
  (* src = "byte_striping.v:14" *)
  DFF _528_ (
    .C(clk_2f),
    .D(_002_),
    .Q(valid_0)
  );
  (* src = "byte_striping.v:14" *)
  DFF _529_ (
    .C(clk_2f),
    .D(_003_),
    .Q(valid_1)
  );
  (* src = "byte_striping.v:14" *)
  DFF _530_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(lane_0[0])
  );
  (* src = "byte_striping.v:14" *)
  DFF _531_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(lane_0[1])
  );
  (* src = "byte_striping.v:14" *)
  DFF _532_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(lane_0[2])
  );
  (* src = "byte_striping.v:14" *)
  DFF _533_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(lane_0[3])
  );
  (* src = "byte_striping.v:14" *)
  DFF _534_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(lane_0[4])
  );
  (* src = "byte_striping.v:14" *)
  DFF _535_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(lane_0[5])
  );
  (* src = "byte_striping.v:14" *)
  DFF _536_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(lane_0[6])
  );
  (* src = "byte_striping.v:14" *)
  DFF _537_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(lane_0[7])
  );
  (* src = "byte_striping.v:14" *)
  DFF _538_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(lane_0[8])
  );
  (* src = "byte_striping.v:14" *)
  DFF _539_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(lane_0[9])
  );
  (* src = "byte_striping.v:14" *)
  DFF _540_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(lane_0[10])
  );
  (* src = "byte_striping.v:14" *)
  DFF _541_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(lane_0[11])
  );
  (* src = "byte_striping.v:14" *)
  DFF _542_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(lane_0[12])
  );
  (* src = "byte_striping.v:14" *)
  DFF _543_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(lane_0[13])
  );
  (* src = "byte_striping.v:14" *)
  DFF _544_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(lane_0[14])
  );
  (* src = "byte_striping.v:14" *)
  DFF _545_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(lane_0[15])
  );
  (* src = "byte_striping.v:14" *)
  DFF _546_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(lane_0[16])
  );
  (* src = "byte_striping.v:14" *)
  DFF _547_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(lane_0[17])
  );
  (* src = "byte_striping.v:14" *)
  DFF _548_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(lane_0[18])
  );
  (* src = "byte_striping.v:14" *)
  DFF _549_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(lane_0[19])
  );
  (* src = "byte_striping.v:14" *)
  DFF _550_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(lane_0[20])
  );
  (* src = "byte_striping.v:14" *)
  DFF _551_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(lane_0[21])
  );
  (* src = "byte_striping.v:14" *)
  DFF _552_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(lane_0[22])
  );
  (* src = "byte_striping.v:14" *)
  DFF _553_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(lane_0[23])
  );
  (* src = "byte_striping.v:14" *)
  DFF _554_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(lane_0[24])
  );
  (* src = "byte_striping.v:14" *)
  DFF _555_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(lane_0[25])
  );
  (* src = "byte_striping.v:14" *)
  DFF _556_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(lane_0[26])
  );
  (* src = "byte_striping.v:14" *)
  DFF _557_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(lane_0[27])
  );
  (* src = "byte_striping.v:14" *)
  DFF _558_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(lane_0[28])
  );
  (* src = "byte_striping.v:14" *)
  DFF _559_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(lane_0[29])
  );
  (* src = "byte_striping.v:14" *)
  DFF _560_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(lane_0[30])
  );
  (* src = "byte_striping.v:14" *)
  DFF _561_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(lane_0[31])
  );
  (* src = "byte_striping.v:14" *)
  DFF _562_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(lane_1[0])
  );
  (* src = "byte_striping.v:14" *)
  DFF _563_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(lane_1[1])
  );
  (* src = "byte_striping.v:14" *)
  DFF _564_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(lane_1[2])
  );
  (* src = "byte_striping.v:14" *)
  DFF _565_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(lane_1[3])
  );
  (* src = "byte_striping.v:14" *)
  DFF _566_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(lane_1[4])
  );
  (* src = "byte_striping.v:14" *)
  DFF _567_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(lane_1[5])
  );
  (* src = "byte_striping.v:14" *)
  DFF _568_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(lane_1[6])
  );
  (* src = "byte_striping.v:14" *)
  DFF _569_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(lane_1[7])
  );
  (* src = "byte_striping.v:14" *)
  DFF _570_ (
    .C(clk_2f),
    .D(_001_[8]),
    .Q(lane_1[8])
  );
  (* src = "byte_striping.v:14" *)
  DFF _571_ (
    .C(clk_2f),
    .D(_001_[9]),
    .Q(lane_1[9])
  );
  (* src = "byte_striping.v:14" *)
  DFF _572_ (
    .C(clk_2f),
    .D(_001_[10]),
    .Q(lane_1[10])
  );
  (* src = "byte_striping.v:14" *)
  DFF _573_ (
    .C(clk_2f),
    .D(_001_[11]),
    .Q(lane_1[11])
  );
  (* src = "byte_striping.v:14" *)
  DFF _574_ (
    .C(clk_2f),
    .D(_001_[12]),
    .Q(lane_1[12])
  );
  (* src = "byte_striping.v:14" *)
  DFF _575_ (
    .C(clk_2f),
    .D(_001_[13]),
    .Q(lane_1[13])
  );
  (* src = "byte_striping.v:14" *)
  DFF _576_ (
    .C(clk_2f),
    .D(_001_[14]),
    .Q(lane_1[14])
  );
  (* src = "byte_striping.v:14" *)
  DFF _577_ (
    .C(clk_2f),
    .D(_001_[15]),
    .Q(lane_1[15])
  );
  (* src = "byte_striping.v:14" *)
  DFF _578_ (
    .C(clk_2f),
    .D(_001_[16]),
    .Q(lane_1[16])
  );
  (* src = "byte_striping.v:14" *)
  DFF _579_ (
    .C(clk_2f),
    .D(_001_[17]),
    .Q(lane_1[17])
  );
  (* src = "byte_striping.v:14" *)
  DFF _580_ (
    .C(clk_2f),
    .D(_001_[18]),
    .Q(lane_1[18])
  );
  (* src = "byte_striping.v:14" *)
  DFF _581_ (
    .C(clk_2f),
    .D(_001_[19]),
    .Q(lane_1[19])
  );
  (* src = "byte_striping.v:14" *)
  DFF _582_ (
    .C(clk_2f),
    .D(_001_[20]),
    .Q(lane_1[20])
  );
  (* src = "byte_striping.v:14" *)
  DFF _583_ (
    .C(clk_2f),
    .D(_001_[21]),
    .Q(lane_1[21])
  );
  (* src = "byte_striping.v:14" *)
  DFF _584_ (
    .C(clk_2f),
    .D(_001_[22]),
    .Q(lane_1[22])
  );
  (* src = "byte_striping.v:14" *)
  DFF _585_ (
    .C(clk_2f),
    .D(_001_[23]),
    .Q(lane_1[23])
  );
  (* src = "byte_striping.v:14" *)
  DFF _586_ (
    .C(clk_2f),
    .D(_001_[24]),
    .Q(lane_1[24])
  );
  (* src = "byte_striping.v:14" *)
  DFF _587_ (
    .C(clk_2f),
    .D(_001_[25]),
    .Q(lane_1[25])
  );
  (* src = "byte_striping.v:14" *)
  DFF _588_ (
    .C(clk_2f),
    .D(_001_[26]),
    .Q(lane_1[26])
  );
  (* src = "byte_striping.v:14" *)
  DFF _589_ (
    .C(clk_2f),
    .D(_001_[27]),
    .Q(lane_1[27])
  );
  (* src = "byte_striping.v:14" *)
  DFF _590_ (
    .C(clk_2f),
    .D(_001_[28]),
    .Q(lane_1[28])
  );
  (* src = "byte_striping.v:14" *)
  DFF _591_ (
    .C(clk_2f),
    .D(_001_[29]),
    .Q(lane_1[29])
  );
  (* src = "byte_striping.v:14" *)
  DFF _592_ (
    .C(clk_2f),
    .D(_001_[30]),
    .Q(lane_1[30])
  );
  (* src = "byte_striping.v:14" *)
  DFF _593_ (
    .C(clk_2f),
    .D(_001_[31]),
    .Q(lane_1[31])
  );
endmodule

(* src = "byte_unstriping.v:7" *)
module BYTE_UNSTRIPING(data_out, valid_out, lane_0, lane_1, valid_0, valid_1, clk_2f, clk_f);
  (* src = "byte_unstriping.v:13" *)
  wire [31:0] _000_;
  (* src = "byte_unstriping.v:13" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "byte_unstriping.v:11" *)
  input clk_2f;
  (* src = "byte_unstriping.v:11" *)
  input clk_f;
  (* src = "byte_unstriping.v:8" *)
  output [31:0] data_out;
  (* src = "byte_unstriping.v:10" *)
  input [31:0] lane_0;
  (* src = "byte_unstriping.v:10" *)
  input [31:0] lane_1;
  (* src = "byte_unstriping.v:11" *)
  input valid_0;
  (* src = "byte_unstriping.v:11" *)
  input valid_1;
  (* src = "byte_unstriping.v:9" *)
  output valid_out;
  NOT _072_ (
    .A(valid_1),
    .Y(_002_)
  );
  NOT _073_ (
    .A(valid_0),
    .Y(_003_)
  );
  NOT _074_ (
    .A(clk_f),
    .Y(_004_)
  );
  NOR _075_ (
    .A(_003_),
    .B(clk_f),
    .Y(_005_)
  );
  NAND _076_ (
    .A(lane_0[0]),
    .B(_005_),
    .Y(_006_)
  );
  NOR _077_ (
    .A(_002_),
    .B(_004_),
    .Y(_007_)
  );
  NAND _078_ (
    .A(lane_1[0]),
    .B(_007_),
    .Y(_008_)
  );
  NAND _079_ (
    .A(_006_),
    .B(_008_),
    .Y(_000_[0])
  );
  NAND _080_ (
    .A(lane_0[1]),
    .B(_005_),
    .Y(_009_)
  );
  NAND _081_ (
    .A(lane_1[1]),
    .B(_007_),
    .Y(_010_)
  );
  NAND _082_ (
    .A(_009_),
    .B(_010_),
    .Y(_000_[1])
  );
  NAND _083_ (
    .A(lane_0[2]),
    .B(_005_),
    .Y(_011_)
  );
  NAND _084_ (
    .A(lane_1[2]),
    .B(_007_),
    .Y(_012_)
  );
  NAND _085_ (
    .A(_011_),
    .B(_012_),
    .Y(_000_[2])
  );
  NAND _086_ (
    .A(lane_0[3]),
    .B(_005_),
    .Y(_013_)
  );
  NAND _087_ (
    .A(lane_1[3]),
    .B(_007_),
    .Y(_014_)
  );
  NAND _088_ (
    .A(_013_),
    .B(_014_),
    .Y(_000_[3])
  );
  NAND _089_ (
    .A(lane_0[4]),
    .B(_005_),
    .Y(_015_)
  );
  NAND _090_ (
    .A(lane_1[4]),
    .B(_007_),
    .Y(_016_)
  );
  NAND _091_ (
    .A(_015_),
    .B(_016_),
    .Y(_000_[4])
  );
  NAND _092_ (
    .A(lane_0[5]),
    .B(_005_),
    .Y(_017_)
  );
  NAND _093_ (
    .A(lane_1[5]),
    .B(_007_),
    .Y(_018_)
  );
  NAND _094_ (
    .A(_017_),
    .B(_018_),
    .Y(_000_[5])
  );
  NAND _095_ (
    .A(lane_0[6]),
    .B(_005_),
    .Y(_019_)
  );
  NAND _096_ (
    .A(lane_1[6]),
    .B(_007_),
    .Y(_020_)
  );
  NAND _097_ (
    .A(_019_),
    .B(_020_),
    .Y(_000_[6])
  );
  NAND _098_ (
    .A(lane_0[7]),
    .B(_005_),
    .Y(_021_)
  );
  NAND _099_ (
    .A(lane_1[7]),
    .B(_007_),
    .Y(_022_)
  );
  NAND _100_ (
    .A(_021_),
    .B(_022_),
    .Y(_000_[7])
  );
  NAND _101_ (
    .A(lane_0[8]),
    .B(_005_),
    .Y(_023_)
  );
  NAND _102_ (
    .A(lane_1[8]),
    .B(_007_),
    .Y(_024_)
  );
  NAND _103_ (
    .A(_023_),
    .B(_024_),
    .Y(_000_[8])
  );
  NAND _104_ (
    .A(lane_0[9]),
    .B(_005_),
    .Y(_025_)
  );
  NAND _105_ (
    .A(lane_1[9]),
    .B(_007_),
    .Y(_026_)
  );
  NAND _106_ (
    .A(_025_),
    .B(_026_),
    .Y(_000_[9])
  );
  NAND _107_ (
    .A(lane_0[10]),
    .B(_005_),
    .Y(_027_)
  );
  NAND _108_ (
    .A(lane_1[10]),
    .B(_007_),
    .Y(_028_)
  );
  NAND _109_ (
    .A(_027_),
    .B(_028_),
    .Y(_000_[10])
  );
  NAND _110_ (
    .A(lane_0[11]),
    .B(_005_),
    .Y(_029_)
  );
  NAND _111_ (
    .A(lane_1[11]),
    .B(_007_),
    .Y(_030_)
  );
  NAND _112_ (
    .A(_029_),
    .B(_030_),
    .Y(_000_[11])
  );
  NAND _113_ (
    .A(lane_0[12]),
    .B(_005_),
    .Y(_031_)
  );
  NAND _114_ (
    .A(lane_1[12]),
    .B(_007_),
    .Y(_032_)
  );
  NAND _115_ (
    .A(_031_),
    .B(_032_),
    .Y(_000_[12])
  );
  NAND _116_ (
    .A(lane_0[13]),
    .B(_005_),
    .Y(_033_)
  );
  NAND _117_ (
    .A(lane_1[13]),
    .B(_007_),
    .Y(_034_)
  );
  NAND _118_ (
    .A(_033_),
    .B(_034_),
    .Y(_000_[13])
  );
  NAND _119_ (
    .A(lane_0[14]),
    .B(_005_),
    .Y(_035_)
  );
  NAND _120_ (
    .A(lane_1[14]),
    .B(_007_),
    .Y(_036_)
  );
  NAND _121_ (
    .A(_035_),
    .B(_036_),
    .Y(_000_[14])
  );
  NAND _122_ (
    .A(lane_0[15]),
    .B(_005_),
    .Y(_037_)
  );
  NAND _123_ (
    .A(lane_1[15]),
    .B(_007_),
    .Y(_038_)
  );
  NAND _124_ (
    .A(_037_),
    .B(_038_),
    .Y(_000_[15])
  );
  NAND _125_ (
    .A(lane_0[16]),
    .B(_005_),
    .Y(_039_)
  );
  NAND _126_ (
    .A(lane_1[16]),
    .B(_007_),
    .Y(_040_)
  );
  NAND _127_ (
    .A(_039_),
    .B(_040_),
    .Y(_000_[16])
  );
  NAND _128_ (
    .A(lane_0[17]),
    .B(_005_),
    .Y(_041_)
  );
  NAND _129_ (
    .A(lane_1[17]),
    .B(_007_),
    .Y(_042_)
  );
  NAND _130_ (
    .A(_041_),
    .B(_042_),
    .Y(_000_[17])
  );
  NAND _131_ (
    .A(lane_0[18]),
    .B(_005_),
    .Y(_043_)
  );
  NAND _132_ (
    .A(lane_1[18]),
    .B(_007_),
    .Y(_044_)
  );
  NAND _133_ (
    .A(_043_),
    .B(_044_),
    .Y(_000_[18])
  );
  NAND _134_ (
    .A(lane_0[19]),
    .B(_005_),
    .Y(_045_)
  );
  NAND _135_ (
    .A(lane_1[19]),
    .B(_007_),
    .Y(_046_)
  );
  NAND _136_ (
    .A(_045_),
    .B(_046_),
    .Y(_000_[19])
  );
  NAND _137_ (
    .A(lane_0[20]),
    .B(_005_),
    .Y(_047_)
  );
  NAND _138_ (
    .A(lane_1[20]),
    .B(_007_),
    .Y(_048_)
  );
  NAND _139_ (
    .A(_047_),
    .B(_048_),
    .Y(_000_[20])
  );
  NAND _140_ (
    .A(lane_0[21]),
    .B(_005_),
    .Y(_049_)
  );
  NAND _141_ (
    .A(lane_1[21]),
    .B(_007_),
    .Y(_050_)
  );
  NAND _142_ (
    .A(_049_),
    .B(_050_),
    .Y(_000_[21])
  );
  NAND _143_ (
    .A(lane_0[22]),
    .B(_005_),
    .Y(_051_)
  );
  NAND _144_ (
    .A(lane_1[22]),
    .B(_007_),
    .Y(_052_)
  );
  NAND _145_ (
    .A(_051_),
    .B(_052_),
    .Y(_000_[22])
  );
  NAND _146_ (
    .A(lane_0[23]),
    .B(_005_),
    .Y(_053_)
  );
  NAND _147_ (
    .A(lane_1[23]),
    .B(_007_),
    .Y(_054_)
  );
  NAND _148_ (
    .A(_053_),
    .B(_054_),
    .Y(_000_[23])
  );
  NAND _149_ (
    .A(lane_0[24]),
    .B(_005_),
    .Y(_055_)
  );
  NAND _150_ (
    .A(lane_1[24]),
    .B(_007_),
    .Y(_056_)
  );
  NAND _151_ (
    .A(_055_),
    .B(_056_),
    .Y(_000_[24])
  );
  NAND _152_ (
    .A(lane_0[25]),
    .B(_005_),
    .Y(_057_)
  );
  NAND _153_ (
    .A(lane_1[25]),
    .B(_007_),
    .Y(_058_)
  );
  NAND _154_ (
    .A(_057_),
    .B(_058_),
    .Y(_000_[25])
  );
  NAND _155_ (
    .A(lane_0[26]),
    .B(_005_),
    .Y(_059_)
  );
  NAND _156_ (
    .A(lane_1[26]),
    .B(_007_),
    .Y(_060_)
  );
  NAND _157_ (
    .A(_059_),
    .B(_060_),
    .Y(_000_[26])
  );
  NAND _158_ (
    .A(lane_0[27]),
    .B(_005_),
    .Y(_061_)
  );
  NAND _159_ (
    .A(lane_1[27]),
    .B(_007_),
    .Y(_062_)
  );
  NAND _160_ (
    .A(_061_),
    .B(_062_),
    .Y(_000_[27])
  );
  NAND _161_ (
    .A(lane_0[28]),
    .B(_005_),
    .Y(_063_)
  );
  NAND _162_ (
    .A(lane_1[28]),
    .B(_007_),
    .Y(_064_)
  );
  NAND _163_ (
    .A(_063_),
    .B(_064_),
    .Y(_000_[28])
  );
  NAND _164_ (
    .A(lane_0[29]),
    .B(_005_),
    .Y(_065_)
  );
  NAND _165_ (
    .A(lane_1[29]),
    .B(_007_),
    .Y(_066_)
  );
  NAND _166_ (
    .A(_065_),
    .B(_066_),
    .Y(_000_[29])
  );
  NAND _167_ (
    .A(lane_0[30]),
    .B(_005_),
    .Y(_067_)
  );
  NAND _168_ (
    .A(lane_1[30]),
    .B(_007_),
    .Y(_068_)
  );
  NAND _169_ (
    .A(_067_),
    .B(_068_),
    .Y(_000_[30])
  );
  NAND _170_ (
    .A(lane_0[31]),
    .B(_005_),
    .Y(_069_)
  );
  NAND _171_ (
    .A(lane_1[31]),
    .B(_007_),
    .Y(_070_)
  );
  NAND _172_ (
    .A(_069_),
    .B(_070_),
    .Y(_000_[31])
  );
  NOR _173_ (
    .A(_005_),
    .B(_007_),
    .Y(_071_)
  );
  NOT _174_ (
    .A(_071_),
    .Y(_001_)
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _175_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _176_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _177_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _178_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _179_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _180_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _181_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _182_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _183_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(data_out[8])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _184_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(data_out[9])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _185_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(data_out[10])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _186_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(data_out[11])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _187_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(data_out[12])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _188_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(data_out[13])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _189_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(data_out[14])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _190_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(data_out[15])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _191_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(data_out[16])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _192_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(data_out[17])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _193_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(data_out[18])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _194_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(data_out[19])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _195_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(data_out[20])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _196_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(data_out[21])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _197_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(data_out[22])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _198_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(data_out[23])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _199_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(data_out[24])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _200_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(data_out[25])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _201_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(data_out[26])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _202_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(data_out[27])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _203_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(data_out[28])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _204_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(data_out[29])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _205_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(data_out[30])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _206_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(data_out[31])
  );
  (* src = "byte_unstriping.v:13" *)
  DFF _207_ (
    .C(clk_2f),
    .D(_001_),
    .Q(valid_out)
  );
endmodule

(* top =  1  *)
(* src = "phy.v:6" *)
module PHY(data_out, valid_out, data_in, valid_in, reset, clk_32f);
  (* src = "phy.v:12" *)
  wire bus_serial_0;
  (* src = "phy.v:12" *)
  wire bus_serial_1;
  (* src = "phy.v:10" *)
  input clk_32f;
  (* src = "phy.v:9" *)
  input [31:0] data_in;
  (* src = "phy.v:7" *)
  output [31:0] data_out;
  (* src = "phy.v:10" *)
  input reset;
  (* src = "phy.v:10" *)
  input valid_in;
  (* src = "phy.v:8" *)
  output valid_out;
  (* module_not_derived = 32'd1 *)
  (* src = "phy.v:17" *)
  PHY_RX receptor (
    .clk_32f(clk_32f),
    .data_in_0(bus_serial_0),
    .data_in_1(bus_serial_1),
    .data_out(data_out),
    .reset(reset),
    .valid_out(valid_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy.v:15" *)
  PHY_TX transmisor (
    .clk_32f(clk_32f),
    .data_in(data_in),
    .data_out_0(bus_serial_0),
    .data_out_1(bus_serial_1),
    .reset(reset),
    .valid_in(valid_in)
  );
endmodule

(* src = "phy_rx.v:7" *)
module PHY_RX(data_out, valid_out, data_in_0, data_in_1, reset, clk_32f);
  (* src = "phy_rx.v:14" *)
  wire clk_2f;
  (* src = "phy_rx.v:11" *)
  input clk_32f;
  (* src = "phy_rx.v:14" *)
  wire clk_4f;
  (* src = "phy_rx.v:14" *)
  wire clk_f;
  (* src = "phy_rx.v:16" *)
  wire [31:0] data_32b_0;
  (* src = "phy_rx.v:16" *)
  wire [31:0] data_32b_1;
  (* src = "phy_rx.v:15" *)
  wire [7:0] data_8b_0;
  (* src = "phy_rx.v:15" *)
  wire [7:0] data_8b_1;
  (* src = "phy_rx.v:10" *)
  input data_in_0;
  (* src = "phy_rx.v:10" *)
  input data_in_1;
  (* src = "phy_rx.v:8" *)
  output [31:0] data_out;
  (* src = "phy_rx.v:11" *)
  input reset;
  (* src = "phy_rx.v:20" *)
  wire sincro;
  (* src = "phy_rx.v:20" *)
  (* unused_bits = "0" *)
  wire tierra;
  (* src = "phy_rx.v:19" *)
  wire valid_32b_0;
  (* src = "phy_rx.v:19" *)
  wire valid_32b_1;
  (* src = "phy_rx.v:18" *)
  wire valid_8b_0;
  (* src = "phy_rx.v:18" *)
  wire valid_8b_1;
  (* src = "phy_rx.v:9" *)
  output valid_out;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx.v:24" *)
  BYTE_UNSTRIPING bte_unstrp (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_out(data_out),
    .lane_0(data_32b_0),
    .lane_1(data_32b_1),
    .valid_0(valid_32b_0),
    .valid_1(valid_32b_1),
    .valid_out(valid_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx.v:22" *)
  clk_gen clock_gen (
    .clk_2f(clk_2f),
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx.v:26" *)
  m8_32 conv_0 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .data_8_32(data_32b_0),
    .data_input(data_8b_0),
    .reset(reset),
    .sinc(1'h0),
    .sincout(sincro),
    .valid_8_32(valid_32b_0),
    .valid_input(valid_8b_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx.v:28" *)
  m8_32 conv_1 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .data_8_32(data_32b_1),
    .data_input(data_8b_1),
    .reset(reset),
    .sinc(sincro),
    .sincout(tierra),
    .valid_8_32(valid_32b_1),
    .valid_input(valid_8b_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx.v:31" *)
  serial_paralelo serelo_0 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(data_in_0),
    .data_out(data_8b_0),
    .valid_out(valid_8b_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_rx.v:32" *)
  serial_paralelo serelo_1 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(data_in_1),
    .data_out(data_8b_1),
    .valid_out(valid_8b_1)
  );
endmodule

(* src = "phy_tx.v:8" *)
module PHY_TX(data_out_0, data_out_1, data_in, valid_in, reset, clk_32f);
  (* src = "phy_tx.v:14" *)
  wire clk_2f;
  (* src = "phy_tx.v:11" *)
  input clk_32f;
  (* src = "phy_tx.v:14" *)
  wire clk_4f;
  (* src = "phy_tx.v:14" *)
  wire clk_f;
  (* src = "phy_tx.v:16" *)
  wire [7:0] data_8b_0;
  (* src = "phy_tx.v:16" *)
  wire [7:0] data_8b_1;
  (* src = "phy_tx.v:10" *)
  input [31:0] data_in;
  (* src = "phy_tx.v:9" *)
  output data_out_0;
  (* src = "phy_tx.v:9" *)
  output data_out_1;
  (* src = "phy_tx.v:15" *)
  wire [31:0] lane_0;
  (* src = "phy_tx.v:15" *)
  wire [31:0] lane_1;
  (* src = "phy_tx.v:11" *)
  input reset;
  (* src = "phy_tx.v:18" *)
  wire valid_0;
  (* src = "phy_tx.v:18" *)
  wire valid_1;
  (* src = "phy_tx.v:11" *)
  input valid_in;
  (* src = "phy_tx.v:17" *)
  wire valid_out_0;
  (* src = "phy_tx.v:17" *)
  wire valid_out_1;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:23" *)
  BYTE_STRIPING bte_strp (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_in(data_in),
    .lane_0(lane_0),
    .lane_1(lane_1),
    .valid_0(valid_0),
    .valid_1(valid_1),
    .valid_in(valid_in)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:21" *)
  clk_gen clock_gen (
    .clk_2f(clk_2f),
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .clk_f(clk_f),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:25" *)
  m32_8 conv_0 (
    .clk_4f(clk_4f),
    .data_32_8(data_8b_0),
    .data_strp(lane_0),
    .reset(reset),
    .valid_32_8(valid_out_0),
    .valid_strp(valid_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:26" *)
  m32_8 conv_1 (
    .clk_4f(clk_4f),
    .data_32_8(data_8b_1),
    .data_strp(lane_1),
    .reset(reset),
    .valid_32_8(valid_out_1),
    .valid_strp(valid_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:29" *)
  paralelo_serial parial_0 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(data_8b_0),
    .data_out(data_out_0),
    .valid_in(valid_out_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx.v:30" *)
  paralelo_serial parial_1 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(data_8b_1),
    .data_out(data_out_1),
    .valid_in(valid_out_1)
  );
endmodule

(* src = "clk_gen.v:8" *)
module clk_gen(clk_f, clk_2f, clk_4f, clk_32f, reset);
  (* src = "clk_gen.v:9" *)
  output clk_2f;
  (* src = "clk_gen.v:11" *)
  input clk_32f;
  (* src = "clk_gen.v:10" *)
  output clk_4f;
  (* src = "clk_gen.v:8" *)
  output clk_f;
  (* src = "clk_gen.v:14" *)
  wire q1;
  (* src = "clk_gen.v:14" *)
  wire q2;
  (* src = "clk_gen.v:12" *)
  input reset;
  assign clk_2f = 1'h0;
  assign clk_4f = 1'h0;
  assign clk_f = 1'h0;
  assign q1 = 1'h0;
  assign q2 = 1'h0;
endmodule

(* src = "m32_8.v:7" *)
module m32_8(data_32_8, valid_32_8, data_strp, valid_strp, reset, clk_4f);
  (* src = "m32_8.v:16" *)
  wire [7:0] _000_;
  (* src = "m32_8.v:16" *)
  wire [1:0] _001_;
  (* src = "m32_8.v:16" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "m32_8.v:12" *)
  input clk_4f;
  (* src = "m32_8.v:7" *)
  output [7:0] data_32_8;
  (* src = "m32_8.v:9" *)
  input [31:0] data_strp;
  (* src = "m32_8.v:11" *)
  input reset;
  (* init = 2'h0 *)
  (* src = "m32_8.v:14" *)
  wire [1:0] selector;
  (* src = "m32_8.v:8" *)
  output valid_32_8;
  (* src = "m32_8.v:10" *)
  input valid_strp;
  NOT _068_ (
    .A(selector[0]),
    .Y(_030_)
  );
  NOT _069_ (
    .A(selector[1]),
    .Y(_031_)
  );
  NAND _070_ (
    .A(valid_strp),
    .B(reset),
    .Y(_032_)
  );
  NOT _071_ (
    .A(_032_),
    .Y(_002_)
  );
  NOR _072_ (
    .A(selector[0]),
    .B(_031_),
    .Y(_033_)
  );
  NAND _073_ (
    .A(data_strp[8]),
    .B(_033_),
    .Y(_034_)
  );
  NOR _074_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_035_)
  );
  NAND _075_ (
    .A(data_strp[24]),
    .B(_035_),
    .Y(_036_)
  );
  NAND _076_ (
    .A(_034_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _077_ (
    .A(_030_),
    .B(selector[1]),
    .Y(_038_)
  );
  NAND _078_ (
    .A(data_strp[16]),
    .B(_038_),
    .Y(_039_)
  );
  NOR _079_ (
    .A(_030_),
    .B(_031_),
    .Y(_040_)
  );
  NAND _080_ (
    .A(data_strp[0]),
    .B(_040_),
    .Y(_041_)
  );
  NAND _081_ (
    .A(_039_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _082_ (
    .A(_037_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _083_ (
    .A(_032_),
    .B(_043_),
    .Y(_000_[0])
  );
  NAND _084_ (
    .A(data_strp[1]),
    .B(_040_),
    .Y(_044_)
  );
  NAND _085_ (
    .A(data_strp[25]),
    .B(_035_),
    .Y(_045_)
  );
  NAND _086_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _087_ (
    .A(data_strp[9]),
    .B(_033_),
    .Y(_047_)
  );
  NAND _088_ (
    .A(data_strp[17]),
    .B(_038_),
    .Y(_048_)
  );
  NAND _089_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _090_ (
    .A(_046_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _091_ (
    .A(_032_),
    .B(_050_),
    .Y(_000_[1])
  );
  NAND _092_ (
    .A(data_strp[2]),
    .B(_040_),
    .Y(_051_)
  );
  NAND _093_ (
    .A(data_strp[26]),
    .B(_035_),
    .Y(_052_)
  );
  NAND _094_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _095_ (
    .A(data_strp[10]),
    .B(_033_),
    .Y(_054_)
  );
  NAND _096_ (
    .A(data_strp[18]),
    .B(_038_),
    .Y(_055_)
  );
  NAND _097_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _098_ (
    .A(_053_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _099_ (
    .A(_032_),
    .B(_057_),
    .Y(_000_[2])
  );
  NAND _100_ (
    .A(data_strp[3]),
    .B(_040_),
    .Y(_058_)
  );
  NAND _101_ (
    .A(data_strp[27]),
    .B(_035_),
    .Y(_059_)
  );
  NAND _102_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _103_ (
    .A(data_strp[11]),
    .B(_033_),
    .Y(_061_)
  );
  NAND _104_ (
    .A(data_strp[19]),
    .B(_038_),
    .Y(_062_)
  );
  NAND _105_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _106_ (
    .A(_060_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _107_ (
    .A(_032_),
    .B(_064_),
    .Y(_000_[3])
  );
  NAND _108_ (
    .A(data_strp[4]),
    .B(_040_),
    .Y(_065_)
  );
  NAND _109_ (
    .A(data_strp[28]),
    .B(_035_),
    .Y(_066_)
  );
  NAND _110_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _111_ (
    .A(data_strp[12]),
    .B(_033_),
    .Y(_003_)
  );
  NAND _112_ (
    .A(data_strp[20]),
    .B(_038_),
    .Y(_004_)
  );
  NAND _113_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  NOR _114_ (
    .A(_067_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _115_ (
    .A(_032_),
    .B(_006_),
    .Y(_000_[4])
  );
  NAND _116_ (
    .A(data_strp[5]),
    .B(_040_),
    .Y(_007_)
  );
  NAND _117_ (
    .A(data_strp[29]),
    .B(_035_),
    .Y(_008_)
  );
  NAND _118_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  NAND _119_ (
    .A(data_strp[13]),
    .B(_033_),
    .Y(_010_)
  );
  NAND _120_ (
    .A(data_strp[21]),
    .B(_038_),
    .Y(_011_)
  );
  NAND _121_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _122_ (
    .A(_009_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _123_ (
    .A(_032_),
    .B(_013_),
    .Y(_000_[5])
  );
  NAND _124_ (
    .A(data_strp[6]),
    .B(_040_),
    .Y(_014_)
  );
  NAND _125_ (
    .A(data_strp[30]),
    .B(_035_),
    .Y(_015_)
  );
  NAND _126_ (
    .A(_014_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _127_ (
    .A(data_strp[14]),
    .B(_033_),
    .Y(_017_)
  );
  NAND _128_ (
    .A(data_strp[22]),
    .B(_038_),
    .Y(_018_)
  );
  NAND _129_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _130_ (
    .A(_016_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _131_ (
    .A(_032_),
    .B(_020_),
    .Y(_000_[6])
  );
  NAND _132_ (
    .A(data_strp[7]),
    .B(_040_),
    .Y(_021_)
  );
  NAND _133_ (
    .A(data_strp[31]),
    .B(_035_),
    .Y(_022_)
  );
  NAND _134_ (
    .A(_021_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _135_ (
    .A(data_strp[15]),
    .B(_033_),
    .Y(_024_)
  );
  NAND _136_ (
    .A(data_strp[23]),
    .B(_038_),
    .Y(_025_)
  );
  NAND _137_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _138_ (
    .A(_023_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _139_ (
    .A(_032_),
    .B(_027_),
    .Y(_000_[7])
  );
  NOR _140_ (
    .A(selector[0]),
    .B(_032_),
    .Y(_001_[0])
  );
  NOR _141_ (
    .A(_032_),
    .B(_040_),
    .Y(_028_)
  );
  NOT _142_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR _143_ (
    .A(_035_),
    .B(_029_),
    .Y(_001_[1])
  );
  (* src = "m32_8.v:16" *)
  DFF _144_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(selector[0])
  );
  (* src = "m32_8.v:16" *)
  DFF _145_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(selector[1])
  );
  (* src = "m32_8.v:16" *)
  DFF _146_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_32_8[0])
  );
  (* src = "m32_8.v:16" *)
  DFF _147_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_32_8[1])
  );
  (* src = "m32_8.v:16" *)
  DFF _148_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_32_8[2])
  );
  (* src = "m32_8.v:16" *)
  DFF _149_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_32_8[3])
  );
  (* src = "m32_8.v:16" *)
  DFF _150_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_32_8[4])
  );
  (* src = "m32_8.v:16" *)
  DFF _151_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_32_8[5])
  );
  (* src = "m32_8.v:16" *)
  DFF _152_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_32_8[6])
  );
  (* src = "m32_8.v:16" *)
  DFF _153_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_32_8[7])
  );
  (* src = "m32_8.v:16" *)
  DFF _154_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_32_8)
  );
endmodule

(* src = "m8_32.v:7" *)
module m8_32(data_8_32, valid_8_32, sincout, data_input, sinc, valid_input, reset, clk_f, clk_4f, clk_32f);
  (* src = "m8_32.v:30" *)
  wire _0_;
  (* src = "m8_32.v:18" *)
  wire [31:0] buffer0;
  (* src = "m8_32.v:16" *)
  input clk_32f;
  (* src = "m8_32.v:15" *)
  input clk_4f;
  (* src = "m8_32.v:14" *)
  input clk_f;
  (* src = "m8_32.v:7" *)
  output [31:0] data_8_32;
  (* src = "m8_32.v:10" *)
  input [7:0] data_input;
  (* src = "m8_32.v:13" *)
  input reset;
  (* src = "m8_32.v:11" *)
  input sinc;
  (* src = "m8_32.v:9" *)
  output sincout;
  (* src = "m8_32.v:8" *)
  output valid_8_32;
  (* src = "m8_32.v:12" *)
  input valid_input;
  NOT _1_ (
    .A(sinc),
    .Y(_0_)
  );
  (* src = "m8_32.v:30" *)
  DFF _2_ (
    .C(clk_4f),
    .D(_0_),
    .Q(sincout)
  );
  assign buffer0 = 32'd0;
  assign data_8_32 = 32'd0;
  assign valid_8_32 = 1'h0;
endmodule

(* src = "paralelo_serial.v:1" *)
module paralelo_serial(clk_4f, clk_32f, data_in, valid_in, data_out);
  (* src = "paralelo_serial.v:10" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] _0_;
  wire _1_;
  (* src = "paralelo_serial.v:2" *)
  input clk_32f;
  (* src = "paralelo_serial.v:1" *)
  input clk_4f;
  (* src = "paralelo_serial.v:8" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] data2send;
  (* src = "paralelo_serial.v:3" *)
  input [7:0] data_in;
  (* src = "paralelo_serial.v:5" *)
  output data_out;
  (* src = "paralelo_serial.v:7" *)
  wire [31:0] selector;
  (* src = "paralelo_serial.v:4" *)
  input valid_in;
  NOT _2_ (
    .A(data_in[7]),
    .Y(_1_)
  );
  NAND _3_ (
    .A(_1_),
    .B(valid_in),
    .Y(_0_[7])
  );
  (* src = "paralelo_serial.v:21" *)
  DFF _4_ (
    .C(clk_32f),
    .D(data2send[7]),
    .Q(data_out)
  );
  (* src = "paralelo_serial.v:10" *)
  DFF _5_ (
    .C(clk_4f),
    .D(_0_[7]),
    .Q(data2send[7])
  );
  assign selector = 32'd0;
endmodule

(* src = "serial_paralelo.v:1" *)
module serial_paralelo(data_in, clk_4f, clk_32f, valid_out, data_out);
  (* src = "serial_paralelo.v:63" *)
  wire [31:0] _000_;
  (* src = "serial_paralelo.v:63" *)
  wire [31:0] _001_;
  (* src = "serial_paralelo.v:63" *)
  wire [7:0] _002_;
  (* src = "serial_paralelo.v:63" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  (* init = 32'd0 *)
  (* src = "serial_paralelo.v:6" *)
  wire [31:0] BC_counter;
  (* init = 32'd0 *)
  (* src = "serial_paralelo.v:7" *)
  wire [31:0] active;
  (* src = "serial_paralelo.v:13" *)
  wire buffer0;
  (* src = "serial_paralelo.v:13" *)
  wire buffer1;
  (* src = "serial_paralelo.v:13" *)
  wire buffer2;
  (* src = "serial_paralelo.v:13" *)
  wire buffer3;
  (* src = "serial_paralelo.v:13" *)
  wire buffer4;
  (* src = "serial_paralelo.v:13" *)
  wire buffer5;
  (* src = "serial_paralelo.v:13" *)
  wire buffer6;
  (* src = "serial_paralelo.v:3" *)
  input clk_32f;
  (* src = "serial_paralelo.v:2" *)
  input clk_4f;
  (* src = "serial_paralelo.v:8" *)
  wire [7:0] data2send;
  (* src = "serial_paralelo.v:1" *)
  input data_in;
  (* src = "serial_paralelo.v:5" *)
  output [7:0] data_out;
  (* src = "serial_paralelo.v:9" *)
  wire [2:0] i;
  (* src = "serial_paralelo.v:10" *)
  wire t0;
  (* src = "serial_paralelo.v:10" *)
  wire t1;
  (* src = "serial_paralelo.v:10" *)
  wire t2;
  (* src = "serial_paralelo.v:10" *)
  wire t3;
  (* src = "serial_paralelo.v:10" *)
  wire t4;
  (* src = "serial_paralelo.v:10" *)
  wire t5;
  (* src = "serial_paralelo.v:10" *)
  wire t6;
  (* src = "serial_paralelo.v:10" *)
  wire t7;
  (* src = "serial_paralelo.v:4" *)
  output valid_out;
  NOT _278_ (
    .A(BC_counter[0]),
    .Y(_004_)
  );
  NOT _279_ (
    .A(BC_counter[1]),
    .Y(_005_)
  );
  NOT _280_ (
    .A(BC_counter[3]),
    .Y(_006_)
  );
  NOT _281_ (
    .A(BC_counter[6]),
    .Y(_007_)
  );
  NOT _282_ (
    .A(BC_counter[7]),
    .Y(_008_)
  );
  NOT _283_ (
    .A(BC_counter[8]),
    .Y(_009_)
  );
  NOT _284_ (
    .A(BC_counter[9]),
    .Y(_010_)
  );
  NOT _285_ (
    .A(BC_counter[11]),
    .Y(_011_)
  );
  NOT _286_ (
    .A(BC_counter[13]),
    .Y(_012_)
  );
  NOT _287_ (
    .A(BC_counter[14]),
    .Y(_013_)
  );
  NOT _288_ (
    .A(BC_counter[15]),
    .Y(_014_)
  );
  NOT _289_ (
    .A(BC_counter[18]),
    .Y(_015_)
  );
  NOT _290_ (
    .A(BC_counter[19]),
    .Y(_016_)
  );
  NOT _291_ (
    .A(BC_counter[21]),
    .Y(_017_)
  );
  NOT _292_ (
    .A(BC_counter[25]),
    .Y(_018_)
  );
  NOT _293_ (
    .A(BC_counter[26]),
    .Y(_019_)
  );
  NOT _294_ (
    .A(BC_counter[27]),
    .Y(_020_)
  );
  NOT _295_ (
    .A(BC_counter[28]),
    .Y(_021_)
  );
  NOT _296_ (
    .A(BC_counter[29]),
    .Y(_022_)
  );
  NOT _297_ (
    .A(BC_counter[30]),
    .Y(_023_)
  );
  NOT _298_ (
    .A(BC_counter[31]),
    .Y(_024_)
  );
  NOT _299_ (
    .A(active[1]),
    .Y(_025_)
  );
  NOT _300_ (
    .A(active[2]),
    .Y(_026_)
  );
  NOT _301_ (
    .A(active[3]),
    .Y(_027_)
  );
  NOT _302_ (
    .A(active[4]),
    .Y(_028_)
  );
  NOT _303_ (
    .A(active[5]),
    .Y(_029_)
  );
  NOT _304_ (
    .A(active[6]),
    .Y(_030_)
  );
  NOT _305_ (
    .A(active[7]),
    .Y(_031_)
  );
  NOT _306_ (
    .A(active[8]),
    .Y(_032_)
  );
  NOT _307_ (
    .A(active[9]),
    .Y(_033_)
  );
  NOT _308_ (
    .A(active[10]),
    .Y(_034_)
  );
  NOT _309_ (
    .A(active[11]),
    .Y(_035_)
  );
  NOT _310_ (
    .A(active[12]),
    .Y(_036_)
  );
  NOT _311_ (
    .A(active[13]),
    .Y(_037_)
  );
  NOT _312_ (
    .A(active[14]),
    .Y(_038_)
  );
  NOT _313_ (
    .A(active[15]),
    .Y(_039_)
  );
  NOT _314_ (
    .A(active[16]),
    .Y(_040_)
  );
  NOT _315_ (
    .A(active[17]),
    .Y(_041_)
  );
  NOT _316_ (
    .A(active[18]),
    .Y(_042_)
  );
  NOT _317_ (
    .A(active[19]),
    .Y(_043_)
  );
  NOT _318_ (
    .A(active[20]),
    .Y(_044_)
  );
  NOT _319_ (
    .A(active[21]),
    .Y(_045_)
  );
  NOT _320_ (
    .A(active[22]),
    .Y(_046_)
  );
  NOT _321_ (
    .A(active[23]),
    .Y(_047_)
  );
  NOT _322_ (
    .A(active[24]),
    .Y(_048_)
  );
  NOT _323_ (
    .A(active[25]),
    .Y(_049_)
  );
  NOT _324_ (
    .A(active[26]),
    .Y(_050_)
  );
  NOT _325_ (
    .A(active[27]),
    .Y(_051_)
  );
  NOT _326_ (
    .A(active[28]),
    .Y(_052_)
  );
  NOT _327_ (
    .A(active[29]),
    .Y(_053_)
  );
  NOT _328_ (
    .A(active[30]),
    .Y(_054_)
  );
  NOT _329_ (
    .A(active[31]),
    .Y(_055_)
  );
  NOT _330_ (
    .A(data2send[6]),
    .Y(_056_)
  );
  NOT _331_ (
    .A(active[0]),
    .Y(_057_)
  );
  NOT _332_ (
    .A(BC_counter[2]),
    .Y(_058_)
  );
  NOT _333_ (
    .A(data2send[2]),
    .Y(_059_)
  );
  NOR _334_ (
    .A(BC_counter[3]),
    .B(BC_counter[4]),
    .Y(_060_)
  );
  NOR _335_ (
    .A(BC_counter[5]),
    .B(BC_counter[6]),
    .Y(_061_)
  );
  NAND _336_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _337_ (
    .A(BC_counter[18]),
    .B(BC_counter[19]),
    .Y(_063_)
  );
  NOR _338_ (
    .A(BC_counter[0]),
    .B(BC_counter[1]),
    .Y(_064_)
  );
  NAND _339_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _340_ (
    .A(_062_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _341_ (
    .A(BC_counter[11]),
    .B(BC_counter[12]),
    .Y(_067_)
  );
  NOR _342_ (
    .A(BC_counter[13]),
    .B(BC_counter[14]),
    .Y(_068_)
  );
  NAND _343_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _344_ (
    .A(BC_counter[7]),
    .B(BC_counter[8]),
    .Y(_070_)
  );
  NOR _345_ (
    .A(BC_counter[9]),
    .B(BC_counter[10]),
    .Y(_071_)
  );
  NAND _346_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _347_ (
    .A(_069_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _348_ (
    .A(_066_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _349_ (
    .A(BC_counter[29]),
    .B(BC_counter[30]),
    .Y(_075_)
  );
  NOR _350_ (
    .A(BC_counter[31]),
    .B(_058_),
    .Y(_076_)
  );
  NAND _351_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _352_ (
    .A(BC_counter[25]),
    .B(BC_counter[26]),
    .Y(_078_)
  );
  NOR _353_ (
    .A(BC_counter[27]),
    .B(BC_counter[28]),
    .Y(_079_)
  );
  NAND _354_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _355_ (
    .A(_077_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _356_ (
    .A(BC_counter[21]),
    .B(BC_counter[22]),
    .Y(_082_)
  );
  NOR _357_ (
    .A(BC_counter[23]),
    .B(BC_counter[24]),
    .Y(_083_)
  );
  NAND _358_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _359_ (
    .A(BC_counter[17]),
    .B(BC_counter[20]),
    .Y(_085_)
  );
  NOR _360_ (
    .A(BC_counter[15]),
    .B(BC_counter[16]),
    .Y(_086_)
  );
  NAND _361_ (
    .A(_085_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _362_ (
    .A(_084_),
    .B(_087_),
    .Y(_088_)
  );
  NAND _363_ (
    .A(_081_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _364_ (
    .A(_074_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _365_ (
    .A(active[0]),
    .B(_090_),
    .Y(_091_)
  );
  NOT _366_ (
    .A(_091_),
    .Y(_001_[0])
  );
  NOR _367_ (
    .A(_025_),
    .B(_090_),
    .Y(_001_[1])
  );
  NOR _368_ (
    .A(_026_),
    .B(_090_),
    .Y(_001_[2])
  );
  NOR _369_ (
    .A(_027_),
    .B(_090_),
    .Y(_001_[3])
  );
  NOR _370_ (
    .A(_028_),
    .B(_090_),
    .Y(_001_[4])
  );
  NOR _371_ (
    .A(_029_),
    .B(_090_),
    .Y(_001_[5])
  );
  NOR _372_ (
    .A(_030_),
    .B(_090_),
    .Y(_001_[6])
  );
  NOR _373_ (
    .A(_031_),
    .B(_090_),
    .Y(_001_[7])
  );
  NOR _374_ (
    .A(_032_),
    .B(_090_),
    .Y(_001_[8])
  );
  NOR _375_ (
    .A(_033_),
    .B(_090_),
    .Y(_001_[9])
  );
  NOR _376_ (
    .A(_034_),
    .B(_090_),
    .Y(_001_[10])
  );
  NOR _377_ (
    .A(_035_),
    .B(_090_),
    .Y(_001_[11])
  );
  NOR _378_ (
    .A(_036_),
    .B(_090_),
    .Y(_001_[12])
  );
  NOR _379_ (
    .A(_037_),
    .B(_090_),
    .Y(_001_[13])
  );
  NOR _380_ (
    .A(_038_),
    .B(_090_),
    .Y(_001_[14])
  );
  NOR _381_ (
    .A(_039_),
    .B(_090_),
    .Y(_001_[15])
  );
  NOR _382_ (
    .A(_040_),
    .B(_090_),
    .Y(_001_[16])
  );
  NOR _383_ (
    .A(_041_),
    .B(_090_),
    .Y(_001_[17])
  );
  NOR _384_ (
    .A(_042_),
    .B(_090_),
    .Y(_001_[18])
  );
  NOR _385_ (
    .A(_043_),
    .B(_090_),
    .Y(_001_[19])
  );
  NOR _386_ (
    .A(_044_),
    .B(_090_),
    .Y(_001_[20])
  );
  NOR _387_ (
    .A(_045_),
    .B(_090_),
    .Y(_001_[21])
  );
  NOR _388_ (
    .A(_046_),
    .B(_090_),
    .Y(_001_[22])
  );
  NOR _389_ (
    .A(_047_),
    .B(_090_),
    .Y(_001_[23])
  );
  NOR _390_ (
    .A(_048_),
    .B(_090_),
    .Y(_001_[24])
  );
  NOR _391_ (
    .A(_049_),
    .B(_090_),
    .Y(_001_[25])
  );
  NOR _392_ (
    .A(_050_),
    .B(_090_),
    .Y(_001_[26])
  );
  NOR _393_ (
    .A(_051_),
    .B(_090_),
    .Y(_001_[27])
  );
  NOR _394_ (
    .A(_052_),
    .B(_090_),
    .Y(_001_[28])
  );
  NOR _395_ (
    .A(_053_),
    .B(_090_),
    .Y(_001_[29])
  );
  NOR _396_ (
    .A(_054_),
    .B(_090_),
    .Y(_001_[30])
  );
  NOR _397_ (
    .A(_055_),
    .B(_090_),
    .Y(_001_[31])
  );
  NAND _398_ (
    .A(data2send[3]),
    .B(data2send[4]),
    .Y(_092_)
  );
  NAND _399_ (
    .A(data2send[5]),
    .B(data2send[7]),
    .Y(_093_)
  );
  NOR _400_ (
    .A(_092_),
    .B(_093_),
    .Y(_094_)
  );
  NOT _401_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _402_ (
    .A(data2send[0]),
    .B(data2send[1]),
    .Y(_096_)
  );
  NOT _403_ (
    .A(_096_),
    .Y(_097_)
  );
  NOR _404_ (
    .A(data2send[6]),
    .B(_059_),
    .Y(_098_)
  );
  NAND _405_ (
    .A(_056_),
    .B(data2send[2]),
    .Y(_099_)
  );
  NOR _406_ (
    .A(_097_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _407_ (
    .A(_096_),
    .B(_098_),
    .Y(_101_)
  );
  NOR _408_ (
    .A(_095_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _409_ (
    .A(_094_),
    .B(_100_),
    .Y(_103_)
  );
  NOR _410_ (
    .A(BC_counter[0]),
    .B(_102_),
    .Y(_104_)
  );
  NOR _411_ (
    .A(_004_),
    .B(_103_),
    .Y(_105_)
  );
  NOR _412_ (
    .A(_104_),
    .B(_105_),
    .Y(_000_[0])
  );
  NAND _413_ (
    .A(BC_counter[1]),
    .B(_103_),
    .Y(_106_)
  );
  NOR _414_ (
    .A(_004_),
    .B(_005_),
    .Y(_107_)
  );
  NAND _415_ (
    .A(BC_counter[0]),
    .B(BC_counter[1]),
    .Y(_108_)
  );
  NOR _416_ (
    .A(_064_),
    .B(_107_),
    .Y(_109_)
  );
  NAND _417_ (
    .A(_102_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _418_ (
    .A(_106_),
    .B(_110_),
    .Y(_000_[1])
  );
  NOR _419_ (
    .A(_103_),
    .B(_108_),
    .Y(_111_)
  );
  NOT _420_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _421_ (
    .A(_058_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _422_ (
    .A(BC_counter[2]),
    .B(_111_),
    .Y(_114_)
  );
  NOR _423_ (
    .A(BC_counter[2]),
    .B(_111_),
    .Y(_115_)
  );
  NOR _424_ (
    .A(_113_),
    .B(_115_),
    .Y(_000_[2])
  );
  NOR _425_ (
    .A(_006_),
    .B(_114_),
    .Y(_116_)
  );
  NOR _426_ (
    .A(BC_counter[3]),
    .B(_113_),
    .Y(_117_)
  );
  NOR _427_ (
    .A(_116_),
    .B(_117_),
    .Y(_000_[3])
  );
  NOR _428_ (
    .A(BC_counter[4]),
    .B(_116_),
    .Y(_118_)
  );
  NAND _429_ (
    .A(BC_counter[3]),
    .B(BC_counter[4]),
    .Y(_119_)
  );
  NOR _430_ (
    .A(_114_),
    .B(_119_),
    .Y(_120_)
  );
  NOR _431_ (
    .A(_118_),
    .B(_120_),
    .Y(_000_[4])
  );
  NOR _432_ (
    .A(BC_counter[5]),
    .B(_120_),
    .Y(_121_)
  );
  NAND _433_ (
    .A(BC_counter[5]),
    .B(_120_),
    .Y(_122_)
  );
  NOT _434_ (
    .A(_122_),
    .Y(_123_)
  );
  NOR _435_ (
    .A(_121_),
    .B(_123_),
    .Y(_000_[5])
  );
  NAND _436_ (
    .A(BC_counter[5]),
    .B(BC_counter[2]),
    .Y(_124_)
  );
  NOR _437_ (
    .A(_119_),
    .B(_124_),
    .Y(_125_)
  );
  NOT _438_ (
    .A(_125_),
    .Y(_126_)
  );
  NOR _439_ (
    .A(_108_),
    .B(_126_),
    .Y(_127_)
  );
  NAND _440_ (
    .A(_107_),
    .B(_125_),
    .Y(_128_)
  );
  NOR _441_ (
    .A(_103_),
    .B(_128_),
    .Y(_129_)
  );
  NAND _442_ (
    .A(_102_),
    .B(_127_),
    .Y(_130_)
  );
  NOR _443_ (
    .A(_007_),
    .B(_130_),
    .Y(_131_)
  );
  NAND _444_ (
    .A(BC_counter[6]),
    .B(_129_),
    .Y(_132_)
  );
  NOR _445_ (
    .A(BC_counter[6]),
    .B(_129_),
    .Y(_133_)
  );
  NOR _446_ (
    .A(_131_),
    .B(_133_),
    .Y(_000_[6])
  );
  NOR _447_ (
    .A(_008_),
    .B(_132_),
    .Y(_134_)
  );
  NOT _448_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR _449_ (
    .A(BC_counter[7]),
    .B(_131_),
    .Y(_136_)
  );
  NOR _450_ (
    .A(_134_),
    .B(_136_),
    .Y(_000_[7])
  );
  NOR _451_ (
    .A(BC_counter[8]),
    .B(_134_),
    .Y(_137_)
  );
  NOR _452_ (
    .A(_008_),
    .B(_009_),
    .Y(_138_)
  );
  NOR _453_ (
    .A(_009_),
    .B(_135_),
    .Y(_139_)
  );
  NAND _454_ (
    .A(BC_counter[8]),
    .B(_134_),
    .Y(_140_)
  );
  NOR _455_ (
    .A(_137_),
    .B(_139_),
    .Y(_000_[8])
  );
  NOR _456_ (
    .A(BC_counter[9]),
    .B(_139_),
    .Y(_141_)
  );
  NOR _457_ (
    .A(_010_),
    .B(_140_),
    .Y(_142_)
  );
  NOR _458_ (
    .A(_141_),
    .B(_142_),
    .Y(_000_[9])
  );
  NOR _459_ (
    .A(BC_counter[10]),
    .B(_142_),
    .Y(_143_)
  );
  NAND _460_ (
    .A(BC_counter[9]),
    .B(BC_counter[10]),
    .Y(_144_)
  );
  NOR _461_ (
    .A(_140_),
    .B(_144_),
    .Y(_145_)
  );
  NAND _462_ (
    .A(BC_counter[10]),
    .B(_142_),
    .Y(_146_)
  );
  NOR _463_ (
    .A(_143_),
    .B(_145_),
    .Y(_000_[10])
  );
  NOR _464_ (
    .A(BC_counter[11]),
    .B(_145_),
    .Y(_147_)
  );
  NAND _465_ (
    .A(BC_counter[11]),
    .B(_138_),
    .Y(_148_)
  );
  NOR _466_ (
    .A(_144_),
    .B(_148_),
    .Y(_149_)
  );
  NOR _467_ (
    .A(_011_),
    .B(_146_),
    .Y(_150_)
  );
  NOR _468_ (
    .A(_147_),
    .B(_150_),
    .Y(_000_[11])
  );
  NAND _469_ (
    .A(BC_counter[12]),
    .B(_149_),
    .Y(_151_)
  );
  NOT _470_ (
    .A(_151_),
    .Y(_152_)
  );
  NOR _471_ (
    .A(_132_),
    .B(_151_),
    .Y(_153_)
  );
  NAND _472_ (
    .A(_131_),
    .B(_152_),
    .Y(_154_)
  );
  NOR _473_ (
    .A(BC_counter[12]),
    .B(_150_),
    .Y(_155_)
  );
  NOR _474_ (
    .A(_153_),
    .B(_155_),
    .Y(_000_[12])
  );
  NOR _475_ (
    .A(BC_counter[13]),
    .B(_153_),
    .Y(_156_)
  );
  NOR _476_ (
    .A(_012_),
    .B(_154_),
    .Y(_157_)
  );
  NAND _477_ (
    .A(BC_counter[13]),
    .B(_153_),
    .Y(_158_)
  );
  NOR _478_ (
    .A(_156_),
    .B(_157_),
    .Y(_000_[13])
  );
  NOR _479_ (
    .A(BC_counter[14]),
    .B(_157_),
    .Y(_159_)
  );
  NOR _480_ (
    .A(_013_),
    .B(_158_),
    .Y(_160_)
  );
  NAND _481_ (
    .A(BC_counter[14]),
    .B(_157_),
    .Y(_161_)
  );
  NOR _482_ (
    .A(_012_),
    .B(_013_),
    .Y(_162_)
  );
  NAND _483_ (
    .A(BC_counter[13]),
    .B(BC_counter[14]),
    .Y(_163_)
  );
  NAND _484_ (
    .A(_153_),
    .B(_162_),
    .Y(_164_)
  );
  NOR _485_ (
    .A(_159_),
    .B(_160_),
    .Y(_000_[14])
  );
  NOR _486_ (
    .A(BC_counter[15]),
    .B(_160_),
    .Y(_165_)
  );
  NOR _487_ (
    .A(_014_),
    .B(_164_),
    .Y(_166_)
  );
  NOR _488_ (
    .A(_165_),
    .B(_166_),
    .Y(_000_[15])
  );
  NOR _489_ (
    .A(BC_counter[16]),
    .B(_166_),
    .Y(_167_)
  );
  NAND _490_ (
    .A(BC_counter[15]),
    .B(BC_counter[16]),
    .Y(_168_)
  );
  NOR _491_ (
    .A(_161_),
    .B(_168_),
    .Y(_169_)
  );
  NOR _492_ (
    .A(_167_),
    .B(_169_),
    .Y(_000_[16])
  );
  NOR _493_ (
    .A(BC_counter[17]),
    .B(_169_),
    .Y(_170_)
  );
  NAND _494_ (
    .A(BC_counter[17]),
    .B(_162_),
    .Y(_171_)
  );
  NAND _495_ (
    .A(BC_counter[16]),
    .B(BC_counter[17]),
    .Y(_172_)
  );
  NOR _496_ (
    .A(_163_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _497_ (
    .A(_168_),
    .B(_171_),
    .Y(_174_)
  );
  NAND _498_ (
    .A(BC_counter[15]),
    .B(_173_),
    .Y(_175_)
  );
  NOR _499_ (
    .A(_154_),
    .B(_175_),
    .Y(_176_)
  );
  NAND _500_ (
    .A(_153_),
    .B(_174_),
    .Y(_177_)
  );
  NOR _501_ (
    .A(_170_),
    .B(_176_),
    .Y(_000_[17])
  );
  NOR _502_ (
    .A(BC_counter[18]),
    .B(_176_),
    .Y(_178_)
  );
  NOR _503_ (
    .A(_015_),
    .B(_177_),
    .Y(_179_)
  );
  NOR _504_ (
    .A(_178_),
    .B(_179_),
    .Y(_000_[18])
  );
  NOR _505_ (
    .A(_015_),
    .B(_016_),
    .Y(_180_)
  );
  NAND _506_ (
    .A(BC_counter[18]),
    .B(BC_counter[19]),
    .Y(_181_)
  );
  NOR _507_ (
    .A(_063_),
    .B(_180_),
    .Y(_182_)
  );
  NOR _508_ (
    .A(_177_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _509_ (
    .A(BC_counter[19]),
    .B(_176_),
    .Y(_184_)
  );
  NOR _510_ (
    .A(_183_),
    .B(_184_),
    .Y(_000_[19])
  );
  NOR _511_ (
    .A(_177_),
    .B(_181_),
    .Y(_185_)
  );
  NAND _512_ (
    .A(BC_counter[20]),
    .B(_180_),
    .Y(_186_)
  );
  NAND _513_ (
    .A(BC_counter[20]),
    .B(_185_),
    .Y(_187_)
  );
  NOT _514_ (
    .A(_187_),
    .Y(_188_)
  );
  NOR _515_ (
    .A(BC_counter[20]),
    .B(_185_),
    .Y(_189_)
  );
  NOR _516_ (
    .A(_188_),
    .B(_189_),
    .Y(_000_[20])
  );
  NOR _517_ (
    .A(BC_counter[21]),
    .B(_188_),
    .Y(_190_)
  );
  NOR _518_ (
    .A(_017_),
    .B(_187_),
    .Y(_191_)
  );
  NOR _519_ (
    .A(_190_),
    .B(_191_),
    .Y(_000_[21])
  );
  NOR _520_ (
    .A(BC_counter[22]),
    .B(_191_),
    .Y(_192_)
  );
  NAND _521_ (
    .A(BC_counter[21]),
    .B(BC_counter[22]),
    .Y(_193_)
  );
  NOT _522_ (
    .A(_193_),
    .Y(_194_)
  );
  NOR _523_ (
    .A(_187_),
    .B(_193_),
    .Y(_195_)
  );
  NOR _524_ (
    .A(_192_),
    .B(_195_),
    .Y(_000_[22])
  );
  NOR _525_ (
    .A(BC_counter[23]),
    .B(_195_),
    .Y(_196_)
  );
  NAND _526_ (
    .A(BC_counter[23]),
    .B(_195_),
    .Y(_197_)
  );
  NOT _527_ (
    .A(_197_),
    .Y(_198_)
  );
  NOR _528_ (
    .A(_196_),
    .B(_198_),
    .Y(_000_[23])
  );
  NAND _529_ (
    .A(BC_counter[23]),
    .B(_194_),
    .Y(_199_)
  );
  NOR _530_ (
    .A(_186_),
    .B(_199_),
    .Y(_200_)
  );
  NAND _531_ (
    .A(BC_counter[24]),
    .B(_200_),
    .Y(_201_)
  );
  NOT _532_ (
    .A(_201_),
    .Y(_202_)
  );
  NOR _533_ (
    .A(_177_),
    .B(_201_),
    .Y(_203_)
  );
  NAND _534_ (
    .A(_176_),
    .B(_202_),
    .Y(_204_)
  );
  NOR _535_ (
    .A(_187_),
    .B(_199_),
    .Y(_205_)
  );
  NOR _536_ (
    .A(BC_counter[24]),
    .B(_205_),
    .Y(_206_)
  );
  NOR _537_ (
    .A(_203_),
    .B(_206_),
    .Y(_000_[24])
  );
  NOR _538_ (
    .A(BC_counter[25]),
    .B(_203_),
    .Y(_207_)
  );
  NOR _539_ (
    .A(_018_),
    .B(_204_),
    .Y(_208_)
  );
  NAND _540_ (
    .A(BC_counter[25]),
    .B(_203_),
    .Y(_209_)
  );
  NOR _541_ (
    .A(_207_),
    .B(_208_),
    .Y(_000_[25])
  );
  NOR _542_ (
    .A(BC_counter[26]),
    .B(_208_),
    .Y(_210_)
  );
  NOR _543_ (
    .A(_019_),
    .B(_209_),
    .Y(_211_)
  );
  NAND _544_ (
    .A(BC_counter[26]),
    .B(_208_),
    .Y(_212_)
  );
  NOR _545_ (
    .A(_210_),
    .B(_211_),
    .Y(_000_[26])
  );
  NOR _546_ (
    .A(_020_),
    .B(_212_),
    .Y(_213_)
  );
  NAND _547_ (
    .A(BC_counter[27]),
    .B(_211_),
    .Y(_214_)
  );
  NOR _548_ (
    .A(BC_counter[27]),
    .B(_211_),
    .Y(_215_)
  );
  NOR _549_ (
    .A(_213_),
    .B(_215_),
    .Y(_000_[27])
  );
  NOR _550_ (
    .A(_021_),
    .B(_214_),
    .Y(_216_)
  );
  NAND _551_ (
    .A(BC_counter[28]),
    .B(_213_),
    .Y(_217_)
  );
  NOR _552_ (
    .A(BC_counter[28]),
    .B(_213_),
    .Y(_218_)
  );
  NOR _553_ (
    .A(_216_),
    .B(_218_),
    .Y(_000_[28])
  );
  NOR _554_ (
    .A(BC_counter[29]),
    .B(_216_),
    .Y(_219_)
  );
  NOR _555_ (
    .A(_022_),
    .B(_217_),
    .Y(_220_)
  );
  NAND _556_ (
    .A(BC_counter[29]),
    .B(_216_),
    .Y(_221_)
  );
  NOR _557_ (
    .A(_219_),
    .B(_220_),
    .Y(_000_[29])
  );
  NOR _558_ (
    .A(_023_),
    .B(_221_),
    .Y(_222_)
  );
  NAND _559_ (
    .A(BC_counter[30]),
    .B(_220_),
    .Y(_223_)
  );
  NOR _560_ (
    .A(BC_counter[30]),
    .B(_220_),
    .Y(_224_)
  );
  NOR _561_ (
    .A(_222_),
    .B(_224_),
    .Y(_000_[30])
  );
  NOR _562_ (
    .A(BC_counter[31]),
    .B(_222_),
    .Y(_225_)
  );
  NOR _563_ (
    .A(_024_),
    .B(_223_),
    .Y(_226_)
  );
  NOR _564_ (
    .A(_225_),
    .B(_226_),
    .Y(_000_[31])
  );
  NOR _565_ (
    .A(active[21]),
    .B(active[22]),
    .Y(_227_)
  );
  NOR _566_ (
    .A(active[23]),
    .B(active[24]),
    .Y(_228_)
  );
  NAND _567_ (
    .A(_227_),
    .B(_228_),
    .Y(_229_)
  );
  NOR _568_ (
    .A(active[17]),
    .B(active[18]),
    .Y(_230_)
  );
  NOR _569_ (
    .A(active[19]),
    .B(active[20]),
    .Y(_231_)
  );
  NAND _570_ (
    .A(_230_),
    .B(_231_),
    .Y(_232_)
  );
  NOR _571_ (
    .A(_229_),
    .B(_232_),
    .Y(_233_)
  );
  NOR _572_ (
    .A(active[31]),
    .B(_057_),
    .Y(_234_)
  );
  NOR _573_ (
    .A(active[29]),
    .B(active[30]),
    .Y(_235_)
  );
  NAND _574_ (
    .A(_234_),
    .B(_235_),
    .Y(_236_)
  );
  NOR _575_ (
    .A(active[25]),
    .B(active[26]),
    .Y(_237_)
  );
  NOR _576_ (
    .A(active[27]),
    .B(active[28]),
    .Y(_238_)
  );
  NAND _577_ (
    .A(_237_),
    .B(_238_),
    .Y(_239_)
  );
  NOR _578_ (
    .A(_236_),
    .B(_239_),
    .Y(_240_)
  );
  NAND _579_ (
    .A(_233_),
    .B(_240_),
    .Y(_241_)
  );
  NOR _580_ (
    .A(active[6]),
    .B(active[7]),
    .Y(_242_)
  );
  NOR _581_ (
    .A(active[5]),
    .B(active[8]),
    .Y(_243_)
  );
  NAND _582_ (
    .A(_242_),
    .B(_243_),
    .Y(_244_)
  );
  NOR _583_ (
    .A(active[1]),
    .B(active[2]),
    .Y(_245_)
  );
  NOR _584_ (
    .A(active[3]),
    .B(active[4]),
    .Y(_246_)
  );
  NAND _585_ (
    .A(_245_),
    .B(_246_),
    .Y(_247_)
  );
  NOR _586_ (
    .A(_244_),
    .B(_247_),
    .Y(_248_)
  );
  NOR _587_ (
    .A(active[9]),
    .B(active[10]),
    .Y(_249_)
  );
  NOR _588_ (
    .A(active[11]),
    .B(active[12]),
    .Y(_250_)
  );
  NAND _589_ (
    .A(_249_),
    .B(_250_),
    .Y(_251_)
  );
  NOR _590_ (
    .A(active[13]),
    .B(active[16]),
    .Y(_252_)
  );
  NOR _591_ (
    .A(active[14]),
    .B(active[15]),
    .Y(_253_)
  );
  NAND _592_ (
    .A(_252_),
    .B(_253_),
    .Y(_254_)
  );
  NOR _593_ (
    .A(_251_),
    .B(_254_),
    .Y(_255_)
  );
  NAND _594_ (
    .A(_248_),
    .B(_255_),
    .Y(_256_)
  );
  NOR _595_ (
    .A(_241_),
    .B(_256_),
    .Y(_257_)
  );
  NOT _596_ (
    .A(_257_),
    .Y(_258_)
  );
  NOR _597_ (
    .A(_102_),
    .B(_258_),
    .Y(_259_)
  );
  NAND _598_ (
    .A(_103_),
    .B(_257_),
    .Y(_260_)
  );
  NAND _599_ (
    .A(data2send[0]),
    .B(_257_),
    .Y(_261_)
  );
  NAND _600_ (
    .A(data_out[0]),
    .B(_260_),
    .Y(_262_)
  );
  NAND _601_ (
    .A(_261_),
    .B(_262_),
    .Y(_002_[0])
  );
  NAND _602_ (
    .A(data_out[1]),
    .B(_260_),
    .Y(_263_)
  );
  NAND _603_ (
    .A(data2send[1]),
    .B(_257_),
    .Y(_264_)
  );
  NAND _604_ (
    .A(_263_),
    .B(_264_),
    .Y(_002_[1])
  );
  NAND _605_ (
    .A(data2send[2]),
    .B(_259_),
    .Y(_265_)
  );
  NAND _606_ (
    .A(data_out[2]),
    .B(_260_),
    .Y(_266_)
  );
  NAND _607_ (
    .A(_265_),
    .B(_266_),
    .Y(_002_[2])
  );
  NAND _608_ (
    .A(data2send[3]),
    .B(_259_),
    .Y(_267_)
  );
  NAND _609_ (
    .A(data_out[3]),
    .B(_260_),
    .Y(_268_)
  );
  NAND _610_ (
    .A(_267_),
    .B(_268_),
    .Y(_002_[3])
  );
  NAND _611_ (
    .A(data2send[4]),
    .B(_259_),
    .Y(_269_)
  );
  NAND _612_ (
    .A(data_out[4]),
    .B(_260_),
    .Y(_270_)
  );
  NAND _613_ (
    .A(_269_),
    .B(_270_),
    .Y(_002_[4])
  );
  NAND _614_ (
    .A(data2send[5]),
    .B(_259_),
    .Y(_271_)
  );
  NAND _615_ (
    .A(data_out[5]),
    .B(_260_),
    .Y(_272_)
  );
  NAND _616_ (
    .A(_271_),
    .B(_272_),
    .Y(_002_[5])
  );
  NAND _617_ (
    .A(data_out[6]),
    .B(_260_),
    .Y(_273_)
  );
  NAND _618_ (
    .A(data2send[6]),
    .B(_257_),
    .Y(_274_)
  );
  NAND _619_ (
    .A(_273_),
    .B(_274_),
    .Y(_002_[6])
  );
  NAND _620_ (
    .A(data2send[7]),
    .B(_259_),
    .Y(_275_)
  );
  NAND _621_ (
    .A(data_out[7]),
    .B(_260_),
    .Y(_276_)
  );
  NAND _622_ (
    .A(_275_),
    .B(_276_),
    .Y(_002_[7])
  );
  NAND _623_ (
    .A(valid_out),
    .B(_258_),
    .Y(_277_)
  );
  NAND _624_ (
    .A(_260_),
    .B(_277_),
    .Y(_003_)
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _625_ (
    .C(clk_4f),
    .D(_002_[0]),
    .Q(data_out[0])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _626_ (
    .C(clk_4f),
    .D(_002_[1]),
    .Q(data_out[1])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _627_ (
    .C(clk_4f),
    .D(_002_[2]),
    .Q(data_out[2])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _628_ (
    .C(clk_4f),
    .D(_002_[3]),
    .Q(data_out[3])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _629_ (
    .C(clk_4f),
    .D(_002_[4]),
    .Q(data_out[4])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _630_ (
    .C(clk_4f),
    .D(_002_[5]),
    .Q(data_out[5])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _631_ (
    .C(clk_4f),
    .D(_002_[6]),
    .Q(data_out[6])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _632_ (
    .C(clk_4f),
    .D(_002_[7]),
    .Q(data_out[7])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _633_ (
    .C(clk_4f),
    .D(_003_),
    .Q(valid_out)
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _634_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(active[0])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _635_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(active[1])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _636_ (
    .C(clk_4f),
    .D(_001_[2]),
    .Q(active[2])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _637_ (
    .C(clk_4f),
    .D(_001_[3]),
    .Q(active[3])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _638_ (
    .C(clk_4f),
    .D(_001_[4]),
    .Q(active[4])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _639_ (
    .C(clk_4f),
    .D(_001_[5]),
    .Q(active[5])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _640_ (
    .C(clk_4f),
    .D(_001_[6]),
    .Q(active[6])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _641_ (
    .C(clk_4f),
    .D(_001_[7]),
    .Q(active[7])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _642_ (
    .C(clk_4f),
    .D(_001_[8]),
    .Q(active[8])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _643_ (
    .C(clk_4f),
    .D(_001_[9]),
    .Q(active[9])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _644_ (
    .C(clk_4f),
    .D(_001_[10]),
    .Q(active[10])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _645_ (
    .C(clk_4f),
    .D(_001_[11]),
    .Q(active[11])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _646_ (
    .C(clk_4f),
    .D(_001_[12]),
    .Q(active[12])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _647_ (
    .C(clk_4f),
    .D(_001_[13]),
    .Q(active[13])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _648_ (
    .C(clk_4f),
    .D(_001_[14]),
    .Q(active[14])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _649_ (
    .C(clk_4f),
    .D(_001_[15]),
    .Q(active[15])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _650_ (
    .C(clk_4f),
    .D(_001_[16]),
    .Q(active[16])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _651_ (
    .C(clk_4f),
    .D(_001_[17]),
    .Q(active[17])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _652_ (
    .C(clk_4f),
    .D(_001_[18]),
    .Q(active[18])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _653_ (
    .C(clk_4f),
    .D(_001_[19]),
    .Q(active[19])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _654_ (
    .C(clk_4f),
    .D(_001_[20]),
    .Q(active[20])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _655_ (
    .C(clk_4f),
    .D(_001_[21]),
    .Q(active[21])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _656_ (
    .C(clk_4f),
    .D(_001_[22]),
    .Q(active[22])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _657_ (
    .C(clk_4f),
    .D(_001_[23]),
    .Q(active[23])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _658_ (
    .C(clk_4f),
    .D(_001_[24]),
    .Q(active[24])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _659_ (
    .C(clk_4f),
    .D(_001_[25]),
    .Q(active[25])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _660_ (
    .C(clk_4f),
    .D(_001_[26]),
    .Q(active[26])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _661_ (
    .C(clk_4f),
    .D(_001_[27]),
    .Q(active[27])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _662_ (
    .C(clk_4f),
    .D(_001_[28]),
    .Q(active[28])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _663_ (
    .C(clk_4f),
    .D(_001_[29]),
    .Q(active[29])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _664_ (
    .C(clk_4f),
    .D(_001_[30]),
    .Q(active[30])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _665_ (
    .C(clk_4f),
    .D(_001_[31]),
    .Q(active[31])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _666_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _667_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _668_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _669_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(BC_counter[3])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _670_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(BC_counter[4])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _671_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(BC_counter[5])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _672_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(BC_counter[6])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _673_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(BC_counter[7])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _674_ (
    .C(clk_4f),
    .D(_000_[8]),
    .Q(BC_counter[8])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _675_ (
    .C(clk_4f),
    .D(_000_[9]),
    .Q(BC_counter[9])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _676_ (
    .C(clk_4f),
    .D(_000_[10]),
    .Q(BC_counter[10])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _677_ (
    .C(clk_4f),
    .D(_000_[11]),
    .Q(BC_counter[11])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _678_ (
    .C(clk_4f),
    .D(_000_[12]),
    .Q(BC_counter[12])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _679_ (
    .C(clk_4f),
    .D(_000_[13]),
    .Q(BC_counter[13])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _680_ (
    .C(clk_4f),
    .D(_000_[14]),
    .Q(BC_counter[14])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _681_ (
    .C(clk_4f),
    .D(_000_[15]),
    .Q(BC_counter[15])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _682_ (
    .C(clk_4f),
    .D(_000_[16]),
    .Q(BC_counter[16])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _683_ (
    .C(clk_4f),
    .D(_000_[17]),
    .Q(BC_counter[17])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _684_ (
    .C(clk_4f),
    .D(_000_[18]),
    .Q(BC_counter[18])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _685_ (
    .C(clk_4f),
    .D(_000_[19]),
    .Q(BC_counter[19])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _686_ (
    .C(clk_4f),
    .D(_000_[20]),
    .Q(BC_counter[20])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _687_ (
    .C(clk_4f),
    .D(_000_[21]),
    .Q(BC_counter[21])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _688_ (
    .C(clk_4f),
    .D(_000_[22]),
    .Q(BC_counter[22])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _689_ (
    .C(clk_4f),
    .D(_000_[23]),
    .Q(BC_counter[23])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _690_ (
    .C(clk_4f),
    .D(_000_[24]),
    .Q(BC_counter[24])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _691_ (
    .C(clk_4f),
    .D(_000_[25]),
    .Q(BC_counter[25])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _692_ (
    .C(clk_4f),
    .D(_000_[26]),
    .Q(BC_counter[26])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _693_ (
    .C(clk_4f),
    .D(_000_[27]),
    .Q(BC_counter[27])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _694_ (
    .C(clk_4f),
    .D(_000_[28]),
    .Q(BC_counter[28])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _695_ (
    .C(clk_4f),
    .D(_000_[29]),
    .Q(BC_counter[29])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _696_ (
    .C(clk_4f),
    .D(_000_[30]),
    .Q(BC_counter[30])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _697_ (
    .C(clk_4f),
    .D(_000_[31]),
    .Q(BC_counter[31])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _698_ (
    .C(clk_4f),
    .D(t7),
    .Q(data2send[0])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _699_ (
    .C(clk_4f),
    .D(t6),
    .Q(data2send[1])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _700_ (
    .C(clk_4f),
    .D(t5),
    .Q(data2send[2])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _701_ (
    .C(clk_4f),
    .D(t4),
    .Q(data2send[3])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _702_ (
    .C(clk_4f),
    .D(t3),
    .Q(data2send[4])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _703_ (
    .C(clk_4f),
    .D(t2),
    .Q(data2send[5])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _704_ (
    .C(clk_4f),
    .D(t1),
    .Q(data2send[6])
  );
  (* src = "serial_paralelo.v:63" *)
  DFF _705_ (
    .C(clk_4f),
    .D(t0),
    .Q(data2send[7])
  );
  (* src = "serial_paralelo.v:26" *)
  DFF _706_ (
    .C(clk_32f),
    .D(buffer6),
    .Q(t0)
  );
  (* src = "serial_paralelo.v:15" *)
  DFF _707_ (
    .C(clk_32f),
    .D(buffer1),
    .Q(buffer2)
  );
  (* src = "serial_paralelo.v:15" *)
  DFF _708_ (
    .C(clk_32f),
    .D(data_in),
    .Q(buffer0)
  );
  (* src = "serial_paralelo.v:15" *)
  DFF _709_ (
    .C(clk_32f),
    .D(buffer0),
    .Q(buffer1)
  );
  (* src = "serial_paralelo.v:15" *)
  DFF _710_ (
    .C(clk_32f),
    .D(buffer2),
    .Q(buffer3)
  );
  (* src = "serial_paralelo.v:15" *)
  DFF _711_ (
    .C(clk_32f),
    .D(buffer3),
    .Q(buffer4)
  );
  (* src = "serial_paralelo.v:15" *)
  DFF _712_ (
    .C(clk_32f),
    .D(buffer4),
    .Q(buffer5)
  );
  (* src = "serial_paralelo.v:15" *)
  DFF _713_ (
    .C(clk_32f),
    .D(buffer5),
    .Q(buffer6)
  );
  assign i = 3'h0;
endmodule
