/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "paraleloserial/paralelo_serial.v:1" *)
module paralelo_serial_synth(clk_4f, clk_32f, data_in, valid_in, data_out);
  (* src = "paraleloserial/paralelo_serial.v:10" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] _0_;
  wire _1_;
  (* src = "paraleloserial/paralelo_serial.v:2" *)
  input clk_32f;
  (* src = "paraleloserial/paralelo_serial.v:1" *)
  input clk_4f;
  (* src = "paraleloserial/paralelo_serial.v:8" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [7:0] data2send;
  (* src = "paraleloserial/paralelo_serial.v:3" *)
  input [7:0] data_in;
  (* src = "paraleloserial/paralelo_serial.v:5" *)
  output data_out;
  (* src = "paraleloserial/paralelo_serial.v:7" *)
  wire [2:0] selector;
  (* src = "paraleloserial/paralelo_serial.v:4" *)
  input valid_in;
  NOT _2_ (
    .A(data_in[7]),
    .Y(_1_)
  );
  NAND _3_ (
    .A(_1_),
    .B(valid_in),
    .Y(_0_[7])
  );
  (* src = "paraleloserial/paralelo_serial.v:26" *)
  DFF _4_ (
    .C(clk_32f),
    .D(data2send[7]),
    .Q(data_out)
  );
  (* src = "paraleloserial/paralelo_serial.v:10" *)
  DFF _5_ (
    .C(clk_4f),
    .D(_0_[7]),
    .Q(data2send[7])
  );
  assign selector = 3'h0;
endmodule
